apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dolt-root
  namespace: b4mad-dolt
spec:
  encryptedData:
    DOLT_ROOT_PASSWORD: AgBQ5d543JKUtmOSQ1Fqq3rIB0IWmWZM92tGPc9P1Y2uyukPCMhyfHTMo+yNLDLupEOBoL/mH7pYZUsEenz15rYiBrPlmqe2izk/2rJW4RvLaqdIAQpTtA/4qG2Ve/VPRIDsZJsqwMH92r2lxhk4TyaqNmw4dswvkj2C6kISO6l1zMWDfly0p7r4nq7H6yFAvp6s+JsRJXo1mBpyJ57bzgMtwNssWtv7xAhh6y3rqmh7fwgsEJr6YQ4pVxhFBK4jSqHii7+CIeeLRRva6iJncAfS58n8lp+XB11jazU1IJC9b3iASyx8O92/6YUGFPmKPDJ/e5TRxfYc5czham8cdL6AFy8aOuiamV/YhaYr63+98uIxQn1Fyzt34qo86y3+SuZ0zspu+T2oHTKc3hgkNwkfB5EwX4YH7086IGGB7ZR15UdhoHrNbPcuyTgaK1FA838vleifmCdUDWni94HmUXWlpbe48IzOjDdnD25fQgeutrxWZBaQy+QNQIVrnEB1PST3C9NWp6DFum5mMVypRUailXsxo8k4MbQRtcUVpoB+8c08HMW8hA3Gq5x0WEQlYWRtGjUitrGrgBQguiHjrNzAQ3fvdi2Au/9xVh4fa9x2AoReL7Lqx9kg3qakkmMMbJV42i9UuyWFIIt1fsUxZOiAf2PxQ/fx8ukAuSHODsRvKBQUlrWsQptiL1uRw1mEQJ+F1oNhI2vWiPqkAFAH126c1TQ2Q6xMumHBSwC18gNxag==
  template:
    metadata:
      creationTimestamp: null
      name: dolt-root
      namespace: b4mad-dolt
---
