apiVersion: v1
data:
    DOLT_ROOT_PASSWORD: ENC[AES256_GCM,data:622zY5tcnNCuNX76g4zL00iWZT35KLXYfdSQEn8w+Ji0qHy6yxJFkYmsx4o=,iv:RQPip7D324bOU20zYCdD3abXSkkSrNbrMagenjB7YQo=,tag:xsGfInA4TUysYO9ZrfZMxw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: dolt-root
    namespace: b4mad-dolt
sops:
    lastmodified: "2026-08-24T10:30:50Z"
    mac: ENC[AES256_GCM,data:UU6VbdQBRl/fuMY1T4JAlQQ9uYz/EU5k21RYC0Ko91xgmnSyx7oDVRt0fVeQuXTMUS074LYxoRevvfxyCVOO1q0r6oqicuBeNThJps84T9QG5Wvsc9a30E/JQUB/uUdvzdtEvTcifozfTB79DYsjeoyy6VZ0i61+PMMc96XtP0c=,iv:PCr1JKo3+iuwY8VcyCouWemE5VD8xd6FEPenmY/baKI=,tag:Onr0lCogNHjdxQXrC5ZLhA==,type:str]
    pgp:
        - created_at: "2026-08-24T10:30:50Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9AgVmznaOk7AQ//YotLD1C7m31BtoJhSeuSFjLxsSdBSKUFpLJRPvpIjaZg
            mgQQeNan4LRwt0+xv0Z+GB232Q+9tSOnHx88EANW2HaAq2grjC5hcUjoDUg491Yl
            3MkHBm3vRz9vCTl33cU2oEZboWcRTn11q03MlT5Qn8s15b+5dBiYc1EvdEwYUwmV
            xyLXam6KEJglENP70WkL1SiPCjXBrIEchzV9lvu6hh4kns4QsRh4CMsDJ2hT9Rla
            MDcw2iJ/T3HKyF4jb/0b+U2xWyjLTtoKNhPcAQgeqyrTWi+Qw1+0K/W5XMQdCOUY
            0DGUEYdQer0JL+XCDe7R92hyfpZRNftRvBjZaYDWzsZBTKUVIfgwRktgbuZqrWEX
            T5l9z7+UpJJQYMhQU1RwPvuxUbW6cExvikdIdwxUe+dpST1Ust4BzDyMSW9H293g
            1EAkGP3hDYiKo54Osz1x31LReuZ7PvMrB1AXTGptnmuCbJ2jNhdyhZhsgeMKiWE1
            hWg1cV99/GPe+EI94P+fKOB7NuHXTMM16TvaBPtBQEij5k6JLyDswFo+sehKkW/m
            0uRUEmpDE2dI1gixdMYeh7zK5y3TSJrv+YiWwHj/ca5Ogpmamwp80xdsPOxGiNHp
            w1AHS2JjWQQNZEn2C+U5lvkn0Lk1UQM6POEEGit9wqopvIceEVA3IEEsMxyA8gbS
            XAE3gXwZSDHXjwWDfcEEidEPPa3ZRdMnYUWmJ+mUjWvJx12qYS6jZzfJBgHhsATQ
            ZsBqigPJtf5b9Fs0kAIJlEDSvtkho+AaRjysukWEo3XcIoeZNOkGpMpXKRjF
            =xtsq
            -----END PGP MESSAGE-----
          fp: 04DAFCD9470A962A2F272984E5EB0DA32F3372AC
        - created_at: "2026-08-24T10:30:50Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwSHi8yuDIZWAQ//ehsWCwDTV/V4u3NWltZelx0ZI21nF4Y/CBOXbOqxc7I/
            dd//24TpDrQmIda5I2Ca2n9PrTVSbb/65WIjI9bjtkzf+iGUGV2IncxIDY/vLwTr
            9VjEqnuou6LpBEdha5tNNJQ2D5cYhMY8ee/v8FBcU6JQ63ahln9ZHEUOIhWv+7N+
            uk0bvikTcpuaXWQ+vhkWugaMnlK2TTAdlV9L/juxxfzzgpBBURVp0YtKhNwH0+9R
            onISuqB2hxDdIGIb2bs5HJGp3ABY74ZIOqvLt1Il4eoaik5YhGjOwK5VytLuXzVS
            X9pWYVIuKMmXkubgoSz0iFFObaIfwI6y9fG2wrmm86PFXT2rfJY+NhtkOhUetM3U
            tORvrw7Lb1PCFxbn5OVyE8bLmUPadBiNze2ITEW9scQahrnAkN0gdXYkxHctwOT5
            fUz14CvHK+YbuDC4XkaSeHT+Ausd3otM8fNTpqTESKp6gEYQ4aHgi+e2QxOExS/y
            h7c7CnJ+nIhIkuOMSvvlsU8eipBQnGg/dUzG/FXjbnAzT8dL0ulLVvLTpYbqO6rM
            oep1MW7Gxx8j2G8Wn6LNumjyVu1bYhDLzrrA1uYQUKcn4BZ+VSbW1/vomrMjkg/L
            zfqPREHHrrWC6ilm/PlBVBy/iXnd27lvXrYz8T056LsOHm8hRnoMlqmE4fBChB7S
            XAE9GksqY0ChS1f9HlH8pe6JRF/KEJn9mkYJnViwrhwpqnE+osxHUIA1q4AqizXM
            YzZYFzzAESkRK06v40GBA9jTnrMCiEirrH9ouB0pJTheAlpXyWs1pTBMx/TB
            =9EuP
            -----END PGP MESSAGE-----
          fp: 8A07D816280A983BBC35E85C280DB66A3E8C012E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.12.1
