apiVersion: v1
kind: ConfigMap
metadata:
  name: dolt-servercfg
data:
  config.yaml: |
    listener:
      host: 0.0.0.0
      port: 3306
      tls_key: /etc/dolt-tls/tls.key
      tls_cert: /etc/dolt-tls/tls.crt
      require_secure_transport: true
