apiVersion: v1
kind: Service
metadata:
  name: dolt-sql-server
spec:
  ports:
    - port: 3306
      targetPort: mysql
      name: mysql
    - port: 9102
      targetPort: metrics
      name: metrics
  type: ClusterIP
