apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b4mad-forgejo-realm-secrets
  namespace: b4mad-keycloak
spec:
  encryptedData:
    ERDGESCHOSS_BROKER_SECRET: AgCK//K4vq68ejV5NcnOyS8WbAX3ayUGspd3RNzJkwvzVg/R2p6xQdxHu3Ry4KFjtcntN8mF2906Zp3gLzDDQ8lno62G1gZ1YpYiTe4Rpv83Q+UVV8uACZqLkXYP+e8NDOJe/6JiTeOvmLv7z62lBuGa3fQMd+K/uBoxDnJpWKrRPjKUyMj17y3eNuYJMXgoxoGTGxCnasBBpQ0Hi63wfuYdtmkNXYsYOXcoSU6j63HI4rbtCaqR/hcxp9t9KQ4HkMDO6xUKxyXTtNOKmcpoLCqx/UfhHQUsUV3CJ6+UjeWi3uwmZHkyGAFXjF/7NDMKtxZbE9fFT2xF28AZcaP2EoDqalsvDLBz7FHKQ0BDOmVC5z+v6kDc201jMoJjCHwNWKAqX4aD7Hhe8TimjkQ+HtOILdxQQWhqP3jZAM9QshhO4/zVkorcaDKBZrwb51mRdjX7Vw/3JpSu/hJyFp86cP37t7To5s8Ebx9Q0/oDqOGGKaQiElwllYKBOzHD173GUCVFVoGjlzaEn4YKmscU9YK/u2OBN0Bs1lyR4cLlPp/0YN5NO/0vSqKT/WZxUixe/TB0N9U86iyqTbmPstvONWg2TngPveoIiLe5nVQBn4BGcF/pVBtTZOz8e9mciGIG5G6+huQ6sLTyyi1/H9q17PuoDa0hxqcrDdwc95kMaXe4XKUCiR5zCCGdd8o2mWYiMUvsknycf/SIg+DBIBa+xDQSF16zluxYMwFQSabo1luMgCPoGR3nRl4b2UqWqJ5ZCy0qZG+4ILW+/fB07p8ISTb+
    FORGEJO_CLIENT_SECRET: AgCWuixHgHmGo7p8u/UR5eLQFx4e0BQFashL+gXhQ+EYRlj6tYDbgZUgggX1stNHeRIESa27cZdnkvK7fGNB1+ppJ9mFM9M99rh+fAIHMxsbSFPgZlpeNk/0A+ZNm5Bn5gdrGYzouhXxG4wfMZ245cwxgRCUs4FI2wXIh88kd7wmS3UpmIFw1fe1fgU+JKsMsHJNIW5sNY0BZH+4hOa7JuMtPlCKfHuIz0WVsw0K0acQLDJWWJdPogJ4AGVhQHoZjkj+y7ZqYn4X2+j7PCtcxqes2nILRkLSamUbsXFrqglp1KAYJ1KV1n0nYm/9YSDUYmhPQ0BRgdL0LwJQox738XuFuNbmWkUINOVc2zYa02z5lzRG1DOfTAyE9TpCvqJw2SSHsWarAzDE8msu2VNf6y2MfNlRZqSiWKAPu8W6pP0xW6L6k6zxI3YlDm8CpIPpCUacfSTdDHkp/OGLfGlUYaTvmhaUNhKcvOltZVQzxGNnT/nlLxOvm7NjJrCC0rwvkR4eLjFcl8QRez8Vf/F4ae+gYupsDa08EAq81AV1Lav6XjiSqqE7oZXuu8SrUynMwKP1q03XADj/4yH0/UTQ9jHt1sNasLilhHSF1eNV2DUmN++puwvuL61Kg/lK8NrDAznj1zFfnj2dFnzjbBhKKwFucScfETzD4FsrWMpwGTXwCIR7Z1oU91K4NcootsDZVMxPJZPPIBBuBMVnNQmh906j1yhqoLy9JAenhEwLDTpT5A==
  template:
    metadata:
      creationTimestamp: null
      name: b4mad-forgejo-realm-secrets
      namespace: b4mad-keycloak
---
