apiVersion: v1
data:
    ERDGESCHOSS_BROKER_SECRET: ENC[AES256_GCM,data:gDp/RSfIoNHUJu1R7BZpYoUxGJYQVfh9drVKErxCdbHkFOcl3jL/TCY2FMrsig/vJMEJ5NNI0H38nHI0odipN8vGcjPqIPYN4Ssq3JGf+zm3yQV32oRMSA==,iv:ulpTITpHf54XvUeNk46lwwzxhr6jUZYdYJKeqVW0viY=,tag:QeX8qoxzY6itlfb5Yep8pA==,type:str]
    FORGEJO_CLIENT_SECRET: ENC[AES256_GCM,data:bQYs62QK40IHMUOeBU+n7YYEDnFAV1E/027B9OOtXhODhinbM0RdOC/p6kY=,iv:Is+7md09SsAVaOFZoK4O8Aiu8pnyaMOAnRov7Q7GCHA=,tag:Rapj0j6lbF2eGJ50VOGRDQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: b4mad-forgejo-realm-secrets
    namespace: b4mad-keycloak
sops:
    lastmodified: "2026-07-29T09:34:17Z"
    mac: ENC[AES256_GCM,data:hhWfARNeXZXz1MtfuHKyHVQ+08AnLCHTULDcMK8pqhsfRfe/UV0d8bGDneGrud3PT4kMBqh8yEaBd34FdjDwVz6vdqHlS6aGB3XjyVb5mIHmordo/g2lDfzjEIH2URDdLDRGYavNBGarWakfN6Eo5smmfSxS7sJcGPDPeS+JNcE=,iv:aupGEukVCEk6iCqsR2uOOoInOpPxvAiLu0xuU3aa5nU=,tag:8EnGYKKJOzmRcEbcxKGbTA==,type:str]
    pgp:
        - created_at: "2026-07-29T09:34:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9AgVmznaOk7AQ//X1siwCObxVlgG6yiHFV1L3Iv6LvEGIm0H6zohOstkkDx
            btW0ligdfuMehj1zi0g0c3cMZv65MwWdPDzE4FTd4y6NP3d1VgF489VxykGtEvWj
            BvQqqOnH5wVfNc0jMlcVbhXq3iuv0fhCtzagVm0osbYuMQodZeCq7ZlFzwBugUSY
            zQkyBBpx12M3sEzA2MBqbWSJW+O7A5XgYpwwWKPFYuiS4tztSG4FtOBglI3xeReq
            B4HLodLgf0EcENH6DVkyiaB/ih/o2h6CNTPT5F/7w8r/VKVIaoFM/KhRbgEMjHGw
            47MbyNy77xUVghr7gQ3Uu62CdR4dP1RmKSARTqWhsk7Wx9ViXGRqh2sStBJh4jDd
            nGG4NaYH2kSH3KheXF07fRMXfmrGTXU5eQLXvUQCnrmICHmBc+BFeL4oL9zUunRk
            SVJnW0dsvWzAi8fQIZFk5YC5FXFSnBmz5XMuV2ucYGCO902CtuiYmorLG1mhUXRi
            bZwVYZIP755K2BTrwG7GSPf+vM4nogoOrgsCBR2pjDsUzlPz2MmhoqZd/C27Mh9i
            m3nxtXO0Dax1xycxjtok83WOMgOJksQimz8X/uVeDTw4J2j1oam2DUCi/6eGlQAi
            UGFjnyTSfP4EFG4jxVrv9NUpT1He7QurY3Nb1qzQ1VABn1YQDZoGZjYWEND0ENXS
            XAG3uri6k4hXzH73/hLc6Q4J1hAG+i2Ja2Oizwkrc5f4gZr5S4r0YqkKBv1M9RwX
            lJXfq/VPicoztjJzoZjbAh0JmAy6iS2zcgco3rkFjpC3pcZFnLQ068NzDgqo
            =krS4
            -----END PGP MESSAGE-----
          fp: 04DAFCD9470A962A2F272984E5EB0DA32F3372AC
        - created_at: "2026-07-29T09:34:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwSHi8yuDIZWAQ//WSw6oxrXL8KDFVBitZ7HnNvpESk1HeGAo3u8j7KpZWyy
            NskqoJT5O48bR2gjvJ1ybRcEIZs1w1IHz5O2MNalObVdOe9u1ZBsGcuEPNOCxCDm
            UiD3rKARkzmF6igoA33w5z8fM3iEH3WBBxtMfrj7XT5f8EpOaOnT4S/aw3K/ehU2
            WF3zFJrxbKKWxHLq7eIUsIU3W/PObqaPIf2sFFS+bBBwS629MMrBRTpfW3Wc5np2
            pKzVCKXPnq9HZdadYEWskPEOZoAXLLRvHDK9wWnEG1Cy3/+WEG/wbW77+o3mKdYS
            VXWO0QSZV+PORX3lhbRFf1m4yLDgjtxqlrIRwJAVlw0h+tKehyGNs+B6h4Q8b/py
            SLcqI4k8vZxMHtb/FOjoq0h1iIzulc1vxJRkyfdVN1FCvjF7HWp54QTE1HxiC5T5
            Qco2z3xiOUWYUmCLVn4UeRa5TYumhdZe0e4+8iJLOnv9kND04xlB+IkMv4jYWvP1
            J8QR5BfOlBx46Xs458OV+nPrMO7WM8mv6z69ZeHb7l/8q37CeJYCe95asKzUK2Di
            A+Z/4SijriQv/wJ9/Buegu+NUz797vYp1Hi2X/QpjZLa/8ZECbWsOaBIV8dfkexG
            kw20VMNiGPE8lCMZSJKfLkC+Mma6GY++QCZDS3w1X+PoygX6ZaHaNHT4RnxOfXnS
            XAGHQmpdodPQFtkp36slwQcIoRPK4NTKju45DL+3NDvt4Z+nH5YqvrWd2W5+hETC
            2aTK1SbXz0wPhzM7zMKLwNQeFZF4iUt4Ndmtc8QnK3uzbpDx9b9/BslMq/Ht
            =pMoz
            -----END PGP MESSAGE-----
          fp: 8A07D816280A983BBC35E85C280DB66A3E8C012E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.12.1
