apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: codeberg-oauth2-app
  namespace: b4mad-keycloak
spec:
  encryptedData:
    client-id: AgC/Q3qro4FuCgeobMcRY1rwb9K7lW0QvSC4gnYHDBV2COdS/HYHGK7YEG6y9sxMduQa+YbmPhWjCyOH58o72iFlterds5D2TaIqGevFJXVyVrDRrZVXAZHsLeQTpWTcqlAIqJSD6FCNw7t+xCVD6ixF1vL86iYyqfohzYdBo7HtfbZAVu5UulwuOGCeqsyhUOL0AnNxH+vHVIoNtKaJDflYr0FGN6p2aCmvBzMSQW/BBNVlaZG2YBhtDAL+SYnt+uKxgM3rbLqTi1HXIK1ErcHsIoCpJcFJuB2An+TffvnCSk3UoqEIJ8qdXJgj6CUES3SW7w7pyZBsAp/ywmGJIZ6BbHVutGJOmmkWPrFrRtZgBh0QVVciDrmwJpH77BWt9nj6FZ5zh/oaXCWyqRqEpMp4hO3V8YldG2bKdcuGdb2zov/bT66I2n5YHj/toC7zm4e1gAbC/dUTV+I6BOhQDOCq6tLj0YOd5fFDlJ8liN0pEcvS5XSs378gGgI4aQYXhzxLjgjkbXevuyMWnEJZ5qRfzPdtwkdmIwNAPDY2IgkJHgBtKOPHG23317NfxislDE70jqCrw1Q91N8QfORZG6ExLkMqCNAQYh7yhvZPsd54Au+BtGClUfxC+L9/kgJcqgFR+SG28vFCB7gssnJmsuBd/UuZ6a3PrwfgPunQqs1U44iXUo+DF9gYRy33Cqyw+H0hemk6hlTnS+a7wcx7ZoFyrw/++hPe4ANQ2Rs3F6W7qEWZ5f8=
    client-secret: AgC3RAaHMyN9u0OT8PF+Y1o4mmz397FXkcn0HSTbE0kWYuIJSEIQ1PCgXeFGlNaKke9PYOiIcODs9lDyd/Ui5umlpn0squZif+VXMbstnhGXrkNlXa3zx2J3DBM131BLKgJIbDsI+m9Cr3qa+p7Cb0PM5JmsTCMYYeZFEPxoK4CKrUq7rSlLrTP8IilUbxPmoWFEQsAQhUSpppBMC6Y2CuF6V7ptGoaWQGkRe3WZhjXTc6UtrVzkpupKz7KGbTQc0L78LNHxWJHK4WhhRB4Cjyim4Ced014agUdtLRxAN0i/NIY1+7f7AEYco23bUE6x6LrQ4rLUR1+oXdwSHKbfNBzzevlYhfzRFFuq9SZgGzfYDnJ0JDcTt1j3fu1M+5fv+kxLwzS9E+iZU3j3P3TU1TNy7FXkQFqG3AnhweUJduEGwzUi8zomyvImji1fmlxhhcewc5fE4S1FymwHe2r3yMkqFbw6i1r42FNFLIyzSYlE/w+zIH1TnBfQQsYdMtmAEa40E/xYoIi78cZQYMy0VxjF1gzA+DIip38NVk+BXyfYeQTQvyR9cDcQkU1fvKHtIsyXTK+kVTm5EZLFm1G8kRocmBSmSEP/4YV6QPWnBed7aUVF4S43a7ddX1BDOdJ8fzTodxsJoUHkE2Af7sXZ1JdrSx/6+WCfqwCFmrAdtJNEbcdSGMfXW+YE6OXS2dZBTDoMt6t8CrQXx6zWggdW2x+SA4MelN7n8rBD2UdncHZPfd4cRNker0iLfPEDV9SRyz1tKLBoGFZ6Nw==
  template:
    metadata:
      creationTimestamp: null
      name: codeberg-oauth2-app
      namespace: b4mad-keycloak
---
