apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: b4mad-hookshot
  namespace: op1st-gitops
spec:
  destination:
    namespace: b4mad-matrix
    server: https://api.nostromo.erdgeschoss.b4mad.emea.operate-first.cloud:6443
  project: b4mad
  source:
    path: manifests/applications/b4mad-matrix/hookshot
    repoURL: https://github.com/b4mad/op1st-emea-b4mad
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
