apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lage-bonn
  namespace: op1st-gitops
spec:
  ignoreDifferences:
    - group: kafka.strimzi.io
      kind: Kafka
      jsonPointers:
        - /spec/kafka/resources
