kind: Secret
apiVersion: v1
metadata:
    name: alertmanager-main
    namespace: openshift-monitoring
    creationTimestamp: null
    labels:
        app.kubernetes.io/instance: alertmanager-receivers
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:q17tNvbDCmVmcLZK3gMQ2gqKHCM7Ay4V5I6nEpEyqYF2tBNZ22xvHn/cXAo+xQgkkNaFsKcV0e3Kqfr/Xfcng4U+8yZoUD0M/EfNz0u3AJU8v2g1+nhq1Qn1HpHBRIpvT5XeThqil0MwvioyU46gzwGTtrqbWOwPxBfeWybuvLEwsheFWuEEt/ziGMkAjiX8Xiityv8fOHuY/94H1AcDGWHcqrrIfEFsODr6Bz8es/O6tb+baZeDrN4BZyxe3b04lK++2mOW5WPuyt7CjJb9V5rYFAR/0Qq3wtRDek16axzeBzsvx8droVgxYXQ7QZ6T39ZQat77oN17Z7se/9TxXoQ7mp2C7EjLRGRoD5Eobg9hX3qLjGS2cnDswnj5s1SdYTx5hwjEun0lIIQ3DzYTfNEJ5UGgIrLgCkcaw75Xxy8PomLbM+MNOLavFJkeMAT6wsIOodC/JLUduaTe2TLmaiyQLn9NTJ+MdkfptoYypqO9HquTmEeLwbwzrjdFhJU6SaNkr0S6XZNpQ6YqtKQ21joPMYKlqPaYQYpPp0oIQP5OciDfb7UNWc37CWchdnBcS2EAEsR/ne2EMlwly9E+rk+XZwfMBH7NwKHD0a7trmZE9Ts1Y0jrLVMX1slcVfCSuzeR8N4P8ESs0Epije+gU/SV0Mh19SzUXsuRdVNLI8b07hcnX/VdZKKkCaUHKb6vDj2Lwby8jJeXFu6nBn4tfnJKverYbrG4+bqW730z/qT+pM62xCGQQIh7brV5N+5IdR5zhyU8RXS31p92ZXj0bONM3+B7/3LblQJban74Y+nWpKTzY1wxnZkTnznYj+2efKs3XyZ06PnzIkjrdXttV8Tccr2T5Ju3gkOnHHf3sQbdkqshsahzWGFSkARNZK/uwp+DXLSyx/zhi1BMgsg/AY4+3KK8AmCxYejx4790B2cT3973vciOaSoFVnj4k5Ilx3llMeuy65peonmUtyik1edvTa6TofVoNQhLlO3iuyfQalZw4qeGfbWURZsMhUgMLxfZwIuavxW7H2zRwj4=,iv:ScqnuGZhACzeJDEmSQeFIrr6FNbJ77UTc78tvfibVUo=,tag:pM3XFVbratPDaaTr4nQlBA==,type:str]
type: Opaque
sops:
    lastmodified: "2026-05-06T07:40:44Z"
    mac: ENC[AES256_GCM,data:KajNN/9qoHtMKwbjzg5xAynvm08nN0eZQz4K9RhUpKsvgWqmaCNVd/TKznhGrFK4TaR3aCnThjolR+yUU/YQSPszLJlVqBIg5E7nbL7eKlY2QeV166uQbjLSHHRPR1Je5z//ELJva7S56lhfkMmBAbfLzUpW6PUmcp33ZJ3VMHI=,iv:gx8oec6gZ5v0Luy4CcQPVP7EMRgQLHbATFTg27VHlQ8=,tag:tYa8advpcA6HjJV0l0hVdA==,type:str]
    pgp:
        - created_at: "2026-05-06T07:40:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9AgVmznaOk7ARAAvfXtyZGR+6r0hpvLjyF8Fro+0Ei7BLUHW7dGqTyILYft
            /vVgrtshU3l2NVcdaZpOPeojoAcK0t/lTQX5fMp+Dz835+xUd5Dt262CRytuMXGY
            CxJQcvq5RNrt8O4jebYoAJR4tB3EpzSx4+Na2xjtFI3akMkllJXUg0CJPV+Bf+YD
            b3A4E+au+9wvevt+vZloze+zNzs2ZRkd0lrfkF0SZTnYUBgQ915uVVf3P0mRFUST
            Dbrbn6DV9hV/M3SAr1ukuC8v/wCU4nvGaDeOHERtVCUBn2ok3pN3hau3iE6Kuibk
            rKyF1LWZ9gAT8+YzoyMKfNU+NFnOHG8tFtoGFyWSkn/tHMPbeaU4ZV6V2cKfodXB
            dPBMCpdSsdp4zDIx+Q6KXoAX9d/ME2Vz675/CQfNuBDAaeu6bUnMk4/+VDPrD/8i
            ypCrOeeKwk3eZIEyqtCJTwjMw4Wb6EVsKf8Sx893r18XwU1XqJlW0M3jq0HaZWw0
            QYsX89Qz5XbicEWrjSBPEssOq9aSCKalRwV9l3x9HmhJ+sGFCS4v7zE8v0QXWKiX
            Mk8TJ3y7QRwVQLS0hO0zMJeNmWWFPkTeT/LQ3BJGdzQmJ0xrUc3whf7cPGAmc2b5
            K75lJBvPI3sEYFed2c8KTT7ALOTRpFDsYJwiMKLaQ1rHwbrg1xykWX78AvIfdf7S
            XgFos0ExYvsMQkAT577JKWSw/NBKAN2K7J5SXKf/R7Vi1sD0ZYRWpE+6eST9M/Bg
            2gGX71B+ZhTOtQ6JyeKn/eYIqi75PJ3FoiL1hS/BRuNs51lpwDmoFg/ndE3JTgY=
            =VoIo
            -----END PGP MESSAGE-----
          fp: 04DAFCD9470A962A2F272984E5EB0DA32F3372AC
        - created_at: "2026-05-06T07:40:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwSHi8yuDIZWARAAojpn5GGeubHbfgk0rVr+NeYqXZ5a3fKRiZZwjQGAsBAb
            AD6+kCRqQSIlo9G0RmemEcMwcUZkkINJti3ISbcxORiGmM8Lc3tGz45iX05vbSFY
            oPE4IGgZGZvprxfPPtbHIEUkwWO84Rz7LVojka+u85l2oejuyi3Bwy5rTgi3Ou01
            SqeHsdXyyuDz+/qItTG12rfs0K8a6GTc0aKSjBo0fk4C+6g7eCi2q1ukLhqIkxIS
            p3Mbv9oQfAqxIHqb0E4gz1oDLrpm++3rVcYjrIlJcWnshYFwBp3kKAMf4RxeUIfv
            4La0oxJRfq5o00U0ehranD2mTv9HsBGUeSrGhKgEVFkgqxEG0Znp0sHStvrmlsRt
            d+kXbbSH3TCs8sn6ncVOvdYXVwAEWsH/XCZj7XLa87xrbw8SErXPi2w7cooKyluI
            uuLC2OVnRfWfoFYBnkOz9av5h6tzQv30vUg/20Wq8m5dL2a1IGLeqeNV7JrfKOSK
            IHe6pXBAghSKp3GFyMLGyJAAebKFQfxrp8OjSLT5Pv5WBn9dolYF+TiBF+T/i3HX
            lZMQ7rOJFg6FEr0Zcaqu7dzuU0IdwlGCidlibyEG8bFKBtVdQUGcfI79hwKYHxeT
            W06j2zjcMnQ/01PGcG6wI84rMv0BcELmH/+7k3BUG16fbbCcMAQ4udxgSW7xGabS
            XgGWQ2agG30IN0YVv47FrWgwUYjhdjjbVp3YmQaj6T/v1wYzii9bRWR/F1Umv2Oy
            o5Le9QwDlbICr7ZsfNZwOQ3Mlvo567R3GQyJTexbOnHj83RPHyuU85MqWlig5ME=
            =9TjV
            -----END PGP MESSAGE-----
          fp: 8A07D816280A983BBC35E85C280DB66A3E8C012E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.12.1
