kind: Secret
apiVersion: v1
metadata:
    name: hausmeister-deploy-key
    namespace: op1st-pipelines
    annotations:
        b4mad.net/href: https://codeberg.org/op1st-gitops
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: b4mad-hausmeister
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: b4mad-hausmeister
data:
    ssh-privatekey: ENC[AES256_GCM,data:TkerlGbfszPScPi/Fl1XYnlX2O7tw7eaSW61yYkDhOi1At4MOlgoKSQVK4qhHsI0XTnp0H6iH640T/pfYRkk4wFyhG80KfAUyauGCKvq9tIdsBwq7wf4Gpu+w5lbCKNMSPT7DBTLmP76hfevYCv/DVhqmMQt8LdQPX8v0K1sfbnDOXQcmFUUBOh5Q+M8KwR3OKzWDxiug1C8lv+lBFHoWQc1fE0sJll61dAznyIzbPccbzTToZmj7N0PgNa7/7q0SNE7erNksonB82NUcFnMPnp5r4GLXkldwi4nsMCj1GQhok5/vIUDmC1JTz32qth0hq+Bi7UwQ3idDiyWAyjnQqCtqP4X2LyqxWUGmWp5zp8UPofcG3jfKIFhA3NDVR0C/e0DvgMYBgrMEi1y6Ha6yvCY0YlCQL8QYByTk/LO/M49UPoxp4K/i11gP5FsJWdRjvjmkZ9LnpX4N98P/8SGZYAIwcyjUP0tm1Ea1DlGiEQJ3nPQbgYltnQDFHzUXpKW/UdpgjinedrIUT9UYah0vP4feJ6QlEA4ZRenJ1a8BJj39m5C1x6ASiAm8QP/QXax9jaeyN9oBwdg8m0HFiSGXE7w0e2dXQpkRjH0HSAKvza667jeCgGX7V0pG6b0zvlNkKI0JKgLGwTIEOj+c6Ih1SrmfQqvlpPfwUkoBvxFr5jobR4lg6Z1VYvSCxfqkhNXs2hwj73Fng04SfHe92j6sUREWsL4myOanXc/tvj/Sw4=,iv:FulGEX6i6Ptn2yHo+VOZb3SqT063HAzmaQQzIVzBHxc=,tag:vIkuZqZSKe9ape/rbi6xNw==,type:str]
type: kubernetes.io/ssh-auth
sops:
    lastmodified: "2026-05-21T13:48:12Z"
    mac: ENC[AES256_GCM,data:+egDG0qi13sz+YiubKoRQ5kiwfFS0btxRg68HqQhvXm5cxQ6Lnp3VtK0DKK8Qy0UV5pmd9hsFnXfeMt1xAFVvIu4OQPIJ3ykrHQcsn9Y9At3CELX+LsLTZRsphjopSO6b3b+CcTBfRHLPdYt4C+zUyvm91Khp+vvLCioSHLS4as=,iv:KgWCTzvacOcRxGGgHsYDiyohMiXAKww98ofcO0xCdD0=,tag:x12W66LUFeFEa81VKT1DVg==,type:str]
    pgp:
        - created_at: "2026-05-21T13:48:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9AgVmznaOk7AQ//crNReIgbkENVdjwQ6HilunPhExLMm+7AWPv/2vsnc6AZ
            dIStgioOxwSX/N7UCXaP5GecInJgerFfEwD2ouS9ZpXJCkNVLUyFaIEGKk3pOYX/
            wz+kieDmn4zl6eOu+/Fq7hFOZjSS0vXvizvPK2RU2vivWt0RbcXd7xf6cxT2fGFe
            NMSnm9gdF/dsyM0OfBoo2oTQr23+B80eOuSXg8kuGOc6Rcdbf0dUPxWiPtFR9EM/
            RMUG7HdgBnD4BnLdCtXI9CGoj7gqkAkag5p+hgnijwNZMsof6VBFEr7AteFwL/IT
            7ZjzMAtD4BGcQS7oypJhXsNviKGAGZajauH1KVkxMpavYAgRasIQdU+mGIB+XZZV
            2/L6Ji8pikcZXknskl2akveGSmVhyWUEgO1H3eGbhClgC0CNSHP+H41+El3e0ZIp
            xgMoXpeMjeBK37u298Z8ss1l3VJifCrUY6w7Z5OYmFkkcWtJqUQqbSOwTwUBT+dH
            ScZRl46FAKBKHnS/sHHd/Q/2ABbDZg5csHS+F5qjt7+EizY6Ja0OVESSLKlfagyw
            o8UC2dV0RVe5IrEvJhUfo25Cq5fp1WVi6oIHsEBJCTHzeEUHjirCGt88AvRp5ZE5
            WC1mzRZgFhFRdcKqPNOsQ8xC7TFomdPtbbnDixKpazYvl/2rX6s7t6NU0AbySoTS
            XAHObPXWbkDzhLzNPdoF3M8nto57XqrLNEST4lS2MlPhyESD+p65xFLFKqXZxl1/
            wKL+BzxAnp2f6crK56mXrI6nNpAcsBWbRYhNjIqC3T4TGnVFrJ56lM9cVoqi
            =iHmY
            -----END PGP MESSAGE-----
          fp: 04DAFCD9470A962A2F272984E5EB0DA32F3372AC
        - created_at: "2026-05-21T13:48:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwSHi8yuDIZWARAAj7RNhQDYeEHZHFHk1bo0mLhbszwJ50Y7vQTfbHJKMBCh
            UWqji1bWGspt2+RlCIC9/MdB3CGu/ti+IuNPLZ4Hl8ZnM4cxM8HD4FgI+IksoQ25
            TDQOHZojixOSkqqWiJuAYSwMMjdjZNZR2UliPQOhNKKJdyRlFoMfHiF9CYUTuza5
            pSZEKWqiRxAiDWPC7vpVWowiLQlDp2q7H8ux3GiXB2zz7ZDtRUroISvKMprflPCD
            SuXCbde6kGRxqyYH9j1BY7A9yyEGVsWA93pBOPG8IGfW8HUSlbUXtf3mFzVIicOD
            snvnlgFaf+Qq8MiHaBM3nIQV963bvfz0sXu9ljHuyXYRjnGZD+yYJddYWhGoVRuM
            Eqj7mAX297dvLGd09ukAMW4dyoH6rpMPx8yOSfglmc1fFJ+I0gLxAimutLKMcjgE
            KfkOF4BhY1I0THLOaabGngUwy/DUS2Fh7K+utxB5Y1NUH5nnYWH4GDuIaLzYnJsl
            y5TxzihtfB6VlgsgQsPX77y/GKd9u4K0Esdc/q+/GEwwNpy9ndG6ez2Z0tnR2T29
            wM8i8h/Wc9r1hj2i62BlkWg+zb2ywDn+CTa7X+Rdv1hrfY+LR9LvX0qldBJjyCTx
            iMxC9j7oBbA2VobwspTskvBFkV4tmb+SVqX4fRYdzvoLsvW2nPXRAKe+vQlouHXS
            XAFZe1nf2uexgSAwDAk2uVhJO2vSvVgICRNUCs/OJTEEqghnOMNh4boxu2PzuSy8
            FkQc05U/w/dguQ9qF98wdwOLO4SNCozsYDWRWSCx7m0QckmbVI7eSf+h0cLv
            =KsJ6
            -----END PGP MESSAGE-----
          fp: 8A07D816280A983BBC35E85C280DB66A3E8C012E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.12.1
