apiVersion: v1
data:
    ssh-privatekey: ENC[AES256_GCM,data:yX9oft33iicGtPTjhVL+tCL1dUi+Z6Z8WU00rfHJSCKP1OSVPftWOna4OEIsXae8ZOoOLIEyuDkWgYo6FYH79LAobA6h7SwuDWomIGYwyFPdhLaRQEt+35WuPVrPSqq4tE7rwjERK9kY2wRNLGChi60c0bMbujJAyHNKU9vaW5TMLwQAcxdYTGQBrUP+IF23Zxo5Fgt1NU58xpMcrm+QlyPUagTVrkKlhYLlq+9sUYyItOG6U+0hl9uGFMqic2qsfuhEdX6F3AhfvKpxITqb/oht7seJ5lQ8EwzNpvYFTOkKevDSVQiradxlmVPbRfPbuEdC5WzziFpy1XPjMybgGppAZamiiCWf/oaEHEfEDaPUEOdDsaN2HOYPpaeBhs8MsvLynnYeCdeHCks7z0roH3aALtyl0aedPvX0cKU+Zhcu12AX+8rG9/j9HOh82r/Jst4QOi007d5EWoi71xG5wW3wNU7hqjEZfdcqOanlZqsNNziC/9EaKSXtTJiJdPV5JpX4BL2gxvC2omi2Z2bdV37Q6aEx+DsUV3RamP5W9Nn7DcFAkvU2WApmvzZHQYaQQgGejtcF7Ol6vbRzcf3D9VL3I+inuNZq6y+Q7tLIkbKTx8syqSq8uI9smoCjZQWW+31UH0Ip24eJlYrTRYIpuxDol3ARtAhkk0NY3i4Gtt2SDrD3DT8lW8gy6OvZdPz7crR9X1DnC7g+xcHJU0z3fugyFE4kqxU2fIK0C+sjuhfZHPKGl8KRrVr7NFzOp/EJ,iv:/reo4fTwLFIy+4b3lasPMKJdaHK1731jMOPTvQmbgCI=,tag:sit7i8gJ7bkUmZtk430baA==,type:str]
    ssh-publickey: ENC[AES256_GCM,data:g7CJmYICkoTK7uLkexEo/5uVKsSb48n1jrPoUcDJ8tU/vkkFBbY7g60zOFRPMVkUZyZgqqBNDtWf4vhlatpo2SuDU4uiL+RwuRi5xA1Qrl2SXGHk8wZbtT/qxDVkuTn+l/bHvNTD8q23WnB7LpnS8HiRg6n+teVoPYZWrUOfY+9AXrAk6ezNYc/iD/qcP3gvXio76hePHoLGBBblG4z0hQ==,iv:/AB1BK/BS6UQ6wqox/ExPBIZYNetd9/QDxHWWqRrSpU=,tag:U/aIufoe3zGWt4aPqpfM8g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: codeberg-goern-hausmeister-deploy-key
    namespace: op1st-gitops
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: op1st-pipelines,b4mad-hausmeister
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: op1st-pipelines,b4mad-hausmeister
type: kubernetes.io/ssh-auth
sops:
    lastmodified: "2026-05-21T15:38:34Z"
    mac: ENC[AES256_GCM,data:vyEG74KWcRCef8RPhZ64uOiVQ0iRj847BNAdZ22OUzb9Ah91a2JxeIddxxaCgi11gBtnuA7TSkYWQVuXixN4jWgkwy2dwi/oGsiVoeXABXIhQ4tXmdQtPIRQKBEcctFD6RoJs2WRxDIrArgRFIwlDbR7pudNS+tIhWOXgzjcCfE=,iv:zrvJBCtMh6iFErU3H0FOIayCdEvD7xeFWuFDJ5C8ig0=,tag:YGM9ocbW+8rHddl8rTewQw==,type:str]
    pgp:
        - created_at: "2026-05-21T15:38:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9AgVmznaOk7AQ//YpGsVBvoq9/U7rMxVt3fKcZzakejkfEPXFdq0pFMTiDP
            k0XJv8h7LVa4ksDGhF3YLDwSkE9+HmOiE070YswbeMgEWPvrU4VH2PQnHPm3CUr+
            hVO2W9y3hUGl6L+WEfBk9jKqjBiGpYUQbEENchJ5LTg9HnBX/6BCs3UDxYycm0WH
            JOTCvVx/pjmXIOwvoursHz4szUB/Ho+MVRRnV7Yd2Fc95RlNQmuUgsdax20Hs7cO
            byEwYpFdVRVyTG+68vsUeGl/uf69MTeVo+GE2bWOsFfm6EV8wiRGJ193A606XpwE
            P45wqmkxCdwn0ZDnmTJc5F6BauPmR7YbXRaZgVQEEGlh3AvPX6OVtNfXoH/ipe+t
            4IaKzFrLD8Y7OQBCxunpZu+wPGn9tIA0/IOsj4xLJQ+yxNgqBnWVtdZkeN8eQT5r
            UNKuJ/WPcoUdhRMw3TQ4Z0QYzZr7cJxnpFiUs6SUjU5mf4lGXLd/g/XsZ20AE34G
            yWOLXm+4ggftYDsOstQr1KfZQxl3CHqTwiLQ2v0QtXpcUB5vpEMVU5C/CVEJPYx3
            TgWkDCvpGkNekX1y1SvJv8BfosMqqKwAqfu6qp2ddTEr3jPpgXd3ohwLB9puZ4uT
            tELW6Tp70XCn7snslV2a1MAJehbJXc0SU4VaxTmVm6FAApQG7nruwkywtWhMLzfS
            XgGPhmBn4mmccj65ic21321pXcxd1q05QH6xRNN5I05YqyquFtuM6TC31o5hHgmM
            e0Wx1sei4+y1dTd8sv0TsZUOc8o2U4WLHJS1FMWPmlHTHc7IPRXAgbFYsjSj0rM=
            =OgCw
            -----END PGP MESSAGE-----
          fp: 04DAFCD9470A962A2F272984E5EB0DA32F3372AC
        - created_at: "2026-05-21T15:38:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwSHi8yuDIZWAQ//UM26TG0HP3DJWEvWJkct79AS2MMCdRsN14KyVkyMXZ3p
            pJfcP7fF5TY9kOZw/6RVX9twy17TFJy1gj+HdsqXr3vYPzUH3AjDk8lw7oDN+SAX
            i7tYlz9fQVVrOQGDWh0OUJww2ppW6zEARqgYVIJ0pm8Pq/TAZE+G74TjYSydalBY
            NV1aHw84chyqSyC6l3Ev99sfd0AdGzqX8LHwqKb0xzT5U0iligu58IKc0ZIAb8Kx
            Wu00PegUPkiqibP3lqlWn1YZGpqpVeuYc8qts0WXwcs2jpi85MFyM0Bmq3IwAj6d
            7Wj4B7c9kjuH+A+OLNfJdXYy7w2PSEzXm77el09WCXHIdvRjj7jknaDSuoOad/Gt
            X1LKpA1lGYS62c7PnddBp5MiNC2+k3viiZV2WTg0ksjil253YSXcTOrKlaK/2sr4
            MeDNi6sgPvqByyVmZVyP7BqJ5D9dDJF96pIbMC+qzGDN6UOYUfgrPavSLs1fy+h5
            Niz/2x4reS/SjeBOuGC7bfvka6RXH+GQvumwTYdOfOfIImnfGXhFgN9A5H4/qW2a
            gTDMcIbXVad5WGwsr261AkvloxYU3BYCCyt+0Li0NQO4gH6XAD0DCrqdFx/iv+4v
            1EtKC+jos/ZMWgTZPfBV+sPFSvnywLvTMwoSknyq9Ohark4I3k7q4iI9jGFkVLXS
            XgEFT5oPSsadArJm/fCIo9u7BjnW1dkMyxu0eH/258M//Fo52PBG4M2Xfzlh6wAs
            311iTOx/WuohMu7Ot/cejl4zHoxKTbj7WIOoXhyizGcjOP7U9JlmMu+lKmwvAgg=
            =U39f
            -----END PGP MESSAGE-----
          fp: 8A07D816280A983BBC35E85C280DB66A3E8C012E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.12.1
