apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: epaper-service-deploy-key
  namespace: op1st-pipelines
spec:
  encryptedData:
    ssh-privatekey: AgAVzCfkcivntoawg3CcTtZGCHTbCpzLmzAkjkgBcNyXwcK0/rIkNQJkFeoEa8FhHJ9BBO9I0p7GFTEnb2HDqp0v7gKZcC94LxLgfhWDR507lm1PodgYbqED/PzYys8P5keHg13ctvo5cfU9w3WV26eQrGTpXyayUCXTBl9F1nPvJTvD09C3ahAXyz9ZopnG91JYzgX1gOI8DsvxWsg/d8a2v87rfrNUnQhOlikImqAjs92zIEbQQ+HfNLe0VFotTEM3Uqgac6P2paQEV2fF8uUKOkk6hoWAz6ePu0etIm0/3ZX7W8x13VNZzJ7foMHS8Wgl3sjRnuvBHw33RDFDpQpC3O4S6qVq541tfQcKamqkZUbaBYVBcv8VXAD0lGAth36Mw3+6A4ZOwGrJCn9h10nEiAncvXgGEtrYrp61WPyU6qnAoZvVRHkkb+i7D+sn86R3i43oyMqgnPR1i6605hgclC83OYVj/3Bw4uHL9vsj/NXUeTH40/vsLL8sUt1UdTYCxAUXNhD7sDI/R2LsSuIila9YbZTaFXcOmeG48wBwwVteTlVAhWxbJx1IqF7mE/mQZJA5m0jGg/S/CQBWVPkOd8E4MNIpJxGKkv3TqcK7XHzdE/cQHcSQBh7DoscGQbh5RWaOI5Yn+DPZuQCDP6VAcxduZUw38EYu4I0iWZF4nhgKf1nPGp1UEkMafuG4rpj4WtErR4j8Wzzz9D1+FoFLRPcD0peRWKd+Vhy0ySTLcWF3DtoEXY8SOb2GDfOrn49zf/AIJo5TRESMMChkuuEW3TflRhwvVDXOPz/MsrDc1IUF+b+X53/k9AeeISFBSmOSi57CpEMaxhGxZlTO4qjU+ZdQ7g5gnDH3xy9TVD4wHb4Q7lVKwI38a8KYf6a78Advrf3psdwkOZjhkFIKTUQF7I9dsBORabXkQVuprpy14hggu6xGKwqEYtO1uQeRDA5heO0XkIdPqPF+AL2OZhe35wG+QFX8IqSePE4ZGhkDWAgLTXm+dGPQRhM64TcEYCVlIFrlu08YyqZij5UZjTx7PlFFBvcQxe5MP8eP9kO2+C0yAmFc5t+SQ7+skY+BnRx19t5nUQ+o+hiS2lQLlIv59X/XHuEdm4l3dRnQBSwnwDI0GDL7GkBSOGvsnNl0tI7PhNLu+ez9PcyW7kFHZhz+UlTtDHBfwZUI/f5fMJBSn2Wqdgua/8bZOp2WyUYbF9yvNiQevmoqT8D3Y3zcJAtB1TgGHKAfmjMwYvbvIx2S/WV+3w==
  template:
    metadata:
      annotations:
        b4mad.net/href: https://codeberg.org/op1st-gitops
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: b4mad-epaper-service
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: b4mad-epaper-service
      creationTimestamp: null
      name: epaper-service-deploy-key
      namespace: op1st-pipelines
    type: kubernetes.io/ssh-auth
---
