apiVersion: v1
data:
    ssh-privatekey: ENC[AES256_GCM,data:zM9Yxhpxv3pRq4AL7KqoIZHqildozCuy7OlF4eQYVAIkpGmaiZALjxxSOkqICdLH7WHDw6ZUmflRqI+BBrFLEISX00+ILB38X8Fyw2eiMz3061b+7Rs7Q4PpolB5et3xH9KRSMOUW/JfbY7qw70fOP2eqWZWlv70hjaS88wYEv0IF4HQ9RFM2Em1AAkpdwi1uU6Slj320xcyHPucqq+fC9Q2dJt1MLo31oQ/BPSuK226BSswA5sCLpzb++bQN4TBla1ObkbS7jNI3MaW3JCSyeikb5F6wm7n7sy1H9fi4bbbfHyk1MW3sNrQP2Lh1yLkU8LahjZWlLONQrczjR6PFyZBmHDVsmSp7aBi/9qk74DicwAdrE1GkWh6N1AplYvtrmxhNNc2CqdLVXVgmjHWg8f7DY0PmRzZI3gtumcsWnAH0qbazDCxm6q75wUaG7IS2m5V9RH4aacEdyjlNjaIj9H9/JvKp/Nc6lmzVnMPdZQB9MC0nJumV7TvIkhjWM5Ns4Q40wJgSbR3bLd9T+4X2cFqNS+9ZgVAZTuWt6qILH/+naAPhVXh1jCTOrERA5ijI5NM4QEu5JKZvr3kUTblM45LcbsDzhzPucXkBCVD4iK1im06N1+6TKWDL9cdwQopczS0SMvGCKpe04jzraWhBnOMs2P4ZoHGNDznVOZXcXjyAjTCYmSCR4sUWu/VNwcZTTEIkcxQfLYYjq7+vkwn2767t5vTyM4pbWoiNxdF2pNWI0YbrEetFwKVcxJ02St2,iv:2AWoWV8cLUHu5Er3KtzbsKmxf2vXDIc/hO1mBL7U4kg=,tag:6m9lUmcbL/DaCyqyAjbd+A==,type:str]
    ssh-publickey: ENC[AES256_GCM,data:WMEX8KqVXcLKbZNnCQXfIUG0BmK+ujF1oeSbR+ZVkFIdDLe9gulvFoXEEhb6ENWa0bZ89xjep6BCUhubuuGK4qD37lI0H0leq11uWJFHpz+pcu8QfqnRRwXo0kQAzuqVtqQO8YZUCPs3z07syNoXomh1iBKdN6QjRuILvLjgtCALzPPTfoZByL8y5w0y/7zgd7kH9fedvwxe7obozK2mjw==,iv:I5RAWvLnhZZHJAn7ttv5JrPRy9TLUjqqe6hrFJ+r8Lk=,tag:3IZByG5VrgV2tli+ebUYDw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: codeberg-goern-hausmeister-deploy-key
    namespace: op1st-gitops
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: op1st-pipelines,b4mad-hausmeister
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: op1st-pipelines,b4mad-hausmeister
type: kubernetes.io/ssh-auth
sops:
    lastmodified: "2026-05-21T15:26:53Z"
    mac: ENC[AES256_GCM,data:dCBZKPyKfb9fktOyMdiEpaTMNptc7GsXh1/3//QNsDUQdLGWVB5QjaqrxqsCYAdnsNTCvI6CnoM1b4XfDXXHagXmlYMSoW+DoMgWdeYyfM1PDCJuo+zqzzdm0nJmT7Rt0JhhWS+xXdRdPlo8tKJVbqET13ZhFpOyo9DxiLRHj7k=,iv:/plBiaD+JYBzC/NHVcaetdzLY81+0mPXUr3zeVEwlkE=,tag:69Kh5Ze1FIb08sF/UC1dgw==,type:str]
    pgp:
        - created_at: "2026-05-21T15:26:52Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9AgVmznaOk7AQ//ZMxKWtNWIoflzcgBweH1T1ZJBbkPoKsiVp4mUv1IOgY0
            UGuDuVRwpNsKR6l4if4+S5WB+SfaFthBjEexRCc6qxxb5g9HMzJKPAdddqimYIyU
            k/iILbhv4H471rpiUVq6dqwNcWH3SbTfv1vXcQpX/lWhdiRDmYDiRrAQTk1ozL6V
            hN4i2QpeSRDjLVdS4OONi0LWe54vYBvycNKeS0HXkFSVFnXW34TTal7Z2QI2MJXI
            KqwmXAuUpXLGp4iYaPZM/uawdkmh1dzq9j4p46Xcx5GcEMX82EOdCfqqxfKnQL/8
            WNEilVL7yXOw/BOLmfdybjIhXzuwGKvPRGT4NLQ1KA3aq8nu7AMzD1IoRVf6fWqx
            RdbQE2IKRyrgCS0pZi80ybD23BmYgn17pEsJ3HlCva3syPiGbnNcOJsH7IZHVVbo
            U/NohkKkczj+gKp6X7Kema3W7i8qekUL67aHOnm9Jnc7KT7unkmAmwwFHGInYt2p
            vKjIcX1laPBIWfUtOC4dTGlsyCwoLDzPkVVkakXnD9vI/aZVvCqZXpCKDs2eFQzw
            7L7pgBCnKNwe7UStHo86+JcVRwOxDjuqb8L/2I737FOACLtzT+uK9M3qICVYHvXJ
            2tBhcMAm97M1ERT718jmgrrjX3btjFnq15T6SsFz68exgz3MVPBIB8mDbaSgjBfS
            XAFIgtpEvvQ5EB4haQeTmIs7HAqKvNVV6H7DrdB1arCpa4ZqPJ7WGlHwJLKMI4Rf
            n6vhxQXiXp8f8DHmmj35pg4NtnV3md2plHgSDNRiWDDhGik6fVz+6dk2bL5q
            =0K4v
            -----END PGP MESSAGE-----
          fp: 04DAFCD9470A962A2F272984E5EB0DA32F3372AC
        - created_at: "2026-05-21T15:26:52Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwSHi8yuDIZWARAAoa3GwgMj/WF+Sy/2yi8fwjxI/AGU6Ij42RUWwSN00XO2
            V85/1CrN1zeM7aDvH4X3aZEGLPBSJnZkbeGwMhe9LO9AVag2Obh3+dZHknKDdcrs
            znfSB8yzYjcIF08rYsMNmDI8c5f4d6k5SxrIakxUbczWLTgrM6HqDmGGciqV5GNG
            +oF+BVpBsHzjHkTtPHwQr0qLZFdqyaA+/obDbNk2sN8LZirYTzTjL/WP0+r4QbZi
            iCb5G0viaJ7zA8hF54MuDyr82x98D1SCgiTqJ67IhX3r08RdstS/YOTL2rU0mLdG
            DgDg8+cfwiU8r1Dm+MvciZH8ZX9MT5Pk2YT9Mr1skGmgSJv4poGdN9EkpjieMzDk
            LcHXiphcOUe08Cttm4Vo8FbQhT4ACMf07b6AK8I413ypk4bU/qP7XJDChE8OINHT
            LAp02+ZHGHbs3uhbWA4WIDqNMcKv2Yp9k1EgIJNyDccYwcOk8cqgyPKZ2SRYSrFE
            KfkkKw/bcfkYTx1pX6wHmSSwIRUYXmr4afv9ZBLeTjtUlyK0BNtuObUg9nJ5K+8l
            QI817qiGwMhgZ7W5/P4FaNC9AnWkp4HncI/SefMJGfHsOXgpOsCJyX24DknNNfnw
            bpcJiXN0hBDs9YljuILW/6C9Mf2RYOktje4N4iUrm6LWdYO7AklIT9I2trMMB57S
            XAGHzwVhfi4Nd/ymzpeO+AQTRFKicNxp1CSLWfk9F/8eVlo2ExLQFuSse/Itwb4S
            JT1yDDhC8AOl+Yfp5TsQMNaPrAVLgw2DvEbtR9Yt0krQN1CZWZIe8F0Q1+QP
            =muAw
            -----END PGP MESSAGE-----
          fp: 8A07D816280A983BBC35E85C280DB66A3E8C012E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.12.1
