apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hausmeister-deploy-key
  namespace: op1st-gitops
spec:
  encryptedData:
    ssh-privatekey: AgB/v1hwYhaqF0QcgeiVYMEkVRcY0xeDNjLpcuMY+1AiNjx0vL4onZ7fE/6hsHPJ+edriqiU1okQl8BAc2ULyLhorLA24kTA1OJCRgEPS+cqxQCWWH6QVdFlIAGR5Gx+FyTf7fhWaTkgCB73FJmwItCJqCSwl5oA0SSl64kL/jCSjlAazK8SyZ91g5CvoBX83euPNBa+hB1qdt71wqaBdKDHKXlpfiSaau1cTFldUcpkEt6N9mYo9wTgvP0B0BmDUmXDGEnFyIxr86h8tcE2yZ5C/8+ICjNG1soLg779QALmXQhgd78xsgbLyPYp8jL+qSAb7gcurXZ7ZznPocvImMkmJCIeP8OQhxiSdKKGqUJBuW/PDTvaWz/QdsjOmCi9e+a4eyivs9caKO/ixBis6yCm2u+6QliMjODsZUSA7jSFBzszxaeWv/I+IHekAU+APNR8Uk8KxtQOHnH2e5r7cAiBJAMDd+QDqUrAxbFQejVKQCRBxTUVtnfxPZytKgLHy3/qmRXEVzEKsXvEtUuVCkN/9wljQLC3ssmKz+p0SAu5suul3naFUuGSGkAChXhd4SzLvsHupVGPjK52E8RY0Tl182pb5xtYXQv0rHr3w5T9DhOERDYL6VNIF4IYTxUYuBdbQoiMXvUmnJB+2x1rkc6foHOXZMJcdeoPM1EGyzOOG3pIflyTKOOO9us6u7Vfe8E+gdQjWfoiKNz1JAjsmDvUkhRApiFScLjSnttB2gpYoY8W3A0NFd5yalz6EMGUWJpVhz+85DuH+rtJIu5L5ufQdnh4LeHfAR6AW07DVHI9NlaxZIkoH9L/bbgAwB3ITs6up1+OaNRgwj16GXUcvQYPHBfag3t89MJu/8Xg3w7OIcqb++8g62vHN22FjygYhXrF9valXiEQRH7ZnkQldcWaBV+USEZQ0yfEmayr5vc1qHN2BtuKjMrpDLl6we2xdmC77I+LdfXsZkA4w1FYc9EcO0blBJy8dA9/+EGTW7TYSqyDv2otOHBJmS3dt9P3UbmOmGX/fFMxdrvtYYBZQ+C6XhFDiApYVlPnfhfpD9bFhZ56kFRZi4G0hpewIfzQ4gg039LeiZbUgTN8aVoeloWsT5i9TRYMhu2aCn2mfmTnbSjMxznh4AFHuCUzw5INmfxfhP9RTQwptqwQCn/W5f1ugc+v7NGJQ3OpNSNnEIGXSBSuEw7S6Dx2IbcPyG6HJGV1Vw8OMBbFE5ThxCydSfYAUAMfnNBFn3K6bEuJh92J+gRdhg==
  template:
    metadata:
      annotations:
        b4mad.net/href: https://codeberg.org/op1st-gitops
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: op1st-pipelines,b4mad-hausmeister
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: op1st-pipelines,b4mad-hausmeister
      creationTimestamp: null
      name: hausmeister-deploy-key
      namespace: op1st-gitops
    type: kubernetes.io/ssh-auth
---
