apiVersion: apps/v1
kind: Deployment
metadata:
  name: matrix-hookshot
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      volumes:
        - name: conf
          secret:
            secretName: matrix-hookshot
            defaultMode: 0400
        - name: data
          persistentVolumeClaim:
            claimName: matrix-hookshot-data
        - name: redis-data
          emptyDir: {}
      containers:
        - name: redis
          image: redis:7-alpine
          imagePullPolicy: IfNotPresent
          args:
            - --save
            - ""
            - --appendonly
            - "no"
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          resources:
            limits:
              memory: 128Mi
              cpu: 200m
            requests:
              memory: 32Mi
              cpu: 20m
          volumeMounts:
            - name: redis-data
              mountPath: /data
          livenessProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: 10
            periodSeconds: 30
        - name: hookshot
          image: halfshot/matrix-hookshot:6.0.1
          imagePullPolicy: IfNotPresent
          args:
            - App/BridgeApp.js
            - /etc/hookshot/config.yml
            - /etc/hookshot/registration.yaml
          ports:
            - name: appservice
              containerPort: 9993
              protocol: TCP
            - name: webhooks
              containerPort: 9000
              protocol: TCP
            - name: provisioning
              containerPort: 9001
              protocol: TCP
            - name: metrics
              containerPort: 9002
              protocol: TCP
          env:
            - name: NODE_OPTIONS
              value: --max-old-space-size=512
          resources:
            limits:
              memory: 768Mi
              cpu: 500m
            requests:
              memory: 192Mi
              cpu: 50m
          volumeMounts:
            - name: conf
              mountPath: /etc/hookshot
              readOnly: true
            - name: data
              mountPath: /data
          livenessProbe:
            httpGet:
              path: /live
              port: webhooks
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: webhooks
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
