apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: matrix-hookshot
spec:
  endpoints:
    - path: /metrics
      port: metrics
      scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/component: hookshot
