apiVersion: v1
kind: Secret
metadata:
    name: openobserve-credentials
    namespace: b4mad-openobserve
type: Opaque
stringData:
    ZO_ROOT_USER_EMAIL: ENC[AES256_GCM,data:cdgnAsU5u53S1aoez7Kp,iv:MldOjOP6eJZMTRjUXpBrsU/C7TLs26pXg7JLqZBWFWQ=,tag:EAmCx4WfcZsUhWfFNWOPtg==,type:str]
    ZO_ROOT_USER_PASSWORD: ENC[AES256_GCM,data:Hc9xgVOVhNvqTEEjIpiNsgnNcE7TSXBy7JB9KpfvzeA=,iv:zp/AAq2BMp7V9rZcfa0gaZ6cjO6VVrbVMPNUaZXysxU=,tag:F4TzGe7E5IrdE2xgwSksiQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData|tls)$
    lastmodified: "2026-09-24T09:40:34Z"
    mac: ENC[AES256_GCM,data:422LLBbkwpGHNUfSxlLqtvPQH2i9N+zlk2q4VIMuFBEfkNREClIIeU4slcYPnu4ba3GIPNeTWra34mUPy9biuIS6rB0VhhDmJSSlXvAqKZeyW2WM49LPSoUy/NmYl4Z4horyYr0UdOO2hHnYLPaLgg8y0drEmXHiXpcDkMowF6E=,iv:wO2tCg5DQZEzSMfLaYi4xDNJSMCetTO46BIO9j3oqMc=,tag:hgXo91rWzyNmLb72hsPy5Q==,type:str]
    pgp:
        - created_at: "2026-09-24T09:40:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9AgVmznaOk7AQ//cv6+YQnb1bqbACNZ9pk9LIb3HhlYo2+G4R3yF92Zrfqf
            hTMphbaZv4vJitVhcPh0odDvh7wKc4dkbsJy4IUXV75YZpFHefIsko5FQmvzypz+
            NO8Deuv8yaf1KY5SvdImfuo496Y7o+iWGxQQyuESF8OIyId9LUq2quLcJamZ8krW
            obW6nxQMdo+RUzsWlqxWCruguuoNr7gXTT/3RMB0D9bYHq88EtcZmqIIYm+PKj3G
            Q8Ez0ViAECvbfNISPe772i28/SCLgPEyeeYOmmsWQ0H1U7eH8MiWO5UTjH14FVJr
            3oZz6RQZ6uOJGxZCFwp7JHUrXHazUIAkc52KCxBlhU5uKioEtVkkSa6nmi0vTGl2
            Iyb30bLrLFLLVXikMy+eIaNkTGFsMGgKPphk3NcHRppd8nZ6UOrj3z4LrMivbHbQ
            1uFAwI2s3dw0spnxyr3K8Mbv9zzLtoXHAbjz3O9nZo3XswLhFPvaOoRWl7ZUn71t
            gLcpCtCy/jolTQ0X4+iR3Dq3TY3GAlNL48Qu/WCjRJXSk4MnIkCrA8oRp9noxrUM
            ScjC69rnqCwEqiWJ06SUEtp33ISpaaoad5ejzNCRdf976TLdoq97wuE13bKMbJ+4
            iZ+5amFx1d9jQ1fluQ5Ki1+bujD3XymYG/AH1uvJj4QkbaoE+VawOfohXJNmaaHU
            aAEJAhD9RiWfp3Rjrw6TZAqvZON+KoHHvH1t9lhChRQWXxgS35NKmMlSUfZfjN2d
            dONsv7x/V9nlyddCx2/4ob9uiJUJlUuLAiK+WVHiLZiri34O2NkCVKw3+xBsMwFa
            UnW6H/4mAyiN
            =4vtF
            -----END PGP MESSAGE-----
          fp: 04DAFCD9470A962A2F272984E5EB0DA32F3372AC
        - created_at: "2026-09-24T09:40:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwSHi8yuDIZWARAAl6eAioJRsDh9xmJnIzEYzuJPCrkSln8n778EYZAovW8l
            xhm6CR1Y5eGg/IS/jaJb8j5sXwMjde6P0PlzpdQx4jO786d+rfQeFhFI3EOi0FpF
            3iGFLyC0rW+5sCv1+ur7akdhJFTmf92raCgSI3YfYTss85FokiAEEKH+MHn0XJc2
            k71bfcUDvpXxMvUJQCVDN5iQXU2q4V/6rPSIPlFepo9YsstYRx/CnwuBKNgrKhn6
            kmqgPB1Tcn+Bkr/3gIVVd81onGhQOAzvxnAPxfY7m0RQ88j1hz6+0LImaH3N+qu+
            xKwKElrOA/cIqLCTHJClgDoX6ITXH1a2qY/12XJ6f72ZKZ+UTuVdz3E1E5SqYwSc
            yTeAJcQmJZTh70kf0mr62vndc6EiLK+bFxGF7/R+q66SPcJxIz7xqOrJ6fjNqcYZ
            q44K8kDlhI5dHEPWrpgwo97AViS9qFolJViD5Hj+yPLMxxAzLMsUUxjhmF4BdW4i
            0VYAWU+A40NNR40V8gFVEIafuasB/30+NSzB1c9YwrLrdR8sGAs2ZE+fauGJ9LWq
            eLR0oFN/4C0u2J490Bn04L+86ffIH6jVpfhQ84MZfQuOXs6+AUAJhDk6n7wlwszQ
            6FSBQytw+/yF39AlqmB0XSH+xrX+6+14bJ4Yo3/LtxHBsy+zJa1uuo2YmGLiAaPS
            XgFDOPOF2DME40eovzxhT//4c3gaS4Ib7lw45/Je2RTkOOF1DMD54RAzu5de/kDp
            vv+UZk2CACo3ElTJ92/Z2qxNM557jWeGBpTh1yDEoHxKA0lWyskPdhwmWrFAcAY=
            =9QOw
            -----END PGP MESSAGE-----
          fp: 8A07D816280A983BBC35E85C280DB66A3E8C012E
    version: 3.13.3
