apiVersion: v1
kind: Secret
metadata:
    name: openobserve-credentials
    namespace: b4mad-openobserve
type: Opaque
stringData:
    ZO_ROOT_USER_EMAIL: ENC[AES256_GCM,data:ss4xm+q44/y8609VgtUB,iv:BWYySJ85shAgYyjvaOHELSB/mPm4jfBUBaMCAYYqcSA=,tag:l/xYzxMrW6lZGbQF43n7ZA==,type:str]
    ZO_ROOT_USER_PASSWORD: ENC[AES256_GCM,data:xGdSUnXQUS76+tN6V2gU9DaNKgd61X1ocuMnEgOg1So=,iv:il6/s54vlt9sQngrexgN8Ocxyd5zbIIP0qEoTeXdDUM=,tag:5cs1OepEpU+INwKGxGpuBA==,type:str]
sops:
    encrypted_regex: ^(data|stringData|tls)$
    lastmodified: "2026-09-24T09:50:04Z"
    mac: ENC[AES256_GCM,data:F4fqovtU9eRzW30WCO/5jBV1PH2CD1PcAM8N14nWj0f0wzOZ/9CxZd5Y0XUJU2jSQ+vFHXWAGhtrhyr773UIEP2dtB0B6llKtpBLQNaQvyWT2NCLi/Xnce42skQNvOPA6A3viiRVsXogNKsqBWVLPAOAvPf9NVnc12aWLtiYrD0=,iv:+05vKjr/X8y7iQoYX2/kJBTuTg6ELwEqb0QhgPTU/Z8=,tag:lG5wemQQp3PbIZJAyw66bQ==,type:str]
    pgp:
        - created_at: "2026-09-24T09:50:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9AgVmznaOk7AQ//U6Y6FZF41I7o7an2tobskfdvrnnVM/WfseoiB9q5kn5P
            1LrBEYZ6er9U+cmKiHvwyz2+dav7KPWCaW9AkkDSJDin+76eEolVLmkU4FTDn/WV
            GofsUzlpjcev4AnQLzFor1rdKStDUo2LARYkhQbCeVaktJ6rdmnrZsytB2WBeXwB
            ItNZHg3L2NYVIbCVgzmguQzI8xjbsRJFh0nuwN2CPM+RF6PFgDL30h45aXrJrA13
            YWH/Q45N/bpl5bz4IgViTMEn1xjIIaiPU9XQvy4JsBEVLd+peVdB60djbzgTtIfP
            +SfmAn5T93P4aaSZQnnHNJibnIM+eS5mC+DLUWqbmkV3OIA3Abfa/MwUXg9VfDdu
            eExmcIt+SjLZySEMhEXlWkcy2aIeOfS518Q8j8hCfmYdAtQvqgkufWsWhV5Mc9gp
            kwvlREdMcIyQ76BXymRqkVg5KMn506KGwNGy6s713UNyV+ph2EK3aIJ9NIeMgpm8
            ei3LbuzCawAHoFWlDDxBv2kGKAQyuCvdRY/BYbb/eX4OYUFQfDmIQO+3tqPQadBx
            f6MocM46hxKAxpxYNQxXwMJa7BoP971fXu9Bqhdb32Sdq/GsAO3ZoGksXqLSjxdO
            GrmdDEd6qL7BJJIpx3VEpkPnLthR8VIUYSzbuX3XhP6aKtqAncIDrv/F7ZE9tFDU
            aAEJAhAhPBYfvWo3l9GJvIXdlvWfnWfplYkjcksup68KYTpv3b42d3P+61AWuAic
            xMyJa6R5h+ArQbFG619eKDQ9if7OlpfCzYk31M7MZMLGX42Xr1cyUO6bb5cQJUOD
            cqNe6ZTo8tY8
            =vDnS
            -----END PGP MESSAGE-----
          fp: 04DAFCD9470A962A2F272984E5EB0DA32F3372AC
        - created_at: "2026-09-24T09:50:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwSHi8yuDIZWAQ/7BBOBUaRLKAGoM6nVRL6XN3Ih3VoNtwC9N4ZK2zZoOYsc
            0+S8Vcw08VyFsjdsgHBTjf2eV0ybY1N21PknWYUtzYdeR+zXtAXtpOOHmrDjPKNj
            GAmeFJIWIaNHkfy6EZttxPpIyU1ASOVC8hYoU5mMVnSAC36ykqQUAKEZMVEyusUk
            3AV4FL1J08AaDRPyevLobCr0fJEyzRmJowehTBm4O7ufqHVkdZj1JuxpqHpmwdhD
            UPuXe/7lH8YPoogeUBJwyyHCDWl/gWEhNRKOKOEeQR8w+FVkdafPTzozFeq/G43s
            PpranVIGhiy19fDvyEpBIExRwXidVW4cwnYc6Xx7z2Xqg5JncngIf6wKjsOGAAgG
            A0uD1TdsOPMcX0QkHACq3kSRRpClQXSDjAbyTJmnD4bXMPAGUbcSXPAAPjRHfD+I
            NCdYwYuzxD36RbThbkOAmKR/Mj9h4JAtfK6TpLsWIHBD2I4OwjcTiYvkLxT5lkbR
            hPqp2C64Un+xtdhuWzSxp4FGzOlZ1Kc6RUMC+0B7JleZ0WNnRa7IczJYLIE5YbDm
            Yg4wVa83psDLFT33FmEBpAylBifKB0JB6OchvBUPWQVg5gNZnCzwLh5PTlqMXC4Q
            Gwgmcpkz4/+TukR1XfxN8AOlcmZQs1xWzJzg49oeguOqCwDIBIe8K6M+8oNkRPPS
            XgF7x3udarNuqIhOOGbXoWJrkMMyv1z0PqnyOmvsn/52NjmHixhlOJr12uInppoi
            4RVpuYrU/3m5MfStn2amrjiZkuQofSZDEQ0q/hEUQ0aQS7zDtefeLiF7fhYnfDs=
            =Whh/
            -----END PGP MESSAGE-----
          fp: 8A07D816280A983BBC35E85C280DB66A3E8C012E
    version: 3.13.3
