---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openobserve-credentials
  namespace: b4mad-openobserve
spec:
  encryptedData:
    ZO_ROOT_USER_EMAIL: AgCX+DWqT0b9YeqOOoY3EkYaIFNSY7n6my2VEXXHqM5y2ad64OBQ7Ku/aivfmGst/CEQVs2l7Ydwq0tR5h3BP6//6LMd9D5QDDngvxhIFpRPZ1XdkNXSbDG2+d4aPVmNhA8PeP97QhdzAz8njGdPsycmDtWTJo4fCpe5dGUDjXyYepMu4mckp1OhFY3GhCGcRRwO9uNwa5VQW+YMXda/yTMjLr+a7gHwgFIuGANcqW0F08h47kaOAEOsgDdV3l0CgFwJ8WEr6d4hby4ZVYx2Pz1Ff6erhPZuXZ14ljx8fVkd9RE4OCL9xnHIjkEwgMxLOkGl+ZX/Y/fBmdCRK7RsgPMbCGnnR1jqTLBox0/BTapRCiCOU4hNDh17mU5VjDCTepHwSX93H6iwsCyjsK5dYINa2QLoq1AeRF7F/XOXLg66HOkYiLZPBZc4qzSerGsfhPV6p+P1HhcBgyggcJz07/3cuokfEK9dGfQMnL+48OitWekqwlRoEqo7nHUA1M0qwjYHrUx+/7We8H4XVW1sVuMGhJbAXJrX7/73b9exdNv0sbzN22TAexPY3CoG5EPYI3FD7oreFuR1ZjaA8CPRRd5iVYNWtKcYEBj/zJILBj7BCdFhKE+V0eUNEKdOeiAfQuH8pQA2kLiVkuxBjwV4xf+tgtEy8bGZ1CyhvPJhk+HnVzq5DT4+/GS+adLr2oxt0TU+GXOsSHVeFjt22hIwusE=
    ZO_ROOT_USER_PASSWORD: AgCfFYwDGAz1jPF80qQfaeHS5Gn+NU0U1YXGZU4Wx9dwea2kXq7S5yg7d6LDmLj9zLS0vWtCI/aEsBkdzRKNVyVQYrg9XXGuhETzvBxFPrMInaKPP6vDYDbLBoytLOh34GuiMjIbpCWTUJ7TYrbYBNGFGGxXNvDtAS81WMlRWXSVfNlS6QVe25kpI1p0x9Bp7nV4i0Xs/CAvVbEdXKztMQWmJuOXSvu4APrUZ3fu18xyVhu6zgCOTP0D+FT1B0W7w/toPooQ+zaeVEn6TKRHvJO8mqwayXboPtxgixntZZnWgRJmQbEOr5MaDFfDYNYbvkYQkM/yfEgAgEiMJFn7OA+mgkxyEXgCnO9kvJKDygwAMtUkYXLq1jaGy5gnltNo8jL4kOzclGrcniPVSPb4bz+ts48pZvXDxZIkDn3BQISJEs7J6sjAcS/zMQrNKnIJyzQFFV0+gIvbHPTUPMnuDQ4UzX29/RTamp8VUxpEjoV9W14INPO8sSi9UL3L3ArvOPexvheCvQ4m64R49nvUCaVztvQTBDg5uJdBKaMITr5TVYk6kYTO5PCvLrybpCm0LnnFqpzN+5UxxBhd/ntskRWef5s01e/CjfdkvupHjTN7nDQf+OUGyNlgyn1hyPNzHzr5/UC+4380aF7NDc+1cgrHlUbsb/lNI1BCz+UOlumqRVT67e/ZzAjZ2imuwVEqMJTEkXaS35fyxP7QAxSNeCs/jW3MnYGn04qSdiZiG1TBPQ==
  template:
    metadata:
      name: openobserve-credentials
      namespace: b4mad-openobserve
    type: Opaque
