apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openobserve-credentials
  namespace: b4mad-openobserve
spec:
  encryptedData:
    ZO_ROOT_USER_EMAIL: AgDDCzvjN+b9+RVzQd3qAxXtZGJgzGP6QBIMRXgFF0i5sNUHopmr2ZoXraKhs5vcsiqiM5/LfVgzOmAzd0NYZpAPo+W4DGLYuuMC9WPSslVGb/FszzM80lQ9kpc08xqS4NPtevgiXVRXNy5qNTj/0aOlbyucXDzNA/pbjBzbBwKAX4SAeg40ZmbnuoiEP/HMwgqzEj1CJ9u4doXHkocuZij1t4AwBv3NB3oNUL+gVJrdMk8YqZdhiRfqw7n9nSDCAiJD4eT0qwwU9agSkiQbSj5h1TTP0l2QpvSqcP3OgTKa9+h6nkznrjDgQtoewmZg1hoRjDx5XFnlF2X5OnwOR+uoHGoXVdhyGg1edF3bCrbiuzI+KH9r9Qzhr2G/twL7sUDIxYK0hS2wolfUPMPdIkQjYTQqU3GzTTgmJqvf6aLPNIhTEoa+Cto/Najpqx35lGxcbkJasSr7/yssvwUHd85BHC+O1pgYEOilEUGXqpcIYp+Hiim4V8zS/EaTbmsalaQIwxOEfiNfq2qffrlhF5prgI2C3n+9GFaNkE6MGMh9zte7DDGjhRfzbHVxxeIn4HQiqiUTB6HAn7oyzhUzeHPF/XPfZbd0JILH9u5hPVfwaJH50Ghud7MzFnSTxfQFjbfMarUrd7f68GS7uuqzLDR0kLTCXkRDVta6I5i3u32ZnFN3/BFIyzS7LneZH0+muM8+9KtKXbrqMeRqgK4XDmA=
    ZO_ROOT_USER_PASSWORD: AgCtJU7+kFSHNaTSKYOQeDguE+Xi3A5I/eBrqUL1UCsmn+cRfqIvYn4rkLCx7R8ODUZKZA8lh82+5tb7BCt9pwerWcCMe0sB2a6XuMblAROhZKVQ+H4GyvmsLrXZbmca84/YWcZ9zXR5EJ8ABHds58tpVpuA7S3+83goF9MMmxcFb6xUtBnvQvcjdVj+pnLNib5hDBK0IzcPkyKBzKhbG3OEEoqWaMTTlPwIRtc45HLFR9eJKUvQxUb+qnFoWZ4qcq5vr/ljmUPu5OrLABA29+bSceQdOcfffCcCos9VAeIFQGPrCKnBT3koukCFPGBRHbJyLrXa4Vrbaby0qH9Ch4wvoSdyPLisoo5yXK/jkct/q9/AjgaK3MC9TOFa9uSHJ/iDdCmYHPhDhQD3sgiLxVPVslT8AI7Ro5ldiIDEcyjH7dr6d3SrQXZb76BEoMi6+eNhSNI9qkh06X/1sSbw7ei/uBsP/zcoXonXXW2TfIqfeWwk1lT0jZD8ect/KurhZ6mIvbiYLgVJcywlq41nNhWkzOM393ALJXSKzEHXWW+6dZittOcewWrIR+nCZpbCdYcWeWM2DMmGBEqpaUnBeIkQnzCdy6+RN/QcP03EO0vq9c6PBV1ogcWmB1oJd4B120C5DO3BsoUgSXj4X6HB4F5zGsVZqmbMCGt2z97IVqUzekqI7dKsCetq1hqDn+Qo/fVGanc0cq52u1DlMb5CzqvBywdIKKofeh7SZHwR2bBxAg==
  template:
    metadata:
      creationTimestamp: null
      name: openobserve-credentials
      namespace: b4mad-openobserve
    type: Opaque
---
