---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openobserve-credentials
  namespace: b4mad-openobserve
spec:
  encryptedData:
    ZO_ROOT_USER_EMAIL: AgARR9h05+CxyW6AdNAuntlBZ6eKRtN3TnNZ9BQ4fL1QSXVK+Vxk125BARoBLzmDWZCaZd51SxhVfNepaiacwhGvzNYBEfeHglRn7qt5QAj7avBSGBDTRvmPWjzIi46sOvOUnhmbg4zX2ZKqFgAYh5tdH42MQUYOhzzbqjukYR6URs1MxsWVtr2TpVF3tV/bxrs4iPdkk9M4jZwY8d1+L0d0fUgLBU5+Pf96aTpWDz4G1h+e7u0HpQgjKqA/i0w8RTQPAxVe4u+kcElUVs8lW5QaEVeYASFSjnJhr8rqjCHbUtCBxD6UP4uqxPjcTieWQSthdoHixpUNduELZwtqqvharC27Sx97t7GMNYdXBgZNVI+r5y0moTyPfLs/b4f+kheERfE6A3x+mVPuz5wsNZy3t6iTmXPVvr7Xs72ePES8+cFhFOxIiddbVczWvZLIAZzS8OnSWcFaeE9i8B2DycU74N1CPe/BiHXfOO6o+KcRpccvscq2JgxPmm9TDU/aw2G6QuxsV0VgpWf2AIbAJGv4Vt5ncftG5dH8GO6OOwiDKLt3Nbv8bUoC5mN9X/St+hUBYGPYrmPum16I28C4oMRgl/EmwjpkfBClAHRiPdJIObNXaaeDm/4XXMbhlPtvswJjv5z31aFP4AdrmlYRdMu2h8PQSnvY4kz3EjP9yRHAAJOv14ZUqWLmMQfDVNnjTYy9osP9Z8MBUFDh6bNii8k=
    ZO_ROOT_USER_PASSWORD: AgCpIcFI+lfZsB+bD8F+K8M0Q15qRi/ZY/+fOMZXhfELl96CZ3lRzoP8o25phJCqk4nNQN0UOlYzn8+8vtQIBoHfHwIfju2Srq8FNW3UTQ4hMdxYMk1o/LruFPphDlTXvUmgOQql2Vnxr4KzOF/8KUFoj48DT99PrxEK3wPTiVIYoOzi1/ZOpdh8aGLjudxx9YPF8W+LVj0A8NnxNtoVfNo9Ky1nawSiayeU4SlJL4esxSrRY3BqmA13FurdTOL+Wuvcwye/PKQZGZSdrEv546Zjw9AXlXcEZCZJhVpIGVM2KCgkCA/+AVSb5K7FeMif+HA09+Zgkua7721kfS5AsGsMZ6UUVmIl9GcLqFk+xYypdaeeIKQH/6w2QBpVdi67504Ow/aJxbYOHCNuoU/4b/gJIANDvHVMFZpGGhjRo5lf3aDEz6PmwhdVXCB0zoFzXB2UPuA1TLFf2SVCp9OtUg5vfqoZ/HkeehsO/25Xuj13rTxlt9BxDTjcOW870vRcFsA1V0WUy4+HcloiRsmRJiYXdqN/DFc9C4FFgQbfRVhiQC8e5MCktwnKju9gTpxRJBNtyzxXTiqWtqJHpEzJEg/nuAO1YJh+Jrz49RnZgEHiFgFOIodkZK5h5J7hCLcEtK3kFQOTf+Iz7CKrMacbE+OGXyBtf/o+j4cqMhfhHO7IIAGKNp47VZqDCybA71+34tj7OOTaMFZBIYMOiHxOvNVnnnuIMs7QZBzS2iVNiiKbHg==
  template:
    metadata:
      name: openobserve-credentials
      namespace: b4mad-openobserve
    type: Opaque
