apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: op1st-gitops

commonLabels:
  argocd.argoproj.io/managed-by: op1st-gitops

resources:
  - namespace.yaml
  - argocd.yaml
  - argocd-gpg-keys.yaml
  - rbac.yaml
  - redis-fix.yaml
  - resource_quota.yaml
  - network-policies.yaml

  - clusters/
  - projects/
  - repositories/

  - applications/b4mad-epaper-service-tekton-secrets.yaml
  - applications/b4mad-epaper-service.yaml
  - applications/b4mad-keycloak.yaml
  - applications/b4mad-matrix.yaml
  - applications/b4mad-meshtastic-gateway.yaml
  - applications/b4mad-racing.yaml
  - applications/b4mad-radicle.yaml
  - applications/b4mad-renovate.yaml
  - applications/hausmeister.yaml
  - https://codeberg.org/feeldata/manifests/raw/branch/main/applications/dev.yaml
  - https://codeberg.org/feeldata/manifests/raw/branch/main/applications/prod.yaml
  - https://codeberg.org/machdenstaat/oparl-lite-2/raw/branch/main/manifests/environment/stage/argocd-application.yaml
  - https://codeberg.org/machdenstaat/lage/raw/branch/main/manifest/environment/nostromo/argocd-app.yaml
