apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ca-forgejo-write
  namespace: op1st-gitops
spec:
  encryptedData:
    token: AgC9ABTKcMIu3yJRvVVoMKg23xF7d2gqxFtspzsStNlDpdlNM5A8HUTPEzZQ0EDsp5DlpFaqMAG4863s0rEXkrEouTBCpEbjJMS7NBtjEBZwsuswk4YsQblozzgbXDcyRnSVM6rGDLgXiGeag4PeUt6ru8a0cRDNwWOgNZx/oIo6snzhUz18VBcN2NWj87pkpD+SHfGJdkV9sFBTmdecSHh3Wq457Nw9oSf6Tt0zcqrJlvi8TPqaUEvGuI+LneY2NjuFUWQfNzTq+krLykOLfr2qi+w70xqc4aGO2rQdIheT0qAzJGobiFEAqV+xbcIYqS5NJtJjrrg3Q+UNEkiFuZkPKWH3cyNLxaBUl60Z9Ckn21hED3UKrULleWuIiIRJmJpvWY4geLsQL+okofGYpGbZZlpDQo4clUUWT8o6yquPf5Mwv17UXE6/Gt0fSEyIFn6NoQLX9XkVSjqNaKn3EgsXsgbaWQxxOcQvGPfvDrULbDIPiF/EwUEozP8535HdsBEbvI5RL9jckkq/qUvAhp216cJ0MKw7RgaxkbQrWrC8ufuFB1Xd8ed61EU84EmXcV46X5dk3S1hzw2q6SbK/Pp1aQspxz9y3psNeVMltC4QuLdiaW3NrKY+srDLSJkhzjButYJE2llYaIFz6AvH01jERo1CbJTZSOlDoJhEOvPDIixY9PelZ8j5ofEJNUimejf+Ft6iSHCydBzYh4zZC5oSFwJ2dPv/FApb5YiVepvOQ4vlZ3qCCWBn
  template:
    metadata:
      annotations:
        b4mad.net/href: https://codeberg.org/op1st-gitops
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: op1st-pipelines,b4mad-hausmeister,b4mad-machdenstaat-stage,feeldata-dev
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: op1st-pipelines,b4mad-hausmeister,b4mad-machdenstaat-stage,feeldata-dev
      creationTimestamp: null
      name: ca-forgejo-write
      namespace: op1st-gitops
---
