apiVersion: v1
data:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:vXhmew+DJc7km3TAeoL3z0HWbxCYRS+MwdNSve233ohuguL2YXpTJ5wUtYRKRY+N0m/Qw0PyFy1uGi0BHokMQBcgRy6AyM1hGBxRRxlupq+YuQtzougOkZQz3scgR7ml6YTHXkmiFXw8ocaGtcNQBIO2GQVx8tsFDeCkb4FuMhzgfH3TKQRh8aO7+3uboSMV,iv:ggt/Q8dBMSAOZu+jKZGxs5B30keCejHVQO7cKPpy79s=,tag:8couqLCfrgoTinA7xaq/dQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: ca-pipeline-agent
    annotations:
        b4mad.net/href: https://codeberg.org/op1st-gitops
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: op1st-pipelines,b4mad-hausmeister,b4mad-machdenstaat-stage,feeldata-dev
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: op1st-pipelines,b4mad-hausmeister,b4mad-machdenstaat-stage,feeldata-dev
sops:
    lastmodified: "2026-06-03T07:19:44Z"
    mac: ENC[AES256_GCM,data:/vyHr0llokhBCakvTykiu1nCXuGDpwCaEGRunP8Prb/I61O2PMjNeHS9U9cOZYhNmu2gWm2xWp8xXrO7VpNw2nH1PGiLSKgL84vBU2VStJcae5UAtThfLVVp7ghE0Gr7wN0cePy77FzGlTuhxNutMS5DrVA95ajh9XWPussX+d4=,iv:lEJdXzmPoUOV/pZ4pkmDVhydJ55X/WqhjDkN63X1PZI=,tag:l50OHLt2FiBPobpWgcmLaw==,type:str]
    pgp:
        - created_at: "2026-06-03T07:16:03Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9AgVmznaOk7AQ//YdjT0+wWiBjl4g4eMTdWwmesny3+v30z53HMYg7KDmkE
            QBGCdAbezX1y2jEfBBd5CDBvzP5G8t4ZoLAplkzAmp+u0mhS0YtvsVabpry1r99i
            cAZgrIDPu6MW9Lky66sNcF7GePE7dcyTWwVv5cuT4lwa0ATTvIApPLdjQiy3KlHp
            +St/2nLvC8qNKyRGK4r8xPHWk90DfOQZiy7f8T8hwWIn9geofqm7gk0zSkBunjUG
            jO9D4+hgbEaDBVxGIAjiv//HiX+l/v2gn2GT26SweMqT2ng+/NCGLCmbwJmwthwl
            th+wji8IXnb4B8EepiiiJ/BfZWRg2A6G+bJhkMzBy7LCFSsmkyqSTR5YRHefEJXZ
            YzY/ZJoDY4H2V0GegMXmy0iukBieTwLFAUFujoxamlJ1idTjYoCp7HogX/ObSFAI
            MYAjCE1Ykjm+G/om/pYE9DeOVQ1yXax9Z1tmnK3gGx3PyuutdX3WMxmZ3Bg4JRH/
            3jykjAgUNZDIsxkwTuJqMgLmRENoSv8VoRfKnvHLZ+vBaFqSqTdBXOHHdykcppvK
            C2Ycj8ERTyOcA5oP5IncXnuwvzssrA7yjX0yZHZ8qcLWiO/CT/wUIy5hEI7pijPp
            8CbiFGCRKgvSah6r0vJKFvgCFhQKPOTeaDotcTOSptFXqh3J1/kZkHuc4lLg4F7S
            XgFOex6xEHYyKkZMNOc7czcXsnqP6EzSPaqtkz7FTZWl/iIhLHWxl9Q+7APF0l82
            Xsw3tN/0UlcbpJJwJlHpK36q5+KgpjfEoiGzp4CdrcL2igEbF71mtARmnLxD5B4=
            =iVFd
            -----END PGP MESSAGE-----
          fp: 04DAFCD9470A962A2F272984E5EB0DA32F3372AC
        - created_at: "2026-06-03T07:16:03Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwSHi8yuDIZWAQ/+P8Au82NP6YWjN9nyvvsNFUNhYXyCjvzet4F/J9B8xf4e
            CyNqhsSI0y3Ux+z3CDCn+13eXpmJGKaphK5rTRkJlSuKYkqHyof9NWeEMrOkNOGo
            53qSbXC23HFs4sYsbh4SR5AiqFlRHuOP4k2xgMA5D+xVP98lSrWkVWb1qnCx6keg
            9jaDL/NxHveEv5URX80r2znA6aZFhp9xm2ID4KCwdIm2DYc9OsBklUovKn4kv78z
            gr+7mlt7uokhzJfoF5ryAW9a4wSZqO9/gb9U5wya0WtPeCZrdzr/U9r1LgsOC57J
            QWaYYAXg0MLDe8oRbYcbIndTA4S+Ho8C5hC2GkWrU8yidkIbkb9NNChFcVeThZ3M
            wOkhAksoq0Z84zxB4+lqjFuEIN7LShupKVy7FAgf5ew9OlkQPUf2qQBp/oxSBwid
            JVc+b4XBPr2WB0S7VDhlutxy8TecUvgsZDy3swBdTT8H07QjdIMixCE4KuwDKnHE
            2te6CqGY5hL7ngUWpzqZ0RrpmjVdsch74r8e0wJmdjK8raWUK+pBRBCAGJMQkGKB
            NECUDhdPRPYi8v/S3hkNJtukztAuyGssw3geIQYMpQ3HuUK/iaUmXLkIlO1rJCma
            Bw5BuVNF7fVHnODJHoQSNs9HO8uxMKeRmyWl9lEUJLBACvdw3xND8oNS9pOQycfS
            XgFlr2mxbGSmSw/e4bYMOqhvywfG3WyEhUpfW254IePsXafVEq8JtY0mFYMvp6w/
            LLNmqQuqSr1rLajm/sV6ePL4r2K3QYYZ9EaVKC5bXW9Od9mzl/M0rLr6KUYdlz8=
            =5wN+
            -----END PGP MESSAGE-----
          fp: 8A07D816280A983BBC35E85C280DB66A3E8C012E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.12.1
