apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: codeberg-pac-token
  namespace: op1st-gitops
spec:
  encryptedData:
    provider.token: AgAVTeXQ1dCKUkXdjOMgAatQHPLteM2eDMaVZ5ggGhJK/IDOUdjlot3sYYUWY2uXbLV4CobeVx27ortmaTA5MUNcGfKugSPnqWpf2HT4dOe8afkdKWARA2AJTXWOg/JIDM3BgeOX28Yu94jWdWgyxtBrJN6E/SW0UUN+MvwkK3CDa1H8tQ0DRWkLVG4NwKUgy5VxBtQ39T9p566udGXvlql41WDPq/TEYb/UsppO6SB/l1ghdbtABwbWXgXgS2oEhr7iTxEq3ue806eIJz5FxwOeLojZzAXiddKtu6U3ZsxAjTgtyiPWrSsm9b+pskqOh8D3ZSJKil/Zyh7dyprjun5UepgNXrvxkyjbTtKkfrK65/uXnMx4hZGbDl+e31FSjrh9UdM0H1MjRlJ1/2WEe3x+k1vkGrtvRsu9PU3ur6CXef4Bgc5zMBczfhbOCJwKxsc8OwaD2RF5nR1i8G+33AlcdZzvGZazU+K5T1M7tkJkGcwEpUrkHeVn7Yxu1CuJ31pBeYlssaPOH61SnGgvlu0hLese/+u2U0hGSr46PkU3HfdsX4HPU+Dqkp98+Xr2ZvRX1LVxMQXVOf/Z+B6dPlEGljhYuGnUSealxujDmJaYztmWrVg4uORb/qwGAdwX4rNCvld9ii62CIYYAjr1jPReYqTBeFlYPZ1ukbvPgRZTzPT6FYZDNZ2vp+LOmjQ8wk34Qsek80T/HCTFrG7/MpHC4Db7+pjmPeSLPMnqfj223LnWTo1KRfZw
    webhook.secret: AgCRG7O14mIw1tqLovoJuA1QsqCaCYshrDayoANAoHtyIRkdIh1qpeb4v8lLLNfRF+TGxkgEh69/xVq3dnP1oNUNQ0sGTYkx+mEyHA8JqC8acNeUNR0LJTdQAGHC0myGZ5V+kvNAQqlXV40ABq8Ho1iaeZJ9qtCiBbny6O5nkK5WPz8ojmL5HmSeOSKpIQ0VNqOytGNyMWXoUGckM1UxLEly9CrTwzMsLFyTcnu8pPCEA0tSBQccIpxFy1S7L5wCjRIGHcdg496UXw2saZ+U+NNllPLmEQVFZ7AzubqFjS5xJiX8yRvII+itDsfDru/pZyOncWTC20tw4OCpzfp5DX2h2YbUaPyj2rzh2HaoEC5AWV+9oTRQJ093+JWv8YpOPXuQT87SY4r8XwMAHHdXBq32NzLEl/rSLucdgoR0ivlZqzr/D39cfW6VBL+hCXh1QLAluoRmp8paMdd3d7tUoR4GEgN9Sya/qYPmX/HLEBFxKVRiqRdcy76q5jkx1QcULjo/bh2zdVWd/Lw+z8qWKzbFSeRSU9uALQ9fP/7TjMHXNtJKe9gzX8BJi2HzwsJ+IJqKEVQEARt1F4cDGq77aG7ZZ6EWMghQeLKQKCdtVgdsIM73m40EQHU5sS4e/mj9HzlIqZ4wQ3MzT0YVYgpV9HjSQgKh2VjqlHL/+QfJcQj1cwcnFmmWv4X8XdJv+wcaODgqeAhN1KqHGlpohge0CVOT0C1J4cF+EW9og4FyfLRHSC1fJidQk2vD5UvuQ8wrMXSQb4/DqOsW4xoxwbENIUO1
  template:
    metadata:
      annotations:
        "b4mad.net/href": "https://codeberg.org/op1st-gitops"
        "reflector.v1.k8s.emberstack.com/reflection-allowed": "true"
        "reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces": "op1st-pipelines,b4mad-hausmeister,b4mad-machdenstaat-stage,feeldata-dev"
        "reflector.v1.k8s.emberstack.com/reflection-auto-enabled": "true"
        "reflector.v1.k8s.emberstack.com/reflection-auto-namespaces": "op1st-pipelines,b4mad-hausmeister,b4mad-machdenstaat-stage,feeldata-dev"
      creationTimestamp: null
      name: codeberg-pac-token
      namespace: op1st-gitops
    type: Opaque
