apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: codeberg-pusher
  namespace: op1st-pipelines
spec:
  encryptedData:
    .dockerconfigjson: AgCOqF9eCwcm09EE90G2zTwBZqxoycpoHxCrKtAhTrFvwFwsxbY26EIKic4uh56T/ME6CRmKySVADfpIiYFZoOBkAVdAjgKatRX9fi0YS+pVOXdZUBov0KYoWWwXrCQSamo/TMJ8ocJxH5DO3znQI6NmbAZSedREdK5SLfY6jf3epAmyc/0ngZNjJRoZ1n+c6KHq4VoN9+TQSgRPJfhtXgxafXmJz7sTkl6ZuhSfz9s0Eig8CtCxgLqN5zcwx2teRCdTbd7XC7X8lxL8p1acq/HodpBs0pPbjYPcnoq2HueZ6lM/Twhp5xTAKORRjU/xrBf79QtPXWMmk59Ep/HKCRIZgoZKtPB7LPvmq3jsFE4hOadBybmEglj8AoRKfKh92gksef2waVwiF8fyLj5t7+ym77ivIf5L56sqM9VAvGczCwLOhcpQoCXT9gcOB65QnYc4lT64/aI2lo54iBsW7Gnr1JpcoPHzFJ/VEy4oVbAMkiZXoCtRDwZCpXrlBK1igbT38Y1HYkchTh3ZxCYE1yUIbBwafeH04GZkqKe1xOdrs8FKxA0y3PCmcwSFiG6ceNaE6Z3SiNx0+RNkYjXcQPy1fo77vgM39I1+5zPjXEeYshgXCFyItuTPLLbbngDeKnaGWla6fbYHqGFbTrQkwflrRbDSTQiI9OO+avIzUWqWLMY648RuRsOrVMU9xZnC74cc9jmILFCqR6FwjVVO8ZB3cxufCmT4ioQ/r3/SUf4c7tzMDxGCWsd0PHuOTh5PuVmiIAayxWHBFF5VvqIV+DZ1f8XX6bPXUystOXWTq/mhDylNwZSRbogSAZTZpwNI8VJdpjX1BNn84EhSvIkXcDbUW0wiPfYEhai1x9QRBn06XF+MbUFcfbfJOlQ7p4KaPdXOv6ZoiYVOfNytBY3F48cqjwwdN4Y1QpLGkdyKjOQqsjPjEsP3aobFnS3LTSyq3nQF3SKgglfVuAyrKxgSng3LqKAF19qdi01Lvx87XgFspQFVuep824Ljw26QJxlnxW1f+HOG8i0RtsC4pBepOhIFchzmpcP2nj4ZBw7YLlotl0OKWRsaYYNnp5hx5TqEM0wg02pbq+lN3bM=
  template:
    metadata:
      annotations:
        tekton.dev/docker-0: https://codeberg.org
      creationTimestamp: null
      name: codeberg-pusher
      namespace: op1st-pipelines
    type: kubernetes.io/dockerconfigjson
---
