apiVersion: v1
kind: Secret
metadata:
    name: cosign-signing-key
    namespace: op1st-gitops
    annotations:
        b4mad.net/href: https://codeberg.org/op1st-gitops
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: op1st-pipelines
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: op1st-pipelines
type: Opaque
stringData:
    cosign.key: ENC[AES256_GCM,data:MTcna8oq3guJIo0g/tvrOebfv7soJkS17HpA7I5B0ngCtTxPLikJWj7AGDmhLXevfnjzcfPviY8hY0BXASBTY7Sg7c59IlM8BPpyeg9/h1nDGsV9rvZkMQttX94RfaISTdHzmlHv7n7r5rRy8vJrnWifTQDTSpVRVrm5FC2MZGMNiL3vP6/lDLIPwphupFJ+LkcoBhuuqiJOM5nu7qqqmKkM3aJYSXEAtDH6ERMgqjwrf6lwqNOOqJu4B1HCGxpwZRhIyj7Q7+aNyhT7QcvCmVx0rJzZcJTZJ/pqPDxmIFTZQKV1dF5FiSsU1npJOtFOmIZYMuykJcs3TID+QuI0NWcHtIc8Wss9Hx9may0JMLktzeEGne5rUAsxtBMKDRL0453OgJraeZN2S5VD5QiF0m89MFUwb9G+kPif9Yx+SEFRnpmzmCtsLxMQND1vVJiohn7hYiwLvkjW4oYdbLTZz0uVNEYonmH3RFuEKCeOBaPL6zvKnYYFE+MuGPe5wioViuE7Go2bG+dolAfpQVs7c+mozzjx+BD4moFOpfsd0tKIwL/JTqfF1JJKwxspTStRALM8m1SXaPM22jd6yq3xywdjYxhfDVZfICyBSf8uSr+ZkhUgZLYVd22jPkhXeEX1Wj+4l+3r9TJlIF1MHs5V7tQ7BIdi7LDiGB0bGMoLrdmy/1WTiMRZlLuVAtJBvvxRlqSFyDYlXRJoI5hyqb+FjBOn/old9zXf01HI8dE/TKIZJMGvmslB8jAVZEKLcRajZObS+5sstYZBx7QeUYDFUb0s/5aJdijPfp7FdSKASV65J1q6+an1jtvKv9YAtUWzuyTpoqfB7mc1SP8Jw/qvSV/uumonnrkgzMJ+iA==,iv:TT0TcgWbhnZA5/Z7TATZj4kl8TWnokc3fdvYlABZLAU=,tag:FiHf4MezoyumhV9WChZzYA==,type:str]
    cosign.password: ""
    cosign.pub: ENC[AES256_GCM,data:66qNr3/MZb+csDrSW7p3K2c/YVQdkJymt0g3XIjxOTTcotBHK/xHNTyK9vN7rBCqx9YTjGDrvg3PErZjZNQRC3CM/iPhtN9c7NBazes6PIC3h3L3fn5vuiFoI15aGiTOU6nBRNrqB2DWjpfVZB2pBLLZwdokCQNJlkPqMhwLmjLLdxlDAYc5F1t40c5YwfXXE64UxHp7KTa+DmPU0drGiJv/aQ+OnamJ+ACUR/EqNAPh,iv:Q3xSZzXgQNZ9JcUSlz/NWdBom7CzwxcmGPAvimDP/ds=,tag:s30rBnZHWeT1ytdRK51rVQ==,type:str]
sops:
    lastmodified: "2026-05-25T11:06:24Z"
    mac: ENC[AES256_GCM,data:bH/7q/OALNVmKmXXar+EVMQ5tuNOK8tK81LK0oO597ptqMqM/BuKCALSq4FhL0BsFDoInZSY7cbCzITtoTvvQjT16SsBfn3vLKl5e5oLeyKZd+eSRiCXxCfrov+/KiPwLog+bgSXVw+lUkn5epm3eaGz7BEPEd7qgQOhNeQgecU=,iv:MPVsBzeBnU78CDgeQAOS9WEhTZgtvUkW1xLnLcHvBB8=,tag:tY8SUJyaF4hnxdZb+8ChXA==,type:str]
    pgp:
        - created_at: "2026-05-25T11:06:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9AgVmznaOk7AQ//esLSu1vis3YUtzTdKAWK2LvL4OqN3oYpATVp99O+GrlQ
            YBoLQTm1d/JLvgWWB8ZknH7XHGkH/Zn0LlYAv2GLuosh5vlUdfyvGygFW/kAAT/H
            DsWamDhw7Tj5kd3UzoDcnSvb027kfVaYJqkVRVPfdz5smXHZa5BHxlT+wSTymjLW
            ryID7BVks5ifHCqpOMzyhhdE0ZeLkGjusKDcfLZOsYEMIErzgcyfcVuVfqxuQW7a
            GociltDdH+uzjBnQOwJ6UCV496f05cw5L93hJQOoEmk3m2c/wUmoGxBPth9HrTK5
            CTq6m4zmD6xcetU2v0Qvx2uRiNC3Vr5WIuU5RZHx7qRWPXV901GX2AEG5IgtcCdX
            lKVxBgmC1KH55J3sxm4yCC3/2VUCQVNuoX7dhv+SSnbJDrKgM7UoF6itncSgR+eV
            8ra8AeFmK3XiNlLbH1cWzRDMc6029UJH/YBRCQ3RHq52pkxcfGFAmGv9GXJ86gek
            RX7+GBur0/uSBHdnqkWyH5dm35cvqVxE+VhwnEZkOhgFKozewS/VmlO0cjFaK7PF
            i0vzDCqjVn8VvId30PhPLHFatNOlM2e81hIjvTa86cMHFgnFVNQAkWuYPwteNV4b
            fAjEY1cWZDt5i8q2wIUWIYDx4oSJHXOtExRl+BumPW46ESAZyVzXFfgDIwMK4kXS
            XgE0ZcomVgVRBsLAIjexoJafD9t88df7mTZQq4VESCr+C5zio223G3beGDO7GyMv
            GeSiGyTE/YQ6Miecd+mquKx7Y44QRoPugJzqqT0TIvM29F0U2NOguyaIQnFXwqk=
            =YRDp
            -----END PGP MESSAGE-----
          fp: 04DAFCD9470A962A2F272984E5EB0DA32F3372AC
        - created_at: "2026-05-25T11:06:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwSHi8yuDIZWAQ//SBi0/y4EukP8KKjBksMn/uU6FhhID2l5wouUOZI2kL7f
            Jf+foE8QCHbObn1fpV7f/tTiLckQVEAuwNiKiEJao+TsR/6IKzMBvS+ClKgIMFlY
            6toeWVUy8dEHKjoHB2gx2BFDcvhHVH+YfinVtIhppIi3aRO7j6kRGO/UXwCBUcK+
            gX5xpOFo/u5npemCr4vxyW8xH1RLi6RIJCAvvb8M7p62jNiD6W0Z8E9JTWxW7onA
            9Ie47m7dgDsdto/SMoNDdub4mUM7wABavfoX0Z7Wf7PIjoWbE4EtIP6tmw3WgbM5
            J+L52vP65KVOtaxMGAFDv4fZJLM6PIGz4Ntj3mbT0UTlDLYszUT7D3Sh3D8Yt6jH
            1EgoFsRjWkIFSzrPTFYuGF568ZLykKx0/qRX4zGAY+trbvNTvqR7zPrnLNW92mkZ
            Tjcqf3IsIr1wbyBMFTAe7ziq/Itc+r8DUemSt2lQk3+y0EA15AH1Gtl8ZMo0nj4w
            tXSpe5uRBdB88IcDOxVHDYSMj9fys24iwjw9dJq2gWJ6MK3DLJ3SG5sHZbucfMoB
            LOjV1pHSUai1u95zMwuC3ScDEmil2DtVK+91qRIDsEp5aVRibdh/7HznvyIPmNo9
            HbByrssAKO1sIIhveT91bPUcCAy5YQD9v1WfygY5ltW/DxncbYKtBZosyqBfzJPS
            XgGVjxPUBpE5HLmiD5U9OWwYV7tolCFU+JvNriKkYac4j3KKNLswNBHkoi3EudM3
            JEmQcMcIwltFE9KfkEOBEjYi66g0dXGwHHfYfW5My9OCjPS074D+X/6FUuLI6Cw=
            =+kHQ
            -----END PGP MESSAGE-----
          fp: 8A07D816280A983BBC35E85C280DB66A3E8C012E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.12.1
