apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-pusher
  namespace: op1st-gitops
spec:
  encryptedData:
    .dockerconfigjson: AgA9BQp2FFW2DzwQnf7HYNsjuDGsivE5a59okIbyMEOjPeW0kTShg22WRjvVVdlS4zCjixUssoMRtaq0ZPbGgGi7YiSaa4PWzSW9+CDUnFO1SnIlnTbBTJKtlmgyYdwoolfW5HpudqZprVwEaTtc+hYx5dpsRlabd3dn7boeckqqyd7T5taKp0t2X3He4HVMOzqrMtVOpJ0SyDwK+guicbL1NUaQaF+h9IycMi9aPGCFaK+4tUcj+14D5IMc/HzXN9lE5y4hGFheSRgj9NjBIpMJlpBRPN/iPvEMTnzRLtKWrZ09S9WMuyAyD++oPutc7uk/hIUl/z/mUqO0yyPWuC5uFJ4vOIgzMnD/dV57w6elGf4cfl8yQ4PJ531wo7P90tFIz6fP0hK1WAEF28NJNj+ChjZY3D/Jt653hMiqFLl50b3Ew6wxcJy1gNa8UllaNRz1OcIx/LZNGuibaUg4NZeJ98iot/yodoTK9D7nVHViE9XXWjoDXJ/O/IswKsy3nNe9FTxIa+iOhesj2PyNd6kYQVRJgHwdjzvGrk1UsIdYEtvP3Bb691bTuhCj25Agz741utE6fbBXvTjfEbmb5eWxEqLE52mugSwqejqI3jRZZDCfYNS5yU9hWFB3vVbOcllfgLoDzUe+2HJ4NGNgDclPLRuj/LDn/9/YA1UJsYlCHXpglDfdz+heNhW+G9UPA1Iy2kvS+lllDCBfJWlUoLoe3Ls4Nb/WL7NydfOM3OGL8si24esRAAis5VbPcIPwGM7Lfc/SwTq+eFC582znzPxmYWLxldIrW9+DcBjfmEyOMQfyYHkedG7nncJ5XMVwZNp13XrO53IYL7bsksTsx1uyg7EetLfktyyTITi80IyBhT/ucsXPJLYCI5uNg5Mo0OlYl/viJQc85osHYEmYPTkwk8WbCOJhZIkbMlQ9G2kND54KIymWehRFbGRsdIZwsfwaIUudBPLLjoNNCOeKtbNUgaDkqZ702ZbAsmJBErd8q5iSNVEWo5UQi1SNmRyY
  template:
    metadata:
      annotations:
        b4mad.net/href: https://git.b4mad.industries/b4mad-release-bot
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: op1st-pipelines,b4mad-forgejo
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: op1st-pipelines,b4mad-forgejo
        tekton.dev/docker-0: https://git.b4mad.industries
        tekton.dev/docker-1: https://forgejo.b4mad.net
      creationTimestamp: null
      name: forgejo-pusher
      namespace: op1st-gitops
    type: kubernetes.io/dockerconfigjson
---
