apiVersion: v1
kind: Secret
metadata:
    name: forgejo-pac-token
    namespace: op1st-gitops
    annotations:
        b4mad.net/href: https://forgejo.b4mad.net/b4mad-gitops
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: op1st-pipelines
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: op1st-pipelines
type: Opaque
stringData:
    provider.token: ENC[AES256_GCM,data:C2fI2N1lnx1UjIUKipyPJcEK6YjhgW5qy+XQD5l7NkWq+LirAyRCFA==,iv:i3dZ0n8en0utewj88nsUlohXlxRUJli+ghzB28oyJEo=,tag:YJ76Zyn1biPskv6LegxJvA==,type:str]
    webhook.secret: ENC[AES256_GCM,data:5s5TSSO4DKzCig6Jsc+roL37/iLP8adwdXX2M3nY8kVhK+xDqYtCOw==,iv:pQkCffe/jTW4gWYKJejCzJuYVapfrzekSb9twcf4a94=,tag:CYisXUo6wJRsFdlnVAx+QQ==,type:str]
sops:
    lastmodified: "2026-07-30T11:19:20Z"
    mac: ENC[AES256_GCM,data:s6TK4TETW3VaDVmQvIbauTL0Ub2RFCJXqw7B/wYLwMoUSDGn2rVTC8DiPY2sgvzoYirP6QZjq3hf9CflRRHHVeewdyoO5p1RdBjbme8txusp5oGKkt4tLrD0JpW3iKE7r4sW1+IauIKTH//S4TXprLV0/p8iKmN3RV61F98U7mM=,iv:iTbr4hpAM2i7yxkHCaHMSlTADC9C2N8Od8yC/19jlck=,tag:BD/Zhzqzg2wplWq0aURDgQ==,type:str]
    pgp:
        - created_at: "2026-07-30T11:19:20Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9AgVmznaOk7AQ//bl0oE5L2PQn6ezo14PLx2S5cMEbDKhqsd0sT8g6NlVtl
            nT4Di9T58O4Ol161x62gMqg1xfpesWsQeeJhIuG35MxMAZgDDTxR59wNYSyvoCq1
            wouYeT9nuvBV0eNGluYQgve2vHgBQLolD/5sHI9AXWZesyFPAz6RHuH8bvWfMNoa
            IhF9FAIkcZrysC7sUeACS8+qHgn7AL2UcywEXGQ45ZJ1xr7/zPBBJObUvrNJfJOG
            0Qm1onrMuXrqbLsGCWbqmIj1XplOqUsV40is16McaFCf0QuW/UhwNjSAPhkttc8e
            gs7jfyk3e3hXk6nXnemqitfL5W11SGzMIuGxgDB8c5uKTmC/xSgPJ76f8Yi+fFfO
            uGDmdiM5M/OWaaOubuuHrD/JpgBw29F4keis/ZsMPQ8lVWo7xyM2hS3RTvMDNKtL
            Ud5PhVWXSpWAj0C1Sb9Eq3+KZHRJ/s7n7ReoiHYzgNkIVnvUu/emTBqXnkKZkUpi
            L/FJVK9sxOMpLWKr+lABkiNJKqdmuArKn4aXx8g+w9ePOTvkrVBXuiS6YJM6AfWh
            DHQFaLQ2mf394pJmokCCsb5UlDxY1t9lb1D2HFcvHH+6zxVjIgjvEuOJxZifEADk
            nGWww7PTdu4+jeAvBRsOvDeLPwq1XefY0CJn4ZVhKMNQzy7lviMfKxy1DBNk+kTS
            XgEBApn4+CWRHDqXwFtrS6lBIuRawAPj/QXP7BfXnRlXNaWqqKgEBihZrBJdT/7F
            LpjpFTJj/9yyKtipZEiPVhitWc3tzGtc3PHo48SlFzGQrtEmZDoS9xF/jhk84ic=
            =xXVT
            -----END PGP MESSAGE-----
          fp: 04DAFCD9470A962A2F272984E5EB0DA32F3372AC
        - created_at: "2026-07-30T11:19:20Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwSHi8yuDIZWAQ/7BUFYo/i4GSxgKHM7gy+UIxAzBtfImXJlThf1SZujONAF
            sHLBgE5OWz/i2kawgsz1KbIjUyd8pDcsqmu5C8Jfc7UK1hmO3kR4HTgbwA2WuiYm
            Z7BoEZJP6AasqwL1bM6htJaZklZixLAP3B6lCFrVyz//OclPgIz4Y9/nXaOLn/nG
            Cwx2memCVD0Mw28reHa7y8zo6W4FZM8UHG4JGnppzqEIgbvifJWmLF6xVMTSS4rD
            b8UwppWG/cz+iEfM/yDyv1JlaDZLHqCRbI1axLMH3SVuER1BswT4ZgBfk0VTCnAw
            zdor5QfFZSqXqa3if6lwnsmiV0zlyAa/y7PP4WAQoFapR+ny3RUi3qdm4N4+6om7
            oCqzN2tww/UPFRk3KjlxDLoHtMFTUAMmNcSI/ciUVcg535y4ZnfVQlGwQF8KBZ1I
            SdUeLT3MZOV33Pj/fiisQvyptUFpqE9kd7R/BBjXPajDOfWOQfngK0qKcewbXoM2
            lQnvq4cjbEwNM2YuKxMJn7wJ0chnnf3Kn1a05eBprVZb8x58hQtc104O7cWFgjsY
            vRMAA2axQS1F1RwXePUXlSagoECSp5rPAnxFqWrszsi+/zSSdw+3P6/+8u2bXevV
            nQ4tRKcIHLhLaiQ6pWwPJqkmRbjSzHFVaA+Sfu3Wg6fvDpVLtNttRaUEHE7nu5LS
            XgGtuev8DQuZFaNlyixqmpJMk6wDCo8IOP4Ja05cH7MPF89Ku1yHlNUAe1droV3Q
            GO166lup6S65wfOgh1PcPiZE64nmKjFr40Tax2LL/h6oYrEQXW/LSWhhBkQVa84=
            =55lH
            -----END PGP MESSAGE-----
          fp: 8A07D816280A983BBC35E85C280DB66A3E8C012E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.12.1
