apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-pac-token
  namespace: op1st-gitops
spec:
  encryptedData:
    provider.token: AgAOFZCzIqrqkHuTDPKNuFMDKt+wvcIPAoM9ET0QZ7UfocqOtfMI7yZk0cbrun43YgJZDcG3y4glX3huJVYDnguPH711hu96zjl7khuTCc1V74Nuk04lUNy43gBDSIJ//MkYmOu1O84pvLwa/GrJx8JrDENyaqnGw1j8PJ8mlLobHbqoLaNHylYhN7dVCpQZWITENQyJYMAJSlXLYrfR64/PAy3xi2StWheYtZQjNq3CmnDSFJ52EhMIMYmncY/QubN4R4yUKSlDm5TJFRh9W+DDbY3nLGcbQybNpUHNV7N2wsuuKOdPIJ7CLJIlMOSU0CUZ1x1izVf2fND/YJOKhbxLotVBQVlFsBkO4G7Kd37s0bZd8VEAzVehnQkFv2nbmjMqgH6Nj2xf5XzfWtIBlRQDRY4lGLsripTxgTpPAVZIUmfubTeKoZQ49eEOP3TMU72kYiza1y54MQQ1/BWmZHdl8japsH7OfsFdAJ5qDAXRHltDT9JVwrTLu5YZ51BuOVgl6o2FowCPNhkXjP123CEyX+76NArvq+vbQks5gJkNOPOfPqyBuXQJJHU4KdoKDp/ya7+FmvcEVGlzKmW5EYWS8m1Qz3t9/ZWzePqV+KMzPTfC9xo23ikmNLA4XA9ZNB5xC7LWJ2o5O33kBTTOaD76ZAWpN8XZGfzDEYFWnyfEGjp8w1EZYJJpwLJ/OtXiaPvgbEfyBzq9F0jPv0U3RvL0N80T6ysfZPsMow0mkMK/eIO1KvSW7nJG
    webhook.secret: AgADNktU2OxTuQVWDmxC3SHoKt+ZDLBISE5zKN9SLkoXJnCrbneKLy8T+aZfmZLw7Zmfnygfq0Kr7LcVIDC2vXCKD6XHMXE4d9le/WYYj/xpi0iVjGHaLv4JSKV7nMT8Fh5JJitD4r3SuH8y9yD7nMy07psTfKIK8xXYnxR0+w/X25OOn0vzCiCe9i5cx+6mrV2jUsdy36eZuF5DNGxxvKqSlgL6IHBbCoc6eJXAIfRm5gfFTud6aO0b7UFR0OOKwdOcK4TOPRxEwIL1/kvWOkQ2k3Q4R8Ss9XhWvsCGN1k9UITPvRaedgiQhCzrrbYwBXwtXBhm5HN8lqj5gXODd7Qp7pMNBMakI/MW8Rij7soabalcE7eDPLR7vpOtJXquoa47gqkrWQqT/xv22ft8v7/Xij2Q5z08EaD3u+gTGCyV3/zKrHc0/g07soWWA6o1GpETvarljcNqPSL7Y5Rt3CyR5jzgnKy8/2MpTqjdxUihMwOz8iGFceMlMNG6sTtdtnFuC1RtIs/bTIsam3OFOJE1vjq0xFdzuv5pauXel4HYvumlpfO0dldb+IV8lQwJh5BCa0TXygv77QtoEPaS3uxmXoorpwE3UnkY8Lpywd0tuILKWuh3Kx8Mn+r0icinue7ap6UF0czyCUr32IVEym7fialSFxNhiJPsD5ma/v+jg2YAb35PqL+UU1yFjmBOMxoYczv2EptTzB3Zhe+m15Zu7v4RictI4A7iyI5e3fHYvYGTomJrlSNn
  template:
    metadata:
      annotations:
        "b4mad.net/href": "https://forgejo.b4mad.net/b4mad-gitops"
        "reflector.v1.k8s.emberstack.com/reflection-allowed": "true"
        "reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces": "op1st-pipelines"
        "reflector.v1.k8s.emberstack.com/reflection-auto-enabled": "true"
        "reflector.v1.k8s.emberstack.com/reflection-auto-namespaces": "op1st-pipelines"
      creationTimestamp: null
      name: forgejo-pac-token
      namespace: op1st-gitops
    type: Opaque
