apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-pusher
  namespace: op1st-gitops
spec:
  encryptedData:
    .dockerconfigjson: AgCfDLYLUdahArfoVjZPaSbz8MtNGoYCm1HYoVdQFdW8LV8H1VOJHG97/2obyhhAn/ldiw9pOMld32yiQ7wD/Kg41T3eOUIMIJ9VjPO99ScXegFFks4hTWSbxSSZe//nz3qbcb1GhaZ2/MEx3eTDYf6kfyeAGfjrehHBX+2y1fCCp9Kum4FXvaJ6XfVKceALXMghwO4hb3ZH1amKWWOQ/2PKCetUtdtnBY928uQMZ6agJB3RXV7fJCSwRlYmMaq97nWuFEzGiXnrz/sPUg0qoeKlX3UWElDg3TWL70uWV2oV1c8J2INpECIPasd82XftGJfbUBII/64grbktNuqx7bzBQTjP1PrfYMy1yCI45kEcJ6XCfcYOPtDPLiYIXiDFETu2NEbbJ0aLB9D06j1zNI28WeAi8qglhSZ6/mffj2vW4Gch9M0t6uBlduaTitU778y7zNujdtHHv2ITgNhNneYq28Q15zJ16Hi9mQ+SHHNXU4Vw5si42JfDBBa6P5B7QwjDxInw13sMzniGPPu/HOBLtCkf4w0ro69TteKfrVClgLVcKmSzs8NDjM40APyT6AqGQsbVzAjVXx6GvOOAQVO9yLk35xYYkw8w02OOAbuEBhmsER1M5kWoS4tC5xaIycjQ215YZ/OlsCvfJ869Cz2mns/1+IbbzfcW5LfwuASd/l3ryIC6H/DCo5uk44JaqG1PCQeMN78yfWewL/5AtU52VnUAKsuKsBSZt9pYNXVHKNJ/2VqonUzybQmy6NkB9/rQ0s1vP6V43W3O9VwqyEqHXG0ndN/5m64wyRE17Wypl0ilSmJ1EYe8G4Z0UBWFrVgODoS959sv4ogZB2uzpFX+0BE2OyhJvKx58UM=
  template:
    metadata:
      annotations:
        b4mad.net/href: https://forgejo.b4mad.net/b4mad-release-bot
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: op1st-pipelines,b4mad-forgejo
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: op1st-pipelines,b4mad-forgejo
        tekton.dev/docker-0: https://forgejo.b4mad.net
      creationTimestamp: null
      name: forgejo-pusher
      namespace: op1st-gitops
    type: kubernetes.io/dockerconfigjson
---
