apiVersion: v1
kind: Secret
metadata:
    name: forgejo-pusher
    namespace: op1st-gitops
    annotations:
        b4mad.net/href: https://git.b4mad.industries/b4mad-release-bot
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: op1st-pipelines,b4mad-forgejo
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: op1st-pipelines,b4mad-forgejo
        tekton.dev/docker-0: https://git.b4mad.industries
        tekton.dev/docker-1: https://forgejo.b4mad.net
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:/6PiY8Qf8JjDP9qYecHfD85JwGEwtAMVvu2GK9HRn4N/+jKar3mpLDqkjzTU35x8ehKBPfmBqmHze9cX2EEK/PLGVt6NtIgrwezjCVXXtEv12nCekzO18vuEtRgNMc/EQgqSXM2kNqmBlJC27369fNPfJ/8tas+1PiomFB3W5qw8E+BgVXQTVmHo2TF3Ed4vSYOM/QTpMtQQbJl7QCz7/5EuPGdcXLyMLbCzOedtDnnDLk12HNTN0f40imXUQmDFnSL41PUfWhItCLzKv0Nw67JmxcUPlHXBI7igEs2U3HdB2RUuv+7xkA1ziVNusg==,iv:1ogMhu+uvQQVXr1ZR9q8cGIzWLKjWcpsbNyRKQZ/3z8=,tag:CdcT/LiCtW3jS5tU4u5CKA==,type:str]
sops:
    lastmodified: "2026-08-01T14:33:39Z"
    mac: ENC[AES256_GCM,data:Vi4ZwelMT/Xo8IEY0k3tQyyYvTZ9j4TbCwfurVQ0x+f5SqLics1KwZG6VUtrydfpHMQPv98rSEqyFBBspjUc4YWRYuu4d1/NTO6Vot6f5yDWBzbqqfOa2TbKTBTMaRSMbBrcI3XuGippgkUyTtOGaPrGMQ9yuPLGAFZkTmFYrHg=,iv:8oe85TD+cFOFKNDqffgrzJJuPQ02OqGwV7YaW578k7M=,tag:lzojrRyC4uQZpRWNraBGaA==,type:str]
    pgp:
        - created_at: "2026-08-01T14:33:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9AgVmznaOk7ARAAlaIZrNz21Hi2U39cf5urP30L1sKqc3ha/PXTC7jmy+fi
            C+Ro89FOGD9eToXS0LwLXn9zbM85hAHdFIBsVz8A/RVu9+BPAwBpnNqK8PHWf/WL
            Mw45jCATxkwEmln9qURLf49LJqHB+d/bX2hGgLE0XOb/bdpx2Qow7t1/lsXb55E0
            wFsvfRUgjfyDj2G+RLR2FwXGZVo5aMI/hor0NXnEapOvQHHt5UBKIwr+tER4ytkn
            EnjYI7HhMFGPgH0xo/LzohzHBcvSe1GP0nkar+IgNjj0AZnAwmzAVI3Gz19YWjCC
            rpM2FL3cXASdzXopXV7pGmjDQXPUQtpi/3KztQjNmHNQ+jEt5nzGtEsjxKTIcUm4
            eTBmjhtyjAI5xnGQT3s4jSIP65VXaUEbTO+pKHIMnkJ9QaDz5r09MSwa+yZ1hLcI
            BG3Ef+b5CEEVwbyZcQ2omIPL6IbUE8aG/daBOQuo1t0dECWVLcCPNdc8OJ/ZRnkm
            Ic7nq6y8xYMhvrhocXmrXkyx8DlYEyJqAkYGsE0HDKJwvcavxPn5sRGejFTJCHFp
            +h+cpuU2ZS153jmtSJZCwO/WIUDa7TkrGQCoOoTMYjannTw0lgxzb8uukfcN4Vfe
            rktQEPUI+SAukpvVqkK8/01Zsytlj2rZU6rdIZl72MbJL01WlYRI+BbyXc1PCk7S
            XgHYq+YAeV2bMqRJNbEniGgqiOWUhe4lIuMXLfSZbb2Qz0tLcTjabg85Bkljv3++
            CFrG8xfRUbXWZd9B1Ez0L96nbBexRktwWbDoGPhSMNp/taOZDJJgMR79D4ml3Yc=
            =z1sc
            -----END PGP MESSAGE-----
          fp: 04DAFCD9470A962A2F272984E5EB0DA32F3372AC
        - created_at: "2026-08-01T14:33:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwSHi8yuDIZWAQ/+OQj0ydftZ2nj+KFsVMakzCErxfUqTYGliOv+TX2C4vBp
            9GjRo85X4avpFgZZuHsQ09MyChqBGif6/siae+2EmoKIF6KrBatxaa7xLzeEEtw0
            2GTV+sb7H7t6P/vI+sjPjxHpWir9WQ2AGR1BXCp7xn4W9jYdpg0K5Cq3mJ8JML66
            HhLQiqE31R1wykmy8sjaG07dbyuVPR4lVnF/3ewI4xUC59H24/xoR+JcVOwohvcr
            NK7U7YogXEKj6KWdMHyMfzmIYoVrbnGHFbxmzy8Nsl75K8ek5LTUHCkPfryTG7FW
            /y0VGnV6FdRy552+38VvvFnZ6zN60H7jkWOsU47Zzfyw+TTt+15eS2kxLSwMwDSx
            wseio/oQe/XRuqBOoXJv08nPojE/Wsmx4db0CDv9Jc7RQkaZXl0v8dHaInqGUvxm
            4Q2XXokBc64XzGqx7HudTAz+6EUZSpPVX4iIryeQpUVBBp+Fq8mJLt2yb4yxY7yH
            GK2KUggdZV84bG0PY8IoHaq5SVbZHEvKv9y2Z465miarkGygKKnSVjmXwVfsavEt
            lgNiw+JYCoJAvmrv87jsXItJpfjDZsQrzZf/LUGkdJOQQVY4A3s3+BjPIf+tKemv
            QeiU0gzelKViSFvaJmBzuxHvydkNn5Sc0TvzaL5AsR6VbBy/1trt+wipPaXzYWrS
            XgEx7ret4IJvxI7Y76UTvJA6jv1um6kxtcHHU7EqVWthOMLVsH/EwLYvsnIR7W59
            wJns1qKS4QUo60WcJlsKSlenEDI3TB3Pigha6rBineMYKy7yU0wNGtBsv6W7Vq0=
            =luV+
            -----END PGP MESSAGE-----
          fp: 8A07D816280A983BBC35E85C280DB66A3E8C012E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.12.1
