apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: op1st-release-token
  namespace: op1st-gitops
spec:
  encryptedData:
    token: AgC35HOFl3HU0Ba/YGmT4QJhQmZtSp8jpqGHP8zQS2prY5e843wU5B09axwVGjhRww++WB9+xA2PCsoCslnGfwMDWEr1emtIjbZnlldmVqcWuyVBG3JJGBswk4zqBriwVlvWRtGiVZ8W/HOAPYbFItPXfXO/99I3CzWmNJitjVZ5elyVzttiiOPE37CKhKoJ36KL+7l76HHiXwmx0aMg2qRbzycIYg0rr/DLGLCK4uIf+eFQcxeE1/0BpBHwB6DO1nFkA/Y5/icPtwDKRYs1mjdJmCcBxs+4sJupTm9QxI7BAldGVkOoD+lN81a3cyTAZj3AMzJoUteixYP6OvfYVUmOCGy7XM5TSNy/b0sQLOY1zZOxPqRO1ol8/nEBvjXJFPuVZsBRZ94DC9ItWwM4c4BKifV87PRQsJFDZUoBfGjyvePxTbas4M2XaUJwbIkYaSmfnQHeEZxtGOGCilLvY047s7/9tHwEHVu7Cq0BeHj+luuzj2LDdVyRejXyd2r/ci3QvFeez3yeMV44vbOJrIsdnbpYlusaa3wy/RXysQLvXfqPm8jTDb7kyJ2S1wJRorwJYDRA4WPskQblpmoZuNFT0LcMbTEwaXtO0nh6DM8L1Jba7r2yifsT8G2fHGgDD7iCN0LN9gdfbZEpZdzkdPesnjYoty+94sjr3NmiR6Ys9VohWRxkcIytX5Or30NPkG6Srr6k39JgnHloFp2N/9HQ12IhbWM0j6O4BEEe7AyVMrAIbRP/DCxj
    username: AgCc5OEX95cAIiILMXyVh5xQdljnO2zH61gaHh2J5ZlcTiOlXaumnOQ0a3NxkjhNFjWVLd7/DqHOacmiUlQyYxHnHE6AugaIvpRWrrscfstl7a6WmAtaDnCUMDL7/p45NV/dY8F6KWwDTJu3+evkOdl+TKpW4fwFMmPbIvh1omb6H73yn0WTeXA2Mok5GhP3iB1npR972j3UjjCMbfsPfdjctCWypfumPjbHIrtIbT3A+0KcFij06rEyf1D8BQpKlwDHPwVKhGBjVp5V4iTJMP41ZclxJp22T5X19RZp+Prm896PpqIwCfMx2S1oL65QR5siCRBLVF8eBi609jnSSTXAcQCHqtA+uli2P7s7ri0WMtp3zMKg47mdzriqBHj41U3gKOCpCOZwJEU9G+xKIHa1VQDRlvdC3BRhzDlXcW08sGsODAj5jWsRAMYLO2cxmqhsX93cstDg4ePI+oWHocTVs/O/d4aMPt2o9I/lVl/reQSELIOhqxhQab/vFhRdozwCf2JoDHvCa8HtRWbgeXPcDr07oc9vc49ujQCb7CjD49vhHYK2vF2Z2sVJUlqyiVoK7l/kXT3xYFB6GeVxnO0PPeGXGw/clZsdAAtl1NGOAfhTYjHmGDuha/MXrFuTwHJ86lpAFGXReNl/MfdrzNtLg4WQRtb+mnoRMU9aLWYSisvvQpWyqHMjOLyuMdwAMXfY0tws9aJqQh/zEEY=
  template:
    metadata:
      annotations:
        "b4mad.net/href": "https://codeberg.org/op1st-gitops"
        "reflector.v1.k8s.emberstack.com/reflection-allowed": "true"
        "reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces": "op1st-pipelines"
        "reflector.v1.k8s.emberstack.com/reflection-auto-enabled": "true"
        "reflector.v1.k8s.emberstack.com/reflection-auto-namespaces": "op1st-pipelines"
      creationTimestamp: null
      name: op1st-release-token
      namespace: op1st-gitops
    type: Opaque
