apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-main
  namespace: openshift-monitoring
spec:
  encryptedData:
    alertmanager.yaml: AgBpj/MsJpW5KusyMcOQm6as6ukQeli4ISrnf1QF4ncr2385ng5j70xxVW3r7I95hihhDC2RmL6y0XNIlMgauOuADMGq0GOLLgtydc4hOOBFznvhdcJAmxI9qwcof+2xBm4PXaAvjQnqj5owFGavlI/wWNGBYO6jlolmksuLIpkwRSqHgdQ0h0t7PjIjs6Bmy/rnWgdEvliyJQ4IWBFToXpxTRVOPitMYf7xwC8WiL9ZXVW9Y0RbljqEPiX1m1PrhGmNW8e4DmiXroNRJ9gvoKLU0wj/abgVsDP3WC9I/nWZ+JFPpZrURH4o4L1vOVpSeKRof6AwUsggcL2awkyytpFCWR42rA4nlcqE82x/rriwRyTl6tEYVVA7Gsts7FhJx2SjLVoEtaRrB87RobDOPSNUy9DfKtRCr9R5K6E8oFKtxfNDy/Ik291QUeyrkexi6/jSzn1YBQ+Lxe2WlWvc/v+3A+kOT5/bd1fizKsdFsSa0VhwXkPW6QRkTfVtjZbD7gBLcavWpD40JH4Neq56ljfeuV1IYMQInpi+bSGA/n0KgvLrnFXKxgXa1R2xKnmn8ws23zFL15+FlcZjCY8AQZ9ROoSFjpfM49fGBFR0tJtAR1se+XxrGJ6/QGUmt9NrMhiKvtJQVVtV1rN7ys4cb4PV6JTGLXPbeCOn4LKinewx1h89LspxKllFdgGfWNQGgOJDQ3TYOdNnzVZP1T3lNyog8ys0vw4wtS4DKFc/+hsv035YQZV9CQnjHsxsIPobKpCE0ZPuyQAVvNoVLomGzFmysUn2Sj9cNsqAvwr9S5ewhenoGV0aSjKdg+MrGT9AFc7qIr0Boj7jaJqJwzaZRNHTrmFdisqMfhPuQJkPHL2XA0yNCvt2el+jJuuCzbVuA1DGUfoCIHIbR9XPn2ddDjRyT1pp0+97XjazH90XnEqqtczfe/Bps/zSA0dFxT95YLGTr/m0ZdHUxIVvTL6gxQkSRX+jwTh0JVylTe4uI6ZgoZOrNAmKs4G1QttV9MrvLu4gtW1FwNxKyWmkdkj1CmH0VwEeNOKRJ1lzt/ZVaMEgW7bGti/z6IudAc+xxJ0cP/kA9Q3TgNgytuhzYx9iSAeNdayga6nGltMZZsSX94Vo+sZdz03S4FShHTEiuuPSGubwliq+vrIAkEA+9iXTdGZWFnvgEXBbpVL0hLy3PfLXAsEniFNhuAtcXwMryox+Ziov2YoaYkm7hj01/hHz2y3W5arYHudR9pg/HrQQ4lJrKaJsF5ygHCQyxGHt8iVqiZOFKqUXq0yX42MxYkO6ddbIp3NOTLfRHJrRvKeT2vLvtkKHKbzBJgaC+gKw8g+g3ispKR3k55J82Jyx3SYOf49N/fX4dTAU/oVJ17Xr0ALowGXoxq9fgF4R6kAk1eyJ9tWsB9+QKpQxJ9VwmoPDJfDbTdI5dQfVUqpoGPouLv/jik468XgnBEvsebr1Mf1cy4Aa4OYtRKkmYr7wcnQiUbEPdlqMXaXKnJqjCmVMgUWGvWpTUYX0IGvL2gaPIK3/DvEiX7jEXwl9/oe1V5WKwsOpGM4p5uM+QIV2Pr32hhytPtK7JYPyis05nBvDZaY1Gafhnm9M+JYsBTb6ja6AF5hnSQzcFksPx7b1kd5CS7Ij2HaARGf7++tHKabnhquwnPQ9mXsRErLKUu8q0sI1wYLIvEdF11v4LDy87Cj2qt6rtYxwE8Hv/wHlDajBK/flQkom6KyMXwncVL4FVneFzQ==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: alertmanager-receivers
      name: alertmanager-main
      namespace: openshift-monitoring
    type: Opaque
---
