apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: codeberg-runner-openshift-pac
  namespace: op1st-pipelines
spec:
  encryptedData:
    provider.token: AgCynDG32Fm2vnL042/JSKm+Q6UsOWkgaj7PfNhkospSranMBq3OhxtkZc5gcVeHjDLZUeKJe7WnjXPHVvmS6ff1vRLlJySiDmtsSN8uJU+D9cgnVKq7sSKFmpKUjH8rnlzccplf6imXd5arxwi4/ZETOuVIRct3dNKvR2fcHtK1dKUYAnFaqW+Wl6lFUNC/PdvlCkR1zfd7ztBxnbvxJkzB+kt44Mk6WHaS7kYyhXlYEy+QraOPWIGam73sl2h7tC94W8gBCKJKbCz/pnKotEctmCdvvuJGOHkV8lQ/YXDZa8+3y/r58xKw6rrCT0b86qB8O4BIDbAwaLOIOj5fh4pBtJOQW8xvGkA98W2lcrumWSrFayKo/XSGaD1xRAQRMoQPfq0vF/DivZQLDMdQTVixAoN6V6RMwoZQ9cx0nwwaxKSfzBRjQRw9/adJJrubmm/2/SN6hnxSLSluye2Q+5G5y3TC54qv0pg+qUiXeq3Q+em/XxOcK16VRJ0bRuGwgz9bpXkWxrMF5CgzrLsE/mVYNhLHu2Bt4TrGbKzyg2V0oJgwvvunYTXoedG2+7/lyLK/I4JhHrQTrq0nBTll0EXSTZulcIbbzhN4OzPmd1PO7O2uBqUSLx7mNss7JOP9XhSAD3155r/yO43eAkd/iMgODzJEqLw1Uj3WbHyCohWsx7c9MGPjoYy2xG+OSF/OZ6upkedC4I9VckpMPKCC9IZFhPguVnsbaVwZtMieCmYQejLP0LOYXej6
  template:
    metadata:
      creationTimestamp: null
      name: codeberg-runner-openshift-pac
      namespace: op1st-pipelines
    type: Opaque
---
