apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: codeberg-pusher
  namespace: op1st-pipelines
spec:
  encryptedData:
    .dockerconfigjson: AgC+HVfzo2bvPKEe5n3DRBiPXycxVCggb8WmcB6Tw/34a0RxO1uIERJc/4YqZDeHNXWC379T9CyN/oDFe4feTJW42r7KzjQBWITESTFyuncZarBLF0a8srm5wIhTJHqQ2IXFqduXW6RT4a7NoMcgOefWCEaUHVigyRH5ELc8qvLB7/OFycTbOHIgIVNZMJy+4+uu6BnKXan0eNkRzfyrxygExNeNFwiwpxxoJXdC8zIEQYbNYdsfsNNJ5/wGTkGLEbML5gK98KTDi+dLMwkK0idMNtGfTUGPtl3YcfWXy56cnA5ca57gTH7ARTENKaCmy++yHYL3nwCudp26StrOxy9OLXEimhA/epMzLouUBCOfd1zaHv9RUFLkqSu9c7PJ5+7sgcoqFbCqJ+hutSmS4/3askSHpnvi4p5GLstwQkUlHow7GkjPS1Odo91ra+xpByrFWwnsBgGiZwSJUph1svx4an+z/VNYcc0dKC+nPupAF/NgsvraaUKuETypruxL3QzDTMP+Q89UwUkJhBD/ooGZKjA6K/eLDEroUYcBdP6vIJV6Ly8jzQs+aTZSRbadI2JZXIWhhwPVmIdFZnFvIvKtk9qYpas83KqdjLmDQHx54hphdp9oLGPgR8rfVHtnWnr5Gm7l9ixmZWt+Jw9jscKufAb1CTARsrNQiAN5ZHWHzyX0NOfI43++UoS8EXo+agMHrCex/HKVaeiYos6YI5A/nKnYCOkwKNh60qhpeEJQ6pImzs0WAbRSoPws/U+iHgA+1iIQnUdmqozr1zpd0LUjGq+2MnuwdbKHuN/o2S4WChuVlf52MRiJGk2pNF+huhxaqGGcpWav3YLKcKtDOGTAhfL3A3+WAhU98LbGlxt831tHINmGqIpepmi+VmsRYu/JAOXuoMfQbSWgn4g9IcIikxiT7KOsUcJpO3O61qyjNaOK8AQTSXUmf5NgCtD2R2S3bp7hWF5N9hunk2IimXehqBOuYZypVfKnCEYgjScHIfZ0jbrxkqpxizYt03HG5FIgLcXl2EBAdfLcHyx33BJxPcPixk0IIBgHfb0p1yAWOQ3cR6iGgeoixuvCKuIuT5bWkbIHmwhANxU=
  template:
    metadata:
      annotations:
        tekton.dev/docker-0: https://codeberg.org
      creationTimestamp: null
      name: codeberg-pusher
      namespace: op1st-pipelines
    type: kubernetes.io/dockerconfigjson
---
