apiVersion: v1
data:
    provider.token: ENC[AES256_GCM,data:D25AyXZgWfrKyPwaTahqiH3kRPjWSqLcch67sAl7n2nX8buQh3W83t1Z97fn5kWd0PDnMJJqCwc=,iv:Ep43ejOBEKYZ5zy91PfHt80m1iTGtuzI2e8Xx9HijiY=,tag:s22kTjyjeaD+wCrm+EJ52g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: codeberg-runner-openshift-pac
    namespace: op1st-pipelines
type: Opaque
sops:
    lastmodified: "2026-05-12T07:33:25Z"
    mac: ENC[AES256_GCM,data:z3a+sVQ4R9C4DeRjsXSk1fuTNTorXbQ6+Mco0HBmrETCv51BuTCXD8lbhSgJMOnxp5lr/4V7lFPcKPn5kGi20dSHoPmWwmH9WeyfcIy4Sms08h+XoDXAURWx9nVGayZO5SRgulamolfhxZHiWzGMr//dYiRnhtoBQI7Ef5d1zQ0=,iv:a5XnhHW0H6xLQ+5oUVY5WBwB6B51L5PzGS2vTlDwQos=,tag:wBGWZKCuAiUc4N378fCeKg==,type:str]
    pgp:
        - created_at: "2026-05-12T07:21:48Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9AgVmznaOk7ARAArWr3MbaLHj+G3pktYwQCakAgGeeHZ+nnkjCKAtas2JBA
            NRjXUsYeGmTE8gX1pUfasCV4mcjPa1R9fC+bwlDhgv01Lhr1onFq5gfbA0YR2JtU
            zWrvaXf4mN6ow3yYPGN1WZcntAeIf5XgknTyCtFpJhjYymnvCegL3oq2XCrYWiye
            HJejl0tEpqZdvtXP5y9mar/JE0ukTJv3tgPP2ys0ppM4BWx9BlScZVnV8R4mBqXy
            eNSDtWCWujaR9J6nqYD9hyjgtAyejg0wa3FleQObz4gpwQCQgIlTbTjshCYkErcb
            CNAAZ39NXteLBWq1nTpC87RgtI4GOuee2PhW/pPUP+Q5tbYOGMbYlpZIspxfQKAr
            RkCa3EYLDieFyj9h+PXvBIi+Wifl+wBJKAD5nLuwbZLIb+c+EuVkaH2lcpEYwbS6
            szICcVm5/YlUboTPNIfBOIwgaaN0BijR3dwvVb8nfx/44B4d3uMcFZSNhsVKaiZQ
            V878dwlywPldtMqWZq8YMj60+j79fVyraXxRgLXtw3TtN4QS35xTnINdN2tkIEpA
            OeZ6pllXd/b5Lp/QMAgXI9PjIwbwF/DTGcbV+xoxu/k6RFuO9LQ95fACrmNL42w1
            /cYBI3L6l3t9Zj2c4GjsSghrHzMcf8G0ZN/dmjeeDE4ql3tF/efUNX4AQ4eIm7jS
            XAGcLkgQhtuvtrnvMiHdgJhKUGQLLGNJD0CIcy9vCVWS8cbmXjAyMlfju4Sse6vk
            clUBvD82l3VFAK1IZTC5/Z62AU3A8on3JAUt4Mx5JTGJH07sDAnnWdoucQ9w
            =oP1k
            -----END PGP MESSAGE-----
          fp: 04DAFCD9470A962A2F272984E5EB0DA32F3372AC
        - created_at: "2026-05-12T07:21:48Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwSHi8yuDIZWAQ//R9UjVkxpRMrJ68jKgcPxkuJURnUb6NCEQb0uTQHXdhrx
            Ph+j1RGkb/GtN3VCK7vIe1aua5+RYH01RMv/bo18GullZEePoYOjcnUznjo1ixIo
            AgLBOOgGJDeeo9L/yVCgt8YOIkcIsvSV93o4Y1EZByJcDmIsSCv3iw058ULPfGF/
            NL2f622s4HeArVmQB4Drpki/qFPahsBG37qTWr8hP+OvkiJbojq5Qj8BS/H6YWDG
            Cjwa2QJBHZCha6xg0+qNzjcZaQ4atkwLbLMzrTFTSJpc4CuJy35Ph3IERLVVXOjZ
            H7LdzqH7HAEZpclb4AixfQyo/iWDnt3vfJJvfn0vWqvPHq6lUcSvKB3fRxSmREM5
            kFq/fU/FzBpJVHUB3CDZdTMhQphnVRxytJ6NvhGhKYQyf7iMTsHx/o0WxZbwOYcZ
            5TG0C8P+3ae8m92r0puoZGspkWSKK1o7r7lsexMZuN7wfyWbDK0iLGFEA+KG6xvP
            5RBb2X8pROJgwb3PE98C10BCNZ0JY59aEDk3M0VFwg59m+Q7/LIXZ9SrJFXnP0x6
            XUXiTQJN4sCCgvIOWILyq0CNSz12lfLOZAfuzDwBMBRC+fGbYf9FzRtNSAG6DwIl
            yYSWUrZYQnx07c9p6OEYcuUEZlx9xbqTOsvUD0zNJQ+D35LUnatW3pYDN7HQHA7S
            XAHpsipohsx7k3SQfLWyIcSSvmNCBZHQaYcLC+PUCOri/HytQK9fTiRiCZiTBZfM
            6+K/KQtfYSo7tXECOwtuPKty7ujSMm0jeJV4OxKWdcGVZmJwpto5TLsxKovV
            =VWrR
            -----END PGP MESSAGE-----
          fp: 8A07D816280A983BBC35E85C280DB66A3E8C012E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.12.1
