apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openobserve-remote-write
  namespace: openshift-user-workload-monitoring
spec:
  encryptedData:
    password: AgAzVK2yY5lVmNgKBn6bNsq5OK7BgX1aNSN5y7qgyoKOguu/Jc8rd7Ci2Azpzz8xwn96kJV81luI3S/FycKbuTZ0vn4uAaWn90D1HXvl7Ro72iOSS/ncltTUm3+ndY3evGSP1dIYCI1nE6SCWoAlSrh5K/1GIoclLx4grbPsXpHnSNuiCdu6L+H/BWn4HHK8GDBUYAtuZzyYr1GW/EBgBwn+LCNPPa41UL7pCfoH7GM8Nn20OR/7whn+0lMibgkzLNQuiBTWgjRzc3EYkEFLYc7Rffr+EpMOxsngnV7wR0d2ZEuYS3kiSDSlsKWSOZqHfh0GMt4rT60OKmNMGb8yjnxDGEyBPLPcsZEmvXGZQ+N+30LsXdEDbqd5TCYeEdt/ZBrH/O+0363eiD4qwaIoSHFlfHtNthCJXPomicWbkn83TTvR2s6dYNg5uQJTZUXDXC7ROJlw6ZYRK5J7UrT2Ghe//h4sNoS2M9l0D1BjqIBLzmb5n90TWYd70tdYQFYSSH+VyyJvKdblBki/Jhktzh/ECNE2UpR/ue1/qDXuYZVkGMEE6cwk8CQlLGA8r33ECUoTEm9urRULWA77yCsLWrsGsZSoPyowQeIUKTp/alxqJkjptsLdixmQiuKHX4iAUu8nmGVJKoDyLi/YU89I/w+2Z1FtHFZk2dth++6eqxqGheQdKyHRoaR0/i8OuX6Ues+2ngBhEdwAt8zsADxHv9QFvB3OHZwXlo0nO4qcGDwwhw==
    username: AgBP+LbVhTzSdjB3X9OdDxpFaeGgC6ZT5xkRJLDF7cnf6rrFSlHCQall4J3X13mGmEIKt6mPDwG86+65rlI1dB6hDu8l2YakqTORna/JepH7SlQBbCMh/5B9LS98ktaBRRUVHPXQPHNwSteCCDz2QLtjCkMkAC0tq4UY2zO88Y/aaMTypsUniGhwEkc3jI4uoY+p4f+PBmJSos6wXkQceDd5qjIN0I2jDsbj4VtzHNinyTXLGdesQtUC7Gf8dcBi9sSlCAmvws1IFlI0VcQfkvieSj0fU79HUf5FA+lvTK821avx/hfTFMThz75B2sv0jJ53v44tGqIMhPmYAdVEUX3MMQ05fLVsOvvJxzweSrNuqjISEwU1OrO/Bw9E3rxtdSfsESl+L5BRJAPD5g2U5WxXzk2n2+LgGV0dR2KF9QN9DV31BNqhOiDrep8qOT/Rqan9rzAwTGN0nbCE+LOY5n0db1YpXUIfX3szljIW9AwqN09juTvGCv+WV9KPwtV0XvmsQXuf9twYNfpV/5CGSOV9zhf3/9aUEiOXcotHlJ8FN+fGHe18yKZCWzXqo/PE6nuSfOstVXNCfmzedcYBTKGQhRaoWS+pfF9gT/VXQXI95nSpXTSFhHaaXBYjcNYgmz38GK+KSV70e+V5jgjPoYy3s4ViivD7+PoC2z+EvEB7OBkJhakGZ7stWpt3hhQZgZM38RMzERcXNdggPaDHJyc=
  template:
    metadata:
      creationTimestamp: null
      name: openobserve-remote-write
      namespace: openshift-user-workload-monitoring
    type: Opaque
---
