apiVersion: v1
kind: Secret
metadata:
    name: openobserve-remote-write
    namespace: openshift-user-workload-monitoring
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:/4sFMsg864tlFzCXYq6E,iv:+Jso+p0bsiTAAL0hjG+BrtU+DHpNTgU1beEvLO0Qar0=,tag:5/pRiwbcjqckY/rvjCUn/w==,type:str]
    password: ENC[AES256_GCM,data:6DQx+CvTxU6xeXHkr2In8Ojn7xleXZHnLYpjDCB7C/k=,iv:mg9Hh9+KcTqpu9T/qiGyH7QCHpClNCeHw1E4k3ysjZI=,tag:vi45w1dQOO/aK8mQ5XFB9w==,type:str]
sops:
    lastmodified: "2026-09-27T13:02:04Z"
    mac: ENC[AES256_GCM,data:E4IOmYxqgPYZ5KqjRxSRtm9MsVw1XnRDUe0z3y3HEN63jbIgPUBGBLezRr4UkmcMSyrDyl8aPmWKqbMbzkWpH9tsSEA55CL3NN4IQFkr6e+wB1PFCzT86DLdhmY1MWbEoZs0pT9HIyhQQJ5PVw2V4I1Zn+uY26DxeqdGlxumikI=,iv:ICGxsb3uIyydr65tj6xhjiWWx9YS5UhGLFyw3LlI69g=,tag:YPkse5PPLLw4WixxfGWZvw==,type:str]
    pgp:
        - created_at: "2026-09-27T11:30:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9AgVmznaOk7AQ//SyMwdb3LV33uv9Qys88w3GoGHXnX+8aVuFc6GRumA+CD
            nkd8gSB+raP4KtCdFawMgR2fauUzKDBlkc043OvFHU75E3wVYQu1UgZwarcMtbYC
            wKhuR3XRXxJRwM2DE+wqiW9SK18lTQJ/IsPUuCMIUxdXm7rxelU/N60wKBUtiFzq
            HPMmip8Xxjh/lN9wV77JiYPsEn7+KVJnZ8k0JhFfHxH7Sy0FKODGMO6a0LQbEDNg
            D3WzHin17WcJBtpPHN94G/Ctg675+tPD39pERz6kgoyLaG5rkXCKld+QNXqE/Mqu
            GHrg/OT5RQ7orvRRxSYJsPuI745bEKRoK+q6rUXKmOlz6PAbnXVZl0QJmqAOrkcF
            Xl1nCC2Ixx/JMEg3ZRN41VYyq9Hqb8/s2SZaOthb5fMMYa/O+EjO3ERFelPgJSka
            1/PY39rCA6wty6PMiSt+eEnveYpbFBQ/dSmv0j2vw64yYBCHkEpwv4g6hy5Dq0pn
            9Fpm4LUncRF9WrSQuBXd3RfX9jgAeswJGKlCiplTgtWhC1nV2Ktytj8iLzrTfueG
            gQCdQSzaspkjMP9fomNRcl03A4mxzoCo0JCTfC5x2UXQJcRYzNHGDnMkB0zLYjGy
            S6GavfrF9EwRkrD9RcEgJeCnHoFUycZ816Mty1IUnHbMYHSloiaEadyNLrATra7S
            XgE4djC2vB/3HM1D7S2HNimlT9WOOPNrjaIdOHgDlTvfMUNQ4UnPKGp6MlSo7pVT
            zqcpMZBLc5Ac3q+QvxOYrHQ8e6JqtHn26Fh/mZ3beUHfcN/e+qPdBfUb678sYxo=
            =lJBT
            -----END PGP MESSAGE-----
          fp: 04DAFCD9470A962A2F272984E5EB0DA32F3372AC
        - created_at: "2026-09-27T11:30:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwSHi8yuDIZWARAAiOjsIeJbck64LOHa5maHARxyQzOkwvVOdfx2d3MI+Nsn
            0MxXfYIu+eDDj08dXfyVU79g74S0dD8fLlLRwjXWC42I8t87ucPSRpZA60wqJKwN
            DPVT38zJd3e4jbTNfBHd5xgPZq1ixS3dAJ5abLvsU8w0rsOrqeethgpuvUjeDmSa
            YIz69ubOvtunJargbCGGHyJG+yt7uFaL0+P2F4cquWnvyVlx/qcBUs+lIvxjoR74
            Gfm95s0zibwCCtG9Bm3fvLAtyw5Dz92xD/Cv/RX9pS/n58nNZvgQsN/SnrU/M+CG
            ZmsC1PdfX85CZDutQhdyXhJE25dJJptue+fzMIMLQ7WmvBAt2L0+CbTSOSZBJhZB
            I4Uruw1a1DtaOp1XEVPThtPa77IeO6c04r06c3ZpEoTzkvG2CozjiMWWjURA3fb6
            8Yhpgxw3OkE+9jPkE/z3kSWoZXotXQ29DabNABfNTzd3Iz3U67CqkDodmIc0Rmcx
            DQloI6Yzbv8kWi2VLbZR2pAMxp03Ak1V9nVVYN3OC/GJf0obGH5TwY2EABdZ93+7
            DgQ/nj8Thz4ghWA1KXwVb+ezGsG9bXAI37nZMOpqBfGadbWCna/0q1BIIaP+qYvz
            JE33p8qNgRpverW/jHdxtlR5M9RnqqzP1OhblHlL4S+GE9+U7991I3gEqAB6Q4rS
            XgGI8KIc+WRDksX9q542mxSeEmq9UQ/2NpbQQ27XfdXiC0nNJdEQNxMDpsm4deu4
            fa3LzcMsGwN7IjNQBxSTQFxX5p/TXap4bx9/izA5Lh1L3vzI4wK2711DG2X+aS0=
            =60dh
            -----END PGP MESSAGE-----
          fp: 8A07D816280A983BBC35E85C280DB66A3E8C012E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.12.1
