apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openobserve-remote-write
  namespace: openshift-user-workload-monitoring
spec:
  encryptedData:
    password: AgBTUrS+aFz1TitXeCL1KcnvZsYuaohgEIlF0p6m84cXGV9jCNQd9RxlrEhFxTyZcd2PAivRsHc+Z74srL+xq1MSrhtWOJgLWmgv+md8nRtejgEE0fley8MXs90Y6mcJTEhr7u2oTQYBLa183FmgxvUhl4gvJez9aNUI/kYE2EYkRvknV9YYlzte+fx+KJQMwv53NiUgRBGn87fqIDZeu07R6hf4yrjtF3N5n8nx0y+GCVtOAXHkeMThQmoOgQOGI6+zYFQeBN/7Wq2IAj95iKBogomsaqilkHl9yrEYigXu1BTqA5fu2gK6QcI5IezGtsOgxLqwoB8qSCH6gaMWKK7aH3K/WpU+HEmEKLVUIMzIeKyg3GST/YvAIPcLGiWJaQI90n22uWzIEJkCzizoP8CcXRYwRvutsRAoKluqBlDVbkqRqva0i17elk2zDqwSizEF2Y7UUwqIyYPTIefpuY2UtD0Du0xoCIFjeGtwaaZVu3jFq2ic0/g1k3vGgp2b1fBDv48k4MGitXpmb7zD/n5sYIGETJa6A+o/tVzufb4jy0N0GblWeBoFyQP0ae71L2ARrkEfWRK7XFwqXCiX5/xCjVjSDxRmExe1i+KPBd13Y7Kv8msCkwKbLgbqUoM/F4WhR5Z71GghN5MJGuFslpsrcrZIA3uZS/wki4tXuF2pfDEFQ91xErG/FlzdLatCimPaI5ULGafPlIDqriJJR0yGzQ60LT3aany0hoIvdmBBzA==
    username: AgAxVwN3zJhNvfsPCMP4mvvI0ylGU5wNfXKvtysuhfKZY7sywKXmAQjpPxhk+Pb8LVikTjLiSDpM75qMicpFYFAWO2AZnzPcr9DEL8M8lwl4EJfobJGBTdaKJmN4m8DZ9RHSLp2Zvdno6VqTOI9sAzkLM2YwEdwqpK2jtFpO65MMk2R267EGarydjZ0c49e4wQMJAJwQJCtJxM2ZcJsxa876S0EISyB7ITQuCXznDozYco84Q/Ik7XNc1StWgyjE6WEUv3yUHI9aJZsR/5ip+5VATJDEU0YS7A42Er8CtIeV2mc9hN6suyKrWACng/kkMfOQR/F86beNwCfRwPUMdAlHctNrgGgZLaP8CQwK0ii0J7lrKvIaXkzfq28QBnjmh5FU62dU+fertlhWXFTu+OKK4XCrHwjTlSxRfie+arbWR3GdkTjHDyelQTC1vT4MWCyfHOI6QY8GNlfPMB1mgdtZzNGRScc7LH7CWqxV3GZmzsY6S3bhLQVUCU4gcvw54QOMiFFjZ6NQ+KZd7agNaHEiCmopa8583cF5Nz+g4UhaTf9hovzZPhQiRVxPwVUsSwnzlmETJ3ZEmjoINKJjeo9UnIzuHnPRLhn0TirEiRKLiho2POmEZ6/Tr6aCipQYPkBM120wWXQlMq0Ch140bR/kF1MxRCmUxE7ALJqBvXU9FKUSmZZLW0gwPg+QJghoBYumVHXCFEIxChBk900EkQk=
  template:
    metadata:
      creationTimestamp: null
      name: openobserve-remote-write
      namespace: openshift-user-workload-monitoring
    type: Opaque
---
