apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: perses-oauth
  namespace: b4mad-meshtastic-gateway
spec:
  encryptedData:
    perses-security-authentication-providers-oidc-0-client-id: AgC6zF0CMB6yFdbHBTz9FcfkqUHWR1T2aVSuX93vmdpVMBIVMNjxZ5KsxcTb+51GJyWY7pvvBOlK82fyms/DySWvkCMmYEM1RmVabGcvToWqRue/btvCvxJbimfhudekHBYXJ8aKt/Nu3ybW1ChC3jfuhViwHQCMeARLecWqujRc3hudKD79BD6IxtthrYHPrZaGOS0H7veesZk8SqtlH1IpPCtCbtzZVfiNIWH0fFk4YcKesO5nHTRP+fTSZ5Di073vRL8eRT1UZgd4ra1pZFvPhmkULpRUKDk8y3c3vIqIOCuGVRXd5Aiu9RN5JQZno3BGg6MQBOVP6qGeipWKfM+5gAyldk49Mu6du58tFiy/HNSN7eB9GQCB19kUcGGFt+iI9wbc+ZTd1m9FuNX1JSSpk+GviOA7mozBr2MerQQOFOfkj8KZPKEGzl0ITHOa2tqm8gPCq7hsbDXZHECAw6H28mZoh44UhNOYYmjbbYoMoJV1ZGchd3vnthlHWqarUz8Lpp7N7fQSi6gy2B2Q5gzWBiKQbpZw6ByYjvLGVtELKczcfzHWaJrX7lj0VkwTh7Xe1w60Hll5tABHL6+0L4/1PWky+50pDIYDnQRjTk0Vbyv6saYmotnj80/7K0wUo2ZC6eo8GSMtK505S16t2oYqoMHUHvTcHtoqudGxSkkNyu17zquEt98A6+OrNSukQ3IZ1Tm9CaL2kce0MloGjRQYMC0=
    perses-security-authentication-providers-oidc-0-client-secret: AgBkY2KrwlkmK6jJfwZ/mdNPYozGLyjaeHdxdJZ5nYvI65FaKWRaUBpxsasni/qvUQW5i6IzKdjjVmhkiD7HBYX6N9374NsMzMeH8eQeUrEzh9Af0+FR+HbiGgcJKX72HxE52vgnwmYfYegGrKDXkZKANnHYvheUL/YpUwKtzi/zQMYO+XaQ6Nh7utVNM/kX9T/lz3VhQ9XX11hWekKL03cUu9q9gXW0dOvkwXRukwHgDqSgdU6D5KehQKFatyAlo8scd/2wIIg/ya2jguxJbDXOaqf7tQXCOimOPkjPLfKOuabVXWN+OmVU5d9/vTlkw2vCoUZROxD+qEWq7bQEA6kSJmT9Wx+RmsfSFWQOODj2hn8vF5P+QUgQaaw5OEH45ldmypLeE6FW9Ptzwl2OOKaK0HguNLnM/YCpexH1HNYJ8m8HB5CFYlmZGjk/BjnBOvlZuwDO0rXFhrB7e8FxQvUB35d+WvoOsBf4tcCiXrfguOlxg+UZd9jAqmGw3yUJO551av4Sj9iJW9lIar50oNNxW8HCdkRW0w4T4nxQdMuEsGzNoO0dNfFOjYJjMC2UDBVYfWGFETr1T7F3DDc1ui9pNfDuoUQ9GTdQlkrluDkGPIu3t1S0BcDANg+BA7uliTdMN+gi7r5OahIICr0GychfFyT5NTnQy8Cuk9rTK1HNfjP9Y5bW9xYIPcypmrLhlM0E249k2q8TAPiSXs4uHHNcyn8OAXny1EZDE+ztNSs8ug==
  template:
    metadata:
      creationTimestamp: null
      name: perses-oauth
      namespace: b4mad-meshtastic-gateway
---
