apiVersion: v1
data:
    perses-security-authentication-providers-oidc-0-client-id: ENC[AES256_GCM,data:OeC7F6vE/jIpx9V83gMDvOsXbPT3Yevb,iv:AkrmlgiWWUg2grWGk4pxs2FLaakw0y0fttOI1v1VcEY=,tag:4IDewFf5NE/hXrbmE6HHRQ==,type:str]
    perses-security-authentication-providers-oidc-0-client-secret: ENC[AES256_GCM,data:jB1cMapuBONT7qJmV0Ehi31ERcUnPX/FFjH7QoWfZPs3x9J08Szih2IWFqA=,iv:i0NCanv2farLMfaZyKm1dH7xoGFwBGYukr9ozLY1ja0=,tag:jKBQvBFvxAqRSnlztJYNig==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: perses-oauth
    namespace: b4mad-meshtastic-gateway
sops:
    lastmodified: "2026-04-21T10:54:26Z"
    mac: ENC[AES256_GCM,data:0VmSazr1f8OwChyYEXTf0sOvVz3AYpiK64VQFe4CixTsmedTAdX8ucCGYvaLuO9YiGiC/j3jwK8mfS+mmzezeZFma8Ebyo4HIGu4ZPnqak78pgzg76txkR7VpxqH9KMGXMwjptpc8REhODGXoSkkdvNdpbEuKRBcU0BnezWk6Y8=,iv:W+V3tWnkCInhmJpRG6Ulvz7h6DDa/EafZ8pNcPqOI+w=,tag:xLWyiVeutIcHaVeipIO8gg==,type:str]
    pgp:
        - created_at: "2026-04-21T10:54:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9AgVmznaOk7AQ//QbS4Sm+Bf1+qCx0XGiJeN7pCjOHhFvYrE5/3qifmMv91
            709ooAakfUNbWIHorsH6XLYtzrLWVIdEgFER6kgY4AS1YdY/SnAeupLfRhleiRrR
            hFvqHCgsLhi1ip3ZEko8NMCeAtgYrXL16i/SonKt4mzjDJbWbY/eRpE8t7eSiNj4
            79x13X6UOVRRu34DBSfQpMbh09/MYf/q85ITjGeN6bwron40mKkoIunbE4ObI/0C
            eLGtnLGXg1gkOSd0G/vwZVT+rvCcxrc8DgPyp3pgwRKJjRpQ1ZKPcKrTB7QNKELH
            SzfTThrXexqmRFaiU43JJ35hTjARFqQPFBTU5LqeuPhmMJk/ckO61xLjOBZ4G3hi
            a0eLp8KoIhNpjc8gGpk9VhxXDgdE1zp0jl7kFJBUcg+nybkc8AcvZa8z2Ne2cO4O
            YDJ01f8iN9Ig8n1bfPJRWKnPiozXidp4kZA8+sQfYSZGnSrdy4EImP+5gfcEuqOi
            gyzm2fiAWZNquwS7tmUvUeD7hCzDsvIR/omp5TEJSil1Ec4IHk5OWYUxAioe83RV
            iC8Op8IaY6/KEJPFhShYZ/yP/+mDd+PrVLrbqu6UiY/2VxmDoNxZ5PJEuNDM105n
            yWdBA6Z8HvkUU910/dEnMaKdxuSHFgUsFYjEyYoc2nrJc1zTV6zZ2yRqdLotvlfS
            XgFydY2nSMiLsdB/of6Jv+chWMuo2HyL96HNbYSsR6ZJ/3pyRg8M0iIl8I1iyHLW
            o+hQ8Ps6Jljm3dKig0yoNwK039j2gJIq7IrXCNCLlT6iaoQxrKTvdVwVxmLdVmg=
            =kxIN
            -----END PGP MESSAGE-----
          fp: 04DAFCD9470A962A2F272984E5EB0DA32F3372AC
        - created_at: "2026-04-21T10:54:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwSHi8yuDIZWAQ/7BYFydIY58OKcJrf0jYNipUTFDFgXaDWXJPmLaUaeduX8
            +dV3CvKCgFQ1nwObRTrjMENPROvyOvkZVQrzN6uHCsW6pzffN8rr2JvKgxHOWXyP
            DGPwb0GX/6ITv2zwANmmyCZP3LkaSKHpaPwpA99bF5IXi6q7jtRSGpeU7gj0KN6+
            XKZDrFhjb9nvBLU4/tiPsS+mwKyeRV+0vA0X+RwnZaqvoME5aI2JqjiEgi1DbZ/c
            Yzq1MOAogPI2DLvbe8kW089KtBDs7kzfvOlzZCscDEQvzouybLWhxmQgOD8R2otQ
            31eIcZs1IxnF/ejzGOzfVfr/9kwqrq3yu1JeHYYH3/Y+4dutrAuNb/lhiYFXqCGV
            OxpFOw+SSJvbaC7u476gWTjMT/R/Hl42Q1yRaJeJHMwHu43r6QySPVMSCINYPrVC
            Zoy6gQvb6KVpxkirOq780fcgidHsEAyJckW7sVGCitev+MX7D5yHC0RSmFeq78yz
            B0zMHGFfWOMt5ORcoOfhScZYnU5eX8YfFQKYEEpTzjHOyHtae2W+MtYd9/aG/xeZ
            TTfGBZgNbrC8ZSuRLhSzgGtKzxB1GDMfx/hM2lP/C8msMpRpBq2aFUita+f1GjTW
            kgNFjwNiEQoR9EgDi271e6xoQ4zK9aw7RVLB+YT0/oFgsw3iydqSW6jjiddp+MTS
            XgH7uG/hWWMoHpFAVvirmA6YtnsE0+jNoVyHa95wzj3eZJMEpJDZx62azGEnF2Y+
            TlFCT3g5dk4avDooAvfjPnZKi59Iksu6AChmmlzNQBbvbJRIKPfi0o5Ek//HMm8=
            =vLgK
            -----END PGP MESSAGE-----
          fp: 8A07D816280A983BBC35E85C280DB66A3E8C012E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.12.1
