apiVersion: v1
data:
    encryption-key: ENC[AES256_GCM,data:ibve+J0VZSO0pTOBEWe0SbIr1ncCk0PK1SIFH8Fy7gUGvCVmc2fUQspDLHI=,iv:KhVY56AqVjBGIdcnDiyv7R7TXF/A+ZlUN1SLG9PeGtY=,tag:TbFJg0m9RXzHk9YZyBK6LA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: perses-encryption-key
    namespace: b4mad-meshtastic-gateway
sops:
    lastmodified: "2026-04-21T07:55:12Z"
    mac: ENC[AES256_GCM,data:bDdQNRvv3vRXoroE1Arzoez+DEwwuLhhTcZiadTbbRkzkg8XQowLK1AXLGgplkPtwwGBOSSWz1WbO+7LqCmh2xMsIXqGmJ0YlBVaS/6u1vmjjIX9UHK5jPYG+okNwtl5WG8iY0lRabHFIM5NPqQs7EiMzd2BiyIaAp4+hzVO9D4=,iv:yqsY9wMoItgo3UQUUMweUg++2V5jhnanX/2qSeCkaYw=,tag:Y8POp9GOO/JsM+HIlJURfg==,type:str]
    pgp:
        - created_at: "2026-04-21T07:55:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9AgVmznaOk7ARAAzzeEvUlE0BVcCFT6LaJrZka5FP16fkJVENjg1QPOk67x
            1URvVTVAlb0d5y4HGyg1lSNLq9HTUtOvtF7cMhm1n4Ryg/sVklpld1oI1/Tffh5J
            rqj2H9NrU3m8mFaH8+gtiEmkHQ9vYrnRyaDhGXqYHyVqF0tQg1w1SE0bJqkbFCV1
            vOss69O2r70ufOtSLyytJiCBkenQadmG9pVJSkR6VcKv3TMi0uX9hsLsUEfaj8DK
            1bK/To26LPhDIa7R0opotfwtsRZrBJAGk2ovixy9pTcJQziSq2jilScfvb/0SIQz
            dFX3VoCJxuoKQ3cowwQ7f5D2Kuyr6WePSoXCLUHJIXfVeQpm1398jYwdAgrEaiom
            LfvwqiT2d/gL9mu1TvIcH3ZnJii3/spt03NpOJU773nYLWAptPI2OG3ChZkyaWga
            1720pgu2L9h6G+R5hIpRE/HJ3nKLZ4IzGmtCsLp3Nja+VmfISRbnAie2Fsq2bvRr
            qLPKgf9jGhpg7elS/BsG2eP/HweqRANCQiDgn5136f38+LrjzRwBkPP9NHDjHkau
            VD/wyo/e4k2TX8OFpRR+ddOZkPp5ZSHhKnZQm4djnf0ytB//CPLolaC6FScH8dSu
            Qi6U5mHEL0Mkk96BupVLL4jQGlWFaUAKL51RVseGsRnPUtLDQU8aoFpcFApaXnXS
            XAFMYTliS/cbrJZJzGFeNCX+DT/KrfY4OY/eqISAJLW7U+TvP9PiE5U25fcRolbN
            QInWKgif5neC5fLotk7EYH78qX8pCX9YvF7g0xnfyvXTCpD1lrRrO+UfRYPz
            =Oxce
            -----END PGP MESSAGE-----
          fp: 04DAFCD9470A962A2F272984E5EB0DA32F3372AC
        - created_at: "2026-04-21T07:55:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwSHi8yuDIZWAQ/9HEPtOFHQkRAJWUZNNXm5LMr15iF2GLtcMXluqM04M5g4
            xFhfC8yT5j6E2bfIqgyOdtgsOoGBbwaf8GxzPLblNdcaw6IB22XMbhv19pmkAZL7
            l7IfnuemxcKrdu9Zq+rZ3YAYC0S0f1s/moUdBnh+nGyw4bzqyF3ZMFx8cJ1nvq+P
            4itO+LXB4JVgzFtFBJ9+fzMzlbOTZ0GnSqYYDIJJ15eBFTGzDXxUoLnmq3ATosl0
            Z4RNrVRgAWWrLadt8GRpql2Du5PpHz+kSTe1qmqChTgB22/P+ZumTMkVcDrRf+WH
            y92sx70wgf2IfpYpkXkmGy2vaVk6/NZpXS71jFMKqMwysCSmsIzbjoJRGAkarf6N
            Iy5RwwcUpcHBX1FgO3fJFdYSfIcRwo/Fk+2hWBKBvFePrgKmivDXAHjX0g5jvGyt
            hAzWBW+9SHa6SyPrL3pxQbjqpINH5kk8Q7hsevXHx8YhPUJsnrJwsI4NGWsS2t7r
            4wJGFyyF6K9Um2h2aM80CPjPleklgFK9kEhZhFZXnc7eZOBAT+c4onhdiJJ54hkv
            sqCcqbftABBygwDN/VtPQzsWF9XSo4DYB2GQYLh1CYuyJU4+fkWtE6a1i3wxRP+t
            CXSYNFaAVydASeP/oYw6ceJoH8PFaMJwDg3RbckSmZLnPvs8Bkoi/Fe2SXxfxSPS
            XAGvQJfdqzkEdxRUaUzLj+bFY9/xTwQ3rJVc0LiLyyCiT2wPYEeqIU79/djMoY1P
            WCP/xyPeDkjHGvr+PL3C6a/dZw9lMg9wGWtAXq6bLfPGZOPEL4bwj6JrNsLc
            =4VHR
            -----END PGP MESSAGE-----
          fp: 8A07D816280A983BBC35E85C280DB66A3E8C012E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.12.1
