apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: perses-encryption-key
  namespace: b4mad-meshtastic-gateway
spec:
  encryptedData:
    encryption-key: AgChe6qdAv/LpB6jCkKd9cG3g4/ImcKDXz0SMBkXxuufIfaSqafnhyuIzM+kyp13hq6UJEEHMIQ7BrTo8h+hMkHxH+OrEz6TcymDIX9+Qg6qK/eoag0sOUckbqPL+NMY3tAX3vrzsu8Y5GnYnNizwlK4U/I8RmgatBCC94XBeCWHpNiUSQZSq07KjKcgXyVCj4kDfnZMbx0sF2kQjfdy2ffk9dArW5xk86eww6FW2QfVcfIccrr6R2EebPMiEhip0f/6U21HfmGbqP6UM7UaIML5vyZ9xiGJqZnX62Yr8CRvg+2RqDf3VMimFa/FEW2ANNKh6aMgovPEIuYDFAyy6FikM/+0YGY4WK4bMk93hrD7axwDHafzLl0hjp1d/VB/gxq7fsJkTDd0hu49f53+TblYGREkd58E3B/d5YWBGgNL/4rz0ADQHcNQXIMcVMI5GFFyHYawTaV3uq8wWIbLnVUFarhJqtIr61r/osz/NH9sAmN1yY9TmXzCdS7kuEA9b/2ciVN1gLSKvdMIS1oo1QJMOeN6gOpt0M4aSpaaFpJO7YUehvFj4gYtuWiIwR7asPrPClEcySxH9AVNF7Noh76regSESerHrs6SlL8P2FdiYjwBU+kfEKkz+VqcwphTgU/r+jLyr8o+M20X1uH6s0T8ni6q3DhvHzIkwEY22zFC+2axP83cY4PMr4limbwvBiZYZ2VyHLVmxSZ6bwTl8qUXPOyW4DV/4WMkKrmQLiGQBw==
  template:
    metadata:
      creationTimestamp: null
      name: perses-encryption-key
      namespace: b4mad-meshtastic-gateway
---
