apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin
    namespace: b4mad-forgejo
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:uIso+MA01n9tKpo=,iv:FceSz3fbaUAQ1V/jBOoVU6SfpGz1g3yU6FyTt/iJ7h0=,tag:4MI2ys3xxAArfmytzPdZJg==,type:str]
    password: ENC[AES256_GCM,data:yZuHFpLQ6+/2QxMsj1Wq0IiELyjXpW8gclm9fxuMwcw=,iv:D75HRlpxvkACh9WAvMiK+N0/B+ODfpIsBRQ57tjpre4=,tag:ajP0PNW5G9DoXZjvBSRosQ==,type:str]
sops:
    lastmodified: "2026-07-27T16:58:01Z"
    mac: ENC[AES256_GCM,data:WOFlxDTeaYVy1v75c7r33U60MVvsxsyI/kQrVZPZZa7ROGAopJiAuFcS3kAKxe8rqhVK3g7u/J8HcXRk15lyjWfs4K3busNDxgqOrHqO6fnrp4YFnc/c6GDWAfk8BqXGDOVyChdAG9xQUmK2IqGENQI7OhitpnD+mxSv1BFBs94=,iv:h2w2bgD1OGFnPzEfwOPiHjHQTdKcwJK00RYZXmac/FY=,tag:CGBenivq67GmF9hp8psCfg==,type:str]
    pgp:
        - created_at: "2026-07-27T16:58:00Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9AgVmznaOk7ARAAtH6bvD77SgUbqMgvXD/8+4UVTWeVkpWXaGAz5N3GtWi1
            WAmxT7KZn7OaKg9wDpRFnNwhYHraskqmCQTfw645SzwQ31UrAStOk4g9ci5swJYy
            0okErA8wdkfnoBGjNQdJck5TGVjH+k4psnldrK0VWSm2aWshWLcQ3uTnW58o+UGv
            KyAHyXuvuJLxQgojvf4s+IvqFcxnkV3HX+S4XL9iDe9+qABHxDTwiNwA7ql1hluw
            U7PCgRnWBGXIxh/090zdGcHmSxVipUoj/Ijtfr9pVECB6VpGo+Yi3q00o+Max+/e
            hcNObhiA00mxcoqGlA2kMis3c1jYA9fDMbhkl268rhwZZlym4BrBN5FBNjRJpGQu
            JAfdZvAvnTKYgRiaX3mwBQGxAgVonQfrAu0AANBVbZTxEbYsKGmgOkvDc9h4tt6h
            UnPHehn+lHUHBV/vogwKY7pYeFhOa7Pt0EQYcOz5NcWTn8K4Ce2Gk1R9B4sYXRF9
            9ydg2jxUZzwtRDX3POSKhcp+NI9QeWRft4coebUKa74XCxGybgcJuxia5W5cEVTz
            NfHvUN+N7HHlZenphZAg7g/8fQQIaZYFQxMkwgkWg055XjIHLsm3qa1k+tWGgaH4
            swTN2dbWCgzunj0bJOgMCT9Vg+YoLhEiYYI20ES5OxDsMP8Hygu+XZl7hFpYe0HS
            XAEsGNsvXBT31G1t3YUJwZ6CTkqzFQUznp2Vwv/7mCEVSZy+6GWmdNY8mq7LmGy+
            NM5mue8eyYhH9z9X/xMUqwPzSvJXvkzu/NCo9BUH/JMOHyviQSrP7p4fXsIi
            =29VV
            -----END PGP MESSAGE-----
          fp: 04DAFCD9470A962A2F272984E5EB0DA32F3372AC
        - created_at: "2026-07-27T16:58:00Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwSHi8yuDIZWAQ//b6+vhKPIEqadgpbj1HnPJckOPmnGYXuYeVHqMAHPu4Sx
            tvtAPN2IyDUtxGcA6ixpdIR1+YZM1dK5tOPqtb5hEPX7cQ5yX+eUBB6KTCIhXvTn
            erS4QYqMFfH7Tvw+EBFTC+OJi2Y8pqrmcUSzGot3bxlWV7hQdsDbcVu2AQavMtqs
            PtVk5i+aVlLB3IO00WU6XsBSzYWEJ5GfhPNokuYOkU45DhmDx03bfbOQlQfMl+K2
            JN1qInrQFf9OrTQN/emdvAubqCn1jZgjPrpQYKBs9ayM0z1LfuQt6tYhwL1e/Wv1
            jQgZJqnW9ZnPIOhNekIjGBtzgN3nLVmKihfLq3oAgynO49zu9LpxEgaAQ4SBnk58
            QJtSZHqtFsn6xG6sZ60e0NZQVnex4w004GQ1WAR83n4jlxsoTxFycugNghQy/HZo
            BUck7QInpCN96jn11cEc5Y8FqPOwx1u3L40lSeB690hlG/xTxUOAUERVuo43sxhA
            GDgJ52pfrbjSoGqd8D40uk3sB8Z9y2t4RbQKF0WVfrAKFJZtkcoT1N8LumEYigdv
            fBd+lU2Fxu8ub38Sizuxd/4reoM96HexgkdFXBrWAJSb3rkqsOyRIkyT/EDZfFGR
            13VwTQ4FnfH+sy3UgX8oLPSM+KKdN0WtcpJg8NpWegXIbiEeF37i7Q3DRkelS+3S
            XAFXUn4ur73X/MyXH80Uv7SdlLJyqrJXI5EfOcMmFTNbIwlvj56VY8X2UbR2SD9R
            f/R3TtYqBCsxL1IEIMWtBZzHmcD00dkGXs0t+80oUOnkyD2O3lgBqy6bb4+p
            =phio
            -----END PGP MESSAGE-----
          fp: 8A07D816280A983BBC35E85C280DB66A3E8C012E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.12.1
