apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-admin
  namespace: b4mad-forgejo
spec:
  encryptedData:
    password: AgAnFY/yKd3ukA29PqS61zjkirkGoWOkduazwcnrOHVaQb3IxZlH64colEXDWAPsl+8FVSOPdPiu0FTsZ5K2i7VyfxWSUK7qEQIHMSwfQBEY71Q6tvS8MDwSTpkv0jK7VdYV6BFHksM8Fp9Mcz4jwxNSS9WVvi37tlb5Vrm03iOns9eo0tedQIdtlQVDdfyGlC+t0PlnXElNPkidHQ+NkDlvMKMyNp+0GQ7vF9+/sZZtJ2t84/WPFpgjNyJNfsaWLufcYNAsAdYkMlPgPT+qlFuEb8M80u6jNre6rXFduAUQ1gpxA764p6lSDAzMzAsWz6rKrIVkF2YliLa4Ul119eDebWqu5SEbCA1BycYv6N4ffoUiHbdoPAigX4GNSJNpDjxK97mKY6U0+HoiYpwQU1J5+ngEjXGBsSY6rGkEOaERar0qReNnyCnO2s7CFZZr5BxMfXebuUL6vOjA8SGg0439SdglkaeBUU3MM0z9z+wjbER2iSXAlimfTGngDs7SDsyKqNIUCV4kj1HqbW8GBTA9oqWhCWWKEai2wJwSEl7AExTTfWU9Nq8RkkW5JYXERBG7WH1ZJX6Dm4cNnhH0fD/c+z0kgNEaGh1Nm/TxaD6FHjlzZm/ceagio9aqMwD3t9jpMb7medo1CMyHB7ybg4ekl6mM0rELs1tSHCKnEkrnY/g7BN8AzFUEHme0IcHHLGZz1eFW1HWFZp49QeXZvhSYo4kU3V8e9INnly3LOMXD+w==
    username: AgC1mu90DVQc/yDYwoheVoXtcyF4TWFiGzFfylFLQB5eUKoEr47KiI/g79z0G03ufX3utHNpJipaqeahKIAnR7JAjX9syH1T9C9xPpSgKJFYPDXH8Z/lhoY0/Kw5KuXjXqnJ6YQ4uvUKGI53BiLDoJ+H2LjWnWLQaVq6oSEMfEvyjAWT3xYiNw+L4YG21ULEfZEGnp2LF8naqBLjmJvmVIgYs+OB3AEpviAJ3vQyx2IzjR102qdh82S+B6NQS88gm0G42v+wQjvrAmAR4niMP+m79Jm0Io6iY3U2grRJon8YGArPrljB3wjitO4g67jntZeQEPEbSKrE6sdhwj0xNOlxWkK2Sr5YyU7UFtsNMdAGEq5b5/R80ngDTjm28c5Rva8SJQqchlocvSWpJj9O7G01voGuDI48TXMJA+RIE8hqhuQ9RBeYkEQ8nNXLXQGt5dUzTWa2ClTWbjQwYGUhlFUkoSSdUsBfOjXfDkuzU4c5tj3VYSrriSbP9OtZ54uWFEhM7dPx4iEj/Ecq2rEqEeEq9rN/2BqpjK960BKSoSGy5NfNh+ZHZW9SiHIeBdC52iM9NMYbquCTCnkLv9pQZEExD8aKg+UEEI2O7PHR5ZOg3I4IHs8Ru3OCrxQRqmjAjX/qOaWWdhzUXoraLsqapsf6nypI6OSgWzXp/kwxQgCoiChmaeqFwjAYLQCWnC1XITlCRGAV0NBXaO3DFw==
  template:
    metadata:
      creationTimestamp: null
      name: forgejo-admin
      namespace: b4mad-forgejo
    type: Opaque
---
