apiVersion: v1
kind: Secret
metadata:
    name: aws-creds
    namespace: b4mad-forgejo
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:e59xXeqb7x/JPW6mAWKVa5O3yuA=,iv:fU2BNTUjI/Wsd3nOQoX7XrbHpZlKyF+MGkBKt6IjraE=,tag:bDy6YkjU/tSRMyi6hIj3ag==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:IEz40cBX0d9eXsyvPoiqOxdwFOvgD9aT4don4mIiLcOvYfbwRBmRBw==,iv:H337aijrBzQmGPPpQ3KWHG2oqhfRRVLHlhs3sZuPo48=,tag:QaIDc1z3lC4rMHw0yHoPZA==,type:str]
    url: ENC[AES256_GCM,data:2Csk+UXHTDJMIfePL7bwf4U1MZOvRXDW0aqlpPwVC1R1,iv:LMinx29btgK65BmBAMLOzQGqlYDmmZN/4sd0TSpszD8=,tag:AR0ecayUv1HVXDxN4clg0g==,type:str]
sops:
    lastmodified: "2026-07-27T16:57:58Z"
    mac: ENC[AES256_GCM,data:nW2oCoRvklGNjygYIyZpOuZ7Qborx8Yj3fVhM109C+eCXwbm1bT0vYmWbm5Udt5jck4sDboW2zuwCmify4t3FatYYxCGTPOC1JDUWUNJZlkMnn4n1i1lDgUrPnuzj+yQFZfoO6+Mb2sxm0ofPeAWE+5VhnenrKTw/cBJ5VgSfz8=,iv:qHwvO+r2AV5vv50uOESrv2zgwY5Pio3d+MvHAXau3bU=,tag:N9MMyWgGVYlyaZehBHUFEA==,type:str]
    pgp:
        - created_at: "2026-07-27T16:57:57Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9AgVmznaOk7AQ//dp0xv2HEAXyUwMviTJ/+5bde5hvxQOS6Ep2BZPOTk8ZZ
            GgJ7Ov3GTYw1cUyUfvgIWICbSxH/MKW23NGgS1XNeCYOlaGj1BhOzUbPUfJubRYf
            CTsn8b/TO//QVPrTtL+r13HoZsp7hnZsSnR619jUOqBwgfivcFTHuyJbGMW7eXui
            AXQ/LVVYmlklhhV2oq8b2X2NUYCJfLsK877FyWc/GbXRV3SxawYt7U4w/dzuLBhI
            4f9Gp1WKvUABXdbmDs3ITjjINhqOMOFfL0O/tdsQQFs3I0v5aXDHBe3iIbQGrLb4
            QiKjQneEHxYOubr8/Kb3mRXuv725MG3lt2NbbqlBQy19Cj4TjihPX7cRw7145xA7
            eVcmUyNoC0XOcT7UJKQU0wjIf3I3fDjZAL8fFIa4XDJ+X3fW5pdNUdzNhaLXD+ct
            Sb6/ObzxIydH2ztv2N4v18tFerv5KHAzt5mxPd7Vi4Lbz2EUaklhkarmOCL1RxKJ
            r45gx42r9wxpGt4esFse1UbY6bf98M9hx6x5zvgj2Km0/BHdNZ8qlWQ/7jK0yDxK
            JlMwA9iXbxD5uPOzSUZ4SwduLQxw6O5cJ/ErKbvnfe341jBB+KlOp93xmqQoWMQR
            wqZvf7iSF4w5dT6LVPkNrXluqDcVVuXSQTV4tqeiXmslnuu4fh/EpCeSycTuUPrS
            XgEZPCUtIDB6IYNAS5nfN8/ABeiKqxs3n0llkxdov9+O/faAsiVADtqDOydjcsNc
            cDdwDJyMfMm3Fu64pJ0uAZjWr6DBLFsWnErbidimvTDHCck1HbJeChjqR1aFlzs=
            =/ZMQ
            -----END PGP MESSAGE-----
          fp: 04DAFCD9470A962A2F272984E5EB0DA32F3372AC
        - created_at: "2026-07-27T16:57:57Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwSHi8yuDIZWARAAqYZiaWzeVEmWNgsVHmzCxNwronHP3nRBRCPkSnAkM1Mm
            HOvi6eGkGpNBVAqrd6sZV7bRVFnJO5wegJm7Ji2Vl+ch+QRFoeueg5huwFTEJgBo
            aNphw+TaT8QQzqpb980p9fe9Kp8CRbaU5HBnuKPrluthQ7e2e4OgamKzk+JxPQ3x
            qjuNV0rwTn3vOEeCfArwUTV2Y86sXcFofXAtmIyx/aKlPCTicHsIhcNaq2BCfBiK
            BuCqIS/+vpGwxBdZh4d/BdrLgpUwqqj/ed2iLXgLW+sPFF8xJvOHrxxivHQPI07v
            s5mKL5NzNYUrmVUBsETGw0SKigyF4vte6vYgxNvi7SLVLFgfIYcN4/4WI7Rze8vK
            CIF09+fQU46BTs8fcpOg0+foiR0VjfBy4S8x8+3abV5LghUsLpazOUx1zjaK12JE
            iO2pMeD7frIrhkpW6M/VBYGgaS5aEJx0PnOEWE/zp4ofqlywed1GdqxuqHZCtrIJ
            e6BcJEvZdMdNOsAyCBbJb1f6DXhiIgGQL++V3Dk0NjtWszzkz44GY6GSGu3R96pO
            Q0xdxSVLPjcgUZ0KRmiNbUWx04Aq6RLkuZX70lb71MMkHkGHZsbx2NqfXaz6tw3f
            ZJfesRqHVGGkFlCqgtCbWPThc6ZBkX+9tVprDdbbvHemvbhy2qWUCmyZrDEFWzHS
            XgEy2SJeM+Vtnt8H9LqoKaa6aHV4AIINXTOgDGA8LoK/b0Qx/yKY6j6NY86zpgiW
            opBUrUF94ibTZcDN4oMmTK+ahfHGLE0bBO+ujx0ahVuIvHerTc0qGfyampr4T+E=
            =1+8R
            -----END PGP MESSAGE-----
          fp: 8A07D816280A983BBC35E85C280DB66A3E8C012E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.12.1
