apiVersion: v1
kind: Secret
metadata:
    name: forgejo-mailer
    namespace: b4mad-forgejo
type: Opaque
stringData:
    #ENC[AES256_GCM,data:FFh2QwRbpQkwYXlHExBaAt5DEbGjO/fsJA89oyU9ftNX5CYxtjRN0eEvv7Jnm2gbaYHx5c7msmbKZ5pUifTpXVM41pHdxyLL,iv:AQjpYid1R8yf3oLN2U5M2QnR7DQSrtPUq3tSuoyGtiU=,tag:LpN63trsNcpg56lhaW80CQ==,type:comment]
    #ENC[AES256_GCM,data:fNnShs79LetLxQSLrESi3NGhVGxcQwm9KBG4z1AZx5SL2AFkfJkA4FxderIjNWukpC3OL67u6+r9toISQH27Pd8FQWS6bh46,iv:WE1HbQLXLmx6sWt8TIN7YvXb5A6aby/S3z3L6hx5Ki0=,tag:TMCLJ+dkpymHyroHl309WA==,type:comment]
    #ENC[AES256_GCM,data:2+t2Wmav5JsLR49l5DErKmFauAgWSVCrJoIG+KfmnajS9GvkOCLuiCVmosihVnB8815snLYF7Sh6Rn+D4sdh/4yLWpxmfyvPHqM=,iv:H1flBHcjLALPH1it14g0J7I62POaWNzJrKvKDzKZCAA=,tag:atjghSwjXmkA7bu0SAMxiA==,type:comment]
    #ENC[AES256_GCM,data:rFMx7e9p1NcLx0mrXFCEnryGKEhxUd7jXbT5qV8m6iHZ7Idd9jEOwqrs7rjOAGxtaE2TI0WOJclBCybhQ6lrq6xnRFj/zAIxvUU=,iv:1w1dCUdyovZ48wEStGbr2mCPo/CJHWx8dPZ7qVptbm8=,tag:Y2As374+wwcldxIS2arxhQ==,type:comment]
    #ENC[AES256_GCM,data:08tNPNcELAFL0J7Z2M0inudfzLdleQ+KzzGqObeLt18Iie5dubN9lGozvYU9cmAxwm8TXkG5L+N2qSwJicgnQczcwtFzyKs=,iv:jJUIWekCbVIG1qomdfhJqOzdZtmN1y4+dwiDbzrYkN4=,tag:VcISOdD2H7QPrMa5BHvfNw==,type:comment]
    #ENC[AES256_GCM,data:dh0BFqu87j5ato1L4PdA0Bsl2aQzyi9ckmVF0LAkxwt01zbRV962FMruIFdi5vlq1qQw66iZzjqMAcsR5MoFZza6Qq3mBw==,iv:g+tOiVvxp3/leaDiJC4jPYJwHzcY1sa9Odx7MzlGxO4=,tag:T01GQv138vfXj+jdpijWqQ==,type:comment]
    #ENC[AES256_GCM,data:Zf/eYXxkJE4Y0REDrTXE8Fc3NBGskmoeLXsZ2PlDDHmrrVX6ky78W6pG8rHko6VSyGXjuUpnW8uIuQx2OcO51NbUIrNq2IqKvNPOgwK4EA==,iv:ClEHf4d0wDT4Idi5OvxknX1NFUSBdkVudKnPmzDziWM=,tag:NAf/VTaNHfqYJaLDJZvfEg==,type:comment]
    #ENC[AES256_GCM,data:3iTzS+PvqFblEpldw7zUuHf9qxonsmwbgbZbTSO0Z64peHCohg2YqMB/+ivMRyNJGXk7SpP24A==,iv:uneC4glNWOPFlZ1pzTADpzOIaT3BsbfGwctkqjmpHN0=,tag:2CcNPTymSukT3B8FGtiz7g==,type:comment]
    mailer: ENC[AES256_GCM,data:9GDbOM03/AdmPlcfjGwfSowP6GfXqWFTtBmoAIndQhH0CQ/PXecsx6mthxFaCadbv2EURU19SAWlUPYR4RDecNAaTm2UcpqJnIysMh4F30csAXRQ6L/6EEFPggzZ0m1Dw9lkxVx00ziTIYbDkp/+4hAqRAezO+1r9gveUV0IjIMON8d1jPqg23gahuOxWTfbYdfQBW7mDXlG3NNBn/CNhRe8k0lW02JzkEX7sOZ7P6Y1qFeMqelJJiKRb5j2P5b8YWc=,iv:t9I1UXd4+xjwg0WnKfpDyQMEvbMS9z6j0E/nk2t7vrw=,tag:yUvA1J9uKuwvasGt1Rnbpw==,type:str]
sops:
    lastmodified: "2026-07-30T09:33:47Z"
    mac: ENC[AES256_GCM,data:xZB9YiiWjvtuGT1htvi6VVt57mO01DaJrm9nxlMM0ZWjkuHfLS+IxlrBIPJ7cIumYzg6z8uY3VILC31kkYe6tfrd8iab5lut/kuAd9pEyx39C+g4K7ytpoWhX6aeLhJjJd2aLoNG/GoJt1gmNvXCxpA/sanx/3CKXbD402kdyJ0=,iv:++pJBn5szLHnBspM8IzwGJZmvy/gblKWPb2pWNyQGw8=,tag:FNt0nZvcB5XR6JEHWV/DEw==,type:str]
    pgp:
        - created_at: "2026-07-30T09:33:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9AgVmznaOk7AQ//T32d1dvgi+JJouoDH/tb4SPR6rfLJzH5Dfpq5sb2G8vB
            8FYBm+TuDLuuQpGZUl6XTWqpVA51qn97Yl4gnEQoqx1iB17x9Z5xAGhqibJXT+VK
            R21DWj5v7HZRJWomeKRbAZNaUab0V4D96lC1Hwk3UhIQyeeom2vOCUnQHY3PAkes
            tdiFbjWSiijPYPLlfXNa7UqSLN0ITP/LAv5B1kFNZ0Q2n7hVO2yN2duFLzsUbcUC
            MQmHwcyxMHRVUJ+SIZEe/jGzgjBFYBWxjAZIRbSWV4IUZg1w9xWsK7EGXrHNgNAr
            U1tTXEF9W1vBE8ZYgoi3RI6cBnoYAieOgInJS+ZF4/ziz+VbJfARwP16xC/uSWZk
            2Z4z/C09hfhfgYQVUeWJebmhMzAb2SRKowp4HYN7aMs7Z94y9qxyx429QZvDpvJ0
            GFLnFcWmq8lgBh8X66SLvxXsUtAR01zdZ3BQqzEgS/jGOrcAR/TJTRzdb8cU7HVA
            bUvbRtxN+EAuZKvUGANGaHtaF9TwRo7yF39+JXh9WnT4OlT7y6xwG2z+tYNySBZG
            rXbhHwt2r4b/AzaMIfQCc6yVHlhO6OPSgRhCM62Q25KJlTKx0ITYMYNe32johuXz
            IAAHF1UY4TLEQBea7j9oPpCK3JWwNVaKqZdLcKfNcLXcMuFatcZSk9lJhnYicErS
            XgGJEIxq1aPptaSNjCluLW+m6KuwzAIk7f/GJzkwtEFbXCeNdYCMZs5DPXP0uEnl
            vEKo3ulOZ0NeOW4Xvq2t0nGDk63BIaJO31SrBRaxw8YEysIN3mqinUQZcDiyurY=
            =3xpA
            -----END PGP MESSAGE-----
          fp: 04DAFCD9470A962A2F272984E5EB0DA32F3372AC
        - created_at: "2026-07-30T09:33:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwSHi8yuDIZWARAAq/aOg8zQ5KrcebrBdwjGJIgy0OMiBMTUXDvJ5WctpP2Y
            thxHGAJjPVAx3auxWZs+j9E1hBqB6iavYNDobARk9mKL2bw4z1Py6SLD0Ki1T22d
            KNFfvf6bEj7eDPO35FLWKuKGRkvlIHZmvBvychqYM/xtOgWmGZYMVjPSAri7Aef1
            A9s11IYg6M34hMww6fo7zHIpRryYo2CIre/w4ctC2oRPaYw8VwpZsn1nDw9zLiJt
            RUxOZDLKCy8+JI4LZu/p94/43q9hWvio2FveUTUSz0KuZ1R2U8LaFRIYuVbEKD5l
            SnQuNaYe5RnW0vgwVU0P4TCNbtfM12aY5DNOoslZp4gvYb61wlv6R/ecZ880ZGzx
            3IjMuQBiRB+WJ8sh9wQPHqaterSC0e6tpedw4uv2FR01MEStcM9w4WN++Uiy4sQh
            cAvHZBNIL0DIemuMd/IP3cUxVhEx/v8T2Wvpm8TywmIiT9cQrDjKgfYFcQ2HLPFJ
            L5t+vkI/R4Q8+qMIT4uu50qXrc6TVt+/b7XBDcpRvmZ6u1FgEU7bqCE8uC4qYihU
            JHpBZpBaU7QNeAmVu0DX6zwbYBpWfPlJynGG1bFEVulaoZ86BjN+n5OcOaGzgK+f
            h5wlhporV+5ZBUOx2YDBgZRM5VWG8wi44WYLp4ztdU8aTXxfU1T1eIZKNrsG8svS
            XgGOZMpu5uWfKXkaBpEtF3UcQinJliffEGT7lzZL1+Tb1KuV+Epy5jmnmkD2S3RA
            sU/FTTysROKRQOr8tL+QSvn5xbrPkqMRZL0KBXij6ZyzmsCqOSwY9P3CH1ZnBII=
            =wgPu
            -----END PGP MESSAGE-----
          fp: 8A07D816280A983BBC35E85C280DB66A3E8C012E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.12.1
