apiVersion: v1
kind: Secret
metadata:
    name: forgejo-gpg-signing-key
type: Opaque
stringData:
    privateKey: ENC[AES256_GCM,data:y3zkwkP2qQQYBun+3etYyBVH8LejRFzcCL8cDCK8XOXBxzjQBMRgR056huSrG5dyweqdL6b1wOJTbXnQdyqONF5JGZmoVxMsBxQ9s2XSmqcphOgLuSZx1c6F0BGqfh0aXUW8E3RTxUZ4ORs0h5uqmMNHTnKx19qqypw5lLxetROwUFX8Yt9S4mo66kqHnDQqY52gRoXfAmM/4DLS/osCeQ/3F2V3Do6vQIBo8NDLggnl+QewhRbZE8/Pl9cgSYiSvHPDhx7z74lrCfUSxf6X8fR3/KT120xDPYdGbqQ30+x5NKQLmlYvAwcI7OjpWP/xqlQrhxs5nFv4LdRGiESK+fA4O0EdYc32OcwR2pIzOYbhrnyz9QUPsBezjBiDLA5C57EIpN8ERq9uPTRt42TYH+90tgLfdsCZZllWx1s2PTdR93ePDN+81ODx15sdYcxKnXCZLXgIimyrCWbFUv/aOtO9V8hHQYTqsBXKEMf8VgvWBQu0pADoCw25m8zjXGDS/oyQfhYl483HCC1BvyL/OJnw1hdy1J4RSqPzQBRN3tS8344mbbLDL2jURBGZ8FWAl86LW8koD2RWYSMj5FiMEsVGSxDBha+P6JINeWSbmfZtyQUSAZwR7F4sN95DAZ8GJjvh9BX75FeD7YZaIH6uvB8ZooCqYh/UQ1KR8UpD80QpyxVON1OLVZEJwI/BRzotoBK0pWpiyFj8asULCmgrvRDU7Z86fbt2q3j5WU+qS7BC6HY7kRCNk85UMRiI3Opw3KRRQHRulgj/cYo48+Zh4pUpGz6ceXdm2GJdCt3nk7kqt/EomBL50BKRnIWBybcZYoPYEy9tP18GtolZ7N0wer94WgdAx0C4eWhssI6f2csFIKeAw5F5bdMtCTJzNfuXF+neVN+JCdCF0zoZSq9Gai7ecz+viBsnRZNOPEWvHYG3VaQ+5kDbtGmgMgmvZ9/b0QqeXD35qtqX+qJF4iZ/27Wv1TcVrJK+PZa0lJGfb03XdqimMl/gTr3n2Qg8AAvMOcdrUHQRJM8wQ8mjwgQNmg==,iv:1YzSKLnft7ChHd218JBluaKFdAkBP2yePey9R5tFkKE=,tag:+meMmKRYaFofciOAulrHkQ==,type:str]
sops:
    lastmodified: "2026-07-23T19:09:03Z"
    mac: ENC[AES256_GCM,data:hPIz7TuZJhFQV52l0rQKMR/jkTiJnoQyf2RC76dTKKcm/x5wN1zDMoNiUBp1SKp6swrUG8RMjT5ROznvr2pSA9A1xZpYNTO4PAw43jLMQWk+LAnuM5cCdqqdmK7vuY4NXOXm22HrL5+s926weVKI3uepjZhpF7S1fYD8tc8uzj8=,iv:1Lp+Jf6Ndx4738nlIqdDbxJw0VQog8PFsqf8hB+A18k=,tag:iXHxDnpqdDZnImDoeWKZxA==,type:str]
    pgp:
        - created_at: "2026-07-24T16:43:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9AgVmznaOk7AQ/+McyigeymHQhVLsByo+tf66NpGkkROqY5lgxkXAbpqlpP
            k9xmoHkufncW60bI/wSJmPp3FEjoBpNRHrwT01zm/M24uYLpHt2Vvyz+WHSk1j8/
            Ywnpf8v8oPQWQcAycCf7Y1QVc7Ah0bLnurfbm5syrfMm+s++nA6kitilU5JqHW1C
            UyZDC/Rb4UWhPV7toWupqp3avfWOFaMl8Eo+zmJjLdEsN4IRRXDkDkbZYW9RHwPy
            LMzIitus63laUDRz66AzJDoabvGatNM9Frcw10mkqUpJsNwoDWDu0kdsJDdgpbUx
            LU4nWiCBlUwU6iDkVmXdldOEkM2gJQCvBDiyWAkfoU95D4C1Z5Rjw/bn8jPlbGae
            MoTAmCc/xN1lCOvV5axaNQ8fxsBshRT9BF4YnwMhWTeWQ6wrOBRoMF76MpamCsbw
            We8WoRPxaLclTJPvP0R9aaGW3a41YKoDbrw5zegP97g2nEw6d0twaPZuivgL9ZX8
            wZejRCS1LIARw7/q6vRcrgFnQpfzeI8RZrjxBzCI5CHSxy14WhtvrjN4nfgHzZuO
            1mjpkzQqd8NTTpzehtZfhQbc4he6n5DWVA2yca3gW8Tcz+5SiJKlTre82u90gA1O
            86UCLY6jKE7mrxXHu9LFMhe916nrUJZyxGUXZZxEGmjAMuUOLO2YiSx474jb4enS
            XAEnuj1EXhuPcp70MlthdL/k33xBWh5gOgJ9t+xwl/vMChFK6PKmDoiyZHhyJPDN
            zp5Rt94sHCYDs9Yhv9S6Mo69M2O7dxjCbE9lPvUfY4Lh6vJ8f2E7Nz1lRxJu
            =qGS8
            -----END PGP MESSAGE-----
          fp: 04DAFCD9470A962A2F272984E5EB0DA32F3372AC
        - created_at: "2026-07-24T16:43:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwSHi8yuDIZWARAAieuP+WFgy6FjE2VtFilIdGOTXjbzqsO6h8PZwOERVU0j
            OCuGSYU74/BHdPu+GrYihtJrCbeyIv6lPmusbQcR1PX6p2BdddtNWtmxlYO2I+zu
            APwVDM+2u8ylwpa9+d96nMkMqMVHijmrUViGsoPX38zFBxOOB/aXkCTR422dt8nG
            QxTKo5op1k6yDf8ZCMoMwMDBFmK0wtQY7hB8lXx6+3/BPc5B2O81gy0J1ioThUCM
            sDh/PhUtEWCJYV8ZkyUMYWxGZwRcR3rYOPToN68JY8/A0X7utHBYPfw2EAnnrKJH
            46h9pYeemOcsL7h/5iMtykPBzsVsH9LpD/av46EIo4mgCmOOEjLIfPPDmXxEAUx/
            sv2ZlUA1H7sBRu+/eZimUPGxY/JHdTd2BrqBTRna3QaV0a+OZiRbLdd+mIc2yRfy
            nrUPJqyYtEzlbpXH4Lcv4//8WKpck7j7ObDlrmjYV+WR56MZuMqrDPpJsK4+3Yji
            Fq/mdefHE17pbgcDPb5UaneEDfwQYHjyQPcr7FnqcnrE376gEIz/8XOnl3VBTgXj
            Yh0Wx1vBeqKXU+yDaOs+rw//I+/IfmXwGy5Z2R7wRxIprea4XwO21nR4iyK7EF3j
            cQ1E3Ta25SCReSMq+ZuhEhpiwa30n+moLTOPOLU6m+/xvA3HtLtUMQYbo9thIHDS
            XAEQdzHxVS5Dmr4gWxaNkLZAZfaK/temkdtewXiRVim85pWQPltQF6YkMf1mWo6d
            9Y3U2Rta/6fRNLtP5k5g+s8bqV1pKoV9UsBh8NNU8nHglqi42RX8cQbk5N1U
            =PENk
            -----END PGP MESSAGE-----
          fp: 8A07D816280A983BBC35E85C280DB66A3E8C012E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.12.1
