apiVersion: v1
kind: Secret
metadata:
    name: forgejo-bot-tokens
type: Opaque
stringData:
    renovate-token: ENC[AES256_GCM,data:4EiqW3nkoHXJeIRbelCFmWEvzMJfvnv1XBH9f2YxEThczpjaEI7kVQ==,iv:siHCx44Uaj6AkiyS7PFZsUSmpjs4PXy6wrGkwBZWaQU=,tag:4b739COujjsH9vMVmsUHjw==,type:str]
    gitops-token: ENC[AES256_GCM,data:IIdLP4PhJONF5qdAjbhIQfuDQUbc0kZazfbG2oB58jPhKcn3TlJdrg==,iv:Z6BEbcLdzbcz+FPRh6jrVn7NBenj/5Fed3K9A+cV5xg=,tag:vFlbuDpYqJcFC2jrvpKkUg==,type:str]
    castra-token: ENC[AES256_GCM,data:HVw3JOHmOw1oyquE4fAzKJoMlhNUWqWlZcI+Try/SUYBkzABLMxzeA==,iv:nDU7q+wW7woKikZ6qI0BWLXhcEwl4PZvdC0NuyXlF0A=,tag:AlBLorQj6ByTX/T1kPSh5Q==,type:str]
    release-bot-token: ENC[AES256_GCM,data:Jg7qAHzPpjPjZqsKGjNHK78bGxVjxux+mhu8Tg5eU3ZBxa6VR9g7Vw==,iv:yFnM5thB8aEX9j1Na59LY48dN81hOgM5FPKUwjZi3n4=,tag:j5bvdv39jhWdLfKQOBm4OQ==,type:str]
sops:
    lastmodified: "2026-07-28T09:46:34Z"
    mac: ENC[AES256_GCM,data:utjBFXfZ6JcTLSh1hqExCGaDBO0rqHECRVwDds0KzjjRDryJMUuTA4e7d9SWU+VONqxure8Z53rT2uWuNl8c7llsWcu+MXVwKsUqcYZjfUPZd464mwEMF4BzfRyzU5uKatP2+yq8zoHPpmypn52EHNSdqi9w4R9YklbnwIf1O4w=,iv:n/lCluI5po0fYMOdVGaT/qryZU4H0wgCrd9DnPzWcIA=,tag:Y90L9N83EJNjUh8kmN857A==,type:str]
    pgp:
        - created_at: "2026-07-28T08:45:22Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9AgVmznaOk7AQ//fE4ORtXlPefixOhUkI7MRcAFtVTOAk1Lhz2KxLq96jFV
            ON8u1Y4rXEUuu/d6NHP0HmXIP1LDeWm83kcnSInso19HrXng5J0RhyO1oih47KqQ
            ZBtT3wrOkaNCX5YsdAZJZq9v2AOxecaPYZPaGB3o+M3UG6AUqubzQP4S7Xt4KM7Y
            7GiT6mYNb/OGhJmqLK8a/c5RRwe2WtVKV4MrBTnZSA+mtHHEkoXrFB+WdPnzpF3e
            C+7x1Z9v5UsxRhxBhVwUcz0GR2obPIWOtg1fg0TUdlNqZi+ey2oINx0Ci7JS0ooX
            m5FONfUb2UnEgYjnVYIBD2OPGJSxoYrMkNt33qUKJZsBUbRhiEYOU9d5h08AMqFV
            rZScwWUpTMnbwOEBxoCxoqbA8zHct5l7uR1DOlSNpEpQxUKDIafOaO19Cz4VczRd
            2AOT3rbPy46s4A9WnTywFR9CU60SyAf5GKo1JIijWa021bzlLHALEVdEch5IwDpq
            WrEOMG3S009igMg8NIB93pv/FNfeWqa3h79a6WiwSWxyZb85kbuoNyvjYSJar4aq
            4FvKGYLNH7ScAu7rXvvABhJMKW9ATKP1bwAnegxwXxQBA7TXKL5uxi4A+jN42jPB
            w3DJ4uTIM85ovGYjbS0/hEpdfM8MkscefYwj+YGOEHBPWYmYNwjuP1g8yw+5wcvS
            XgGoYTFmlC42TFtceAooH4LrP3hk7TOuhNpWlj3cU9g5hKlV2NXqNhixhFjHIzJO
            V4vTY54ut73oPzPt35vjU9XKgSl+wvOEeI1ZLzKDW/X7UfpCj7JnvtqsGJYyMiw=
            =+TfF
            -----END PGP MESSAGE-----
          fp: 04DAFCD9470A962A2F272984E5EB0DA32F3372AC
        - created_at: "2026-07-28T08:45:22Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwSHi8yuDIZWAQ//Wz7MLml2cdCBKh/U3dhmkUMnP3jJ3TuyJ3nLcCPGsOk0
            aEnVgzvluv/9EnmXttPMyGcGbrgMYp05iBcvPQ7rLX76gNa7GiCOS85XtVbNgdNg
            cnylIGaWZojyOKRuFvAQXxPhq2s0hQe1V2LvzZldJBbCcxIaHxoCUARL3cN1N3E+
            QFeBjDD/gelYcCqljbRayTTM9hdUuW98FEjMOklkD+od971DEi6k636Y5Qhah0hW
            MgvdKwLdimG1OGs/mEIEk+PXamHtyT9IyvHsBbzHK6IxjvmcqxKGl+xwiIm2qImD
            hrjtLV+HgQUXLUGvbt1cNamFEXK/pH7yJqvrNX8v/sr/VaKtTWAJSzisNr1rj24E
            qd1eO6yI4jQ7ABGkP+DxKdhySJASRF3cnkfbvhh51Fa8/D0VlpCor9a8Ko6vEvfy
            XcHYx8/B91m3uUaBc0nXIPz12gEDlOOtztRgzqvXwf6fjeImPnjBRUEtxAe/+tlk
            xGWZZZ9Jofsl8JjOoaMBbis0Vdw4lmLYSG7fna/ZQXvX8z9u6c2z2nGMxNAx2akH
            gEBkvBQEF+J+jUcawA9pv+lDmWeIlBV1KUjjMmkkqI/ynA770H1yiJiyEh8mTZCx
            zmPgPpDxbSZdPW1Aq8/zGg7FL9Qtr+eFQ5Uc/Dm19LsesDygqpYc9qkQHup9FAvS
            XgHPoR/hbf55gC5ntOJ4YDzCJJxumSe2he51FPbV07lffE+evlS5FhRbR25/KDOu
            KvkxqO/OYIo0yh/gy1d6ef4Iby6cdbdsdKPvGz1DVjcqLgPtk5fi75Zk4biSqwA=
            =tuqz
            -----END PGP MESSAGE-----
          fp: 8A07D816280A983BBC35E85C280DB66A3E8C012E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.12.1
