apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-admin
  namespace: b4mad-forgejo-test
spec:
  encryptedData:
    password: AgBXBfvgJs60iIwKGLceMQA0nJZTH5eoexJVCMm+felPQP4I4P2l9NpIHittB84eadILiiwrK7p9Q/Mvfx3T7vw4C3Cvwu5UT0kUwVUjnk1iCs/wNld3WH4O7Z4uziWLOLbXVvN83WYYtRIB/vdFE170jai/gZq6cn5T83lSuTo7TFrMJlxzlzw/NYFY0N/EbB4G4sbV+LF+kvcFg/hUe1SqVoCoBQVtBJGua9UD9GhGeZsCCS2zJ8RSI1k2iXrk6iWkjnlwj8WeFRUKN/3M7PON5N/XpXX6avLY+Oo2oVu4ZvKZa7NT7KKl1DnkUqJs67/EM9+dCCNjzF4UzpphbA6rvWDdL2jJNgd43tLUAY9OwMRvW8g53Z1sBRFeC6OHb/lT73TBRhIkPIteNMA2Z9D7pSh3tfGa76/VPXDPGkAzDDnMLZnsoNJXbbRUwqI3zDq79VNXG1z51JJxbC8as6rzurIzT0dhq4Fyp+YzpC6G2nOcPUTuur/CdnTeCfc2CPlzmZ7GMi+10o66UoHA5r7xArWRj57VEg11t76eeoJY8XqD2/hwrbzp9nv6rKhCD9bPetDe0RqZx7uTCCLzg7fq7q1bxVJSmLYJwQl4aJPczV4OaqQpyQlh+kOMZT8SVIFVxd7CYMLBhIz+Xr+pn4F7PEADH7Ls1rcTn8DHfpwlW9RamalWL5ZuiXHJhMB9cE0ehaSVfGAj/ZE+K9wuUs+/e9O5zwY94AachwhYuu5DSw==
    username: AgDI1g6IXdKSrb4LFikt7rVo0GKAhmVlhl13eKi2G7Gb4s7i5euxFLaEai3/ZqGUx+kHyfC+tNgBLsr+O9FeeLAvMO8moqWr9NEkEeqQV33ES+LFHEQTM5TJmVhv6kb3TbrMCWdXeUY0AbPM5a+LAFOXD7k8QfzI89mSdmHElaJV8NIg86YXC08rlXyTKB7XGqGsWJR51FJICLtsrJ3h6p2Xd+Qv9CgwI60ViTSatPsDmsp371JS+EdtE/lZm8/d2nX8n1Hr2SeEcdzh7NlCKeStNH+CX0UwNstH7Ntoa/LX77r77gCQo524hEPLotbXj9zJKNyjuIYqYskofvvgw2kXLZRsx1U+rIdbJziwyKcUHiPLf0h4sVoLs8NdbQdA5rWTV7OEYx6tAln//RkHcQcTO8Ddoh3EZ7EtrEy36dBSCAZotO4ietlNHTs8rK6WiqFoouOLdCUQXffcS8u1K0RxsB6LcBZlepFG7I6u2h+fTcOK4oKPfedskegdCDbwZ8gAxjYk1ywJ90Jg18dcFUSyRnYTC7rOpQN0H/roq87g5hA3QX83zUhqA9RPbJAg1cOIDIxXJY3FuWkcyLWH5UWYbBi7V+Av+rQwH6FK0yRczmMJMA3hDpoZHELrd70mxur3rO1M+R3oT4LkhoRboPAso1VZ4WU47LtTlr/xR1ctax3h3dFfOrBUnMUEup5xPxTcW70Ozmodwmc3Rw==
  template:
    metadata:
      creationTimestamp: null
      name: forgejo-admin
      namespace: b4mad-forgejo-test
    type: Opaque
---
