apiVersion: v1
data:
    key: ENC[AES256_GCM,data:2SeSTbvqojC1kPLp,iv:P/H5eILo1zRGGDJhO/hbriPB5nl7H9iFycXGs2HfESg=,tag:TF0eAVGhqf452WI/0KcqvQ==,type:str]
    secret: ENC[AES256_GCM,data:/wDH65p0hWY1OCKlZ7jGnpbyD6wK3yF6qMpMbxzFksQddBA3T6OzYiQyZXU=,iv:eC/aPt6y1+O4blYsHfJ/vaL3apWPd0ZrKnwzXARfqmI=,tag:oGEKvRUU1vWzA0ZjhhBSPA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: forgejo-oauth-secret
sops:
    lastmodified: "2026-07-23T16:47:20Z"
    mac: ENC[AES256_GCM,data:1F8W1fiWBi5MjUNJxGtyTH4XWrLkALdPIFrXj+Z+gat2chMvbffWZTipzVSSN/ZZpNsFdKeel79Xq2j1dYjyTciCreWcjvUYBmnRvuqIe3Ux/JXN5ZTtVrbs730BVOv+4sFqvbq+z802btl307ClfRVWLrOTF9Ir1Ik8IYxN9n8=,iv:gpYc7hds7kpjsNtyYkCNXVtH0LV/CWCUZGMajv6bInU=,tag:7xdZbDxkTG+xqEkHdzg8SQ==,type:str]
    pgp:
        - created_at: "2026-07-24T16:43:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9AgVmznaOk7AQ//VgFQLGzJiwXpHiVx+BL21lT3iIntjyvalSDxq2FNxFXT
            86eD/0+h8c6f6A3JvmV9MU5O3rM2+FYEEnTeqwzNo9XuynVHFAukig38/3HE3Yl/
            WcbUGg9J0tsy60oZAuVJqiAydPrxbBJP/kOd8CyFMEMiuAiwc/4AZIKPK2QInTg6
            sL23vaKl6cS1M51z7mJ8wa6Mj0eLppww3TPZasHdVALVNE684wVrCXI3UW1+oA9S
            TrO1Yl/8VnLVVapCeISeXUTBdWUoqVL9xmtqfzAXEWXZiY//+YLNQ7OSiTTB565X
            mxAnMso+XfiCWFBpRUXRHYyi/9FSMPipPBnLSjN/SjK32WDu+hXJ4MDoh2HDCX4k
            BGSRtGkDKOzKikCbvs6/NawQxucMmgxeSgI+8pKA1DIusdT83Woa4N1npnx3O0zB
            wLJCddMBx7wjBpXpo7wYV+ZrSrnWIZLy5ms+DFNta5DveCTyjdKis3QENBptui4N
            XhnR8RWXXNiE/Yfw24R7+6StqjkmfCztqWXDvm6fdCS3TTC0g9pfLEcXGUHD7klu
            bTpz7Yu4GQxhZjaUpmDuFi8hGUKi8mu3t63N6FhCjinbKOskLuB7jeIRCdj6ipZG
            qyRmenc9SG0MM3MmYRASZvUoRsma6t2zgAKdsMMhHgg0diDlbWCb0u6vWCDoQYLS
            XgGyLjzyIdJM6Mwclp45UJHGmpPb2CVlqpkWYOJeqXHn6mMvqMtvNUT7kcQyFX+d
            761AsRhNuhbQXbp3umAHcpPcyU83y69lxWWPvCC5cblrOnPi3HGiYIIIOqYOFzk=
            =SwMs
            -----END PGP MESSAGE-----
          fp: 04DAFCD9470A962A2F272984E5EB0DA32F3372AC
        - created_at: "2026-07-24T16:43:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwSHi8yuDIZWARAAlAQAzhFAK/wnlefr6AEy9IohbMNRf569IpuweT2t//kR
            ezo1T9dEC0Z8nrLnVzLy3rzvY3T51V5gNLJB5a6qXE2vyqQI1eP3QE5/3PuzOn1x
            JdzFeZj1PAk+eyNMPPMEPYcSW99qo1dWRybgW9DEJ06JLPASSckpfFrFtzJSImbg
            VEXMeIQm6LPBNwLLxLMaz9wJ6aT0QhUHhUbJaj0EHh4z5O0puw9fex8QNel5rdoj
            gcoDXaCw+XzRJHUfRbtkEQfltAo4Oxw8BjDwioXB4/AF8VBX95ZtzMgVf1B5sL1O
            aeLl+5PbaXgYgI8L6I1UE6+SD5H0pQRE+9+Ff+/KrYvCuld7CC1lRtaRdYgC7afi
            HmN2CLWqzPv+87MTy33X0teWejTdasx9FsLdDlCZIhG+V7QQSrFTAyCtjC6Vr31Q
            HHpjHRp6iGI5LXa769IDFPiFKCkqwuOb82mcW8IfO8Mb9Zuh0JQh0fVi2xp71PXZ
            hI4UlfVRPO4XWho/pR9lM+NQVdgiRWFMIEZevABm0HxWvU6RWsqvQX1LDB7+X93N
            QCAN8mjnaZs5olS/LFRZgZIwb4ZaDD0OM+7IJSyEqRmb82IwxGhqsK3Qoh3MA1js
            VnP9AwDx2wyXngtOvhDvjQ56791al/Hz2Z3ATkBflM5XIlQCFCgII5oNR+KEasrS
            XgHIYoQMSxJrVvEAT/OOEaIZzBGpvsMgqD633wXzHZgUejUKYLxvWLYqLXNh667Y
            IWN9W18vtEafUFGqdOTd0wkiwbEdHKhD7mIc/criogy7EL1D78uSfCCSWH3Ul9I=
            =Llyb
            -----END PGP MESSAGE-----
          fp: 8A07D816280A983BBC35E85C280DB66A3E8C012E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.12.1
