apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin
    namespace: b4mad-forgejo-test
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:I1ikVkzsh+/WciQ=,iv:do4fevWyWXKsewPlrp7SAmRxZKS0YuzBCoIfF/dWAs8=,tag:sUG+3/H/9uR3nNhv/yAV0g==,type:str]
    password: ENC[AES256_GCM,data:825r6ypNcSNzOajPnfkinGHsPxJ8lagLNuqr6zYqveQ=,iv:6BcOP5XGoRjWurGeRZPgse0N1+OmBG11Ok2SptVn3jg=,tag:20RHVgYle+pSxN4Y6FZZ8g==,type:str]
sops:
    lastmodified: "2026-07-24T17:07:23Z"
    mac: ENC[AES256_GCM,data:h0E0Trb9hTOyPI7Zy2wWyPp6rjwbfOu6PVUTht64iNuy1poYSFBV9NKJwVetcJonE5MTJra8oHIse631CQvTi59H+3N7U7+3m1An4BKkmXWE4h5lKDvKqA+Gw7SJmdj0NwqmxUYetH1vadzeRzLnK9Ejqr5ZFjr7R4SVTApfRIs=,iv:Lsaoq5sMvzfJkuEx1mKXx7yH4voq9K7BLg++oIJmm+s=,tag:t/HlgtSjlZcpc3VsmngmkQ==,type:str]
    pgp:
        - created_at: "2026-07-24T17:07:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9AgVmznaOk7ARAAli6PodRKjrinZUChwpMl2A8oYvkVP+9z4QIDkCxlFzgo
            CvNoN1f9SYVW9g7d+AwQQt4+DEaPAvO1RbyJk7qfJntpp/FC+ADIHO27xXlu406a
            eJ1pnWgc1Fj2m6Dke3hGyYxzM5ofHvcZBJnJ+uEULw+prRzQN+JSzcjcSMb9WqT4
            i6JTYy6pyB9/6qiy4eAmOHTKldYuPXBYYCJ95DUgSKMtBG/th5xEUUU/95HFXgtd
            Fwc2nuQStMHJpqSLvygn1tKtylIIazpXmzndlmXWYlcJNvbyhTZYfmihU757BIaC
            8dJEBR8HJWXPC6rO2eFTVRuK4CuhqkZH8n6GNGB/z676mZeuAMOdD9Cyu1hcF8+J
            2BvY73jSKlGY6MyOo4TvjO/o+JhOvfXVlv9nCZUBQMtjxmxiSxpXpqc8JrLH7vqt
            SgLzLYqY77QCnluUJhHGPbqRF3oKOMpfLa/ETJVSxIjQ+n3JRHUc2MlYIHPiPa7a
            TOBS/VYQ79KF58wbttnPt2r0gPEmIAtGvLT18YlJgPTJKYf8ydJWYV61MjBpv1Hz
            szXnIHd6atsTOfUp20QXpLW+D2pWAPQXUlakMW0LatNVMar1EQNX7q/bsW07Wvvn
            uufDCxuYcihH3/wo14VHmBDKu8qlRIdPwbIO3DfR64q2ZAGqOw3HTW7KD8kF9IvS
            XAFe+x2YZ4CV6omQrx9U0kkEF1R0kbGCisHBJJH5t7jKuZpLB6cbEaHk/RpZIHNk
            lTTqQ77U6GS0BMI5QLC6Y6i3bqWC9gcKiw8gJ6/tyGrTLCipejSRNongCmAF
            =3JJy
            -----END PGP MESSAGE-----
          fp: 04DAFCD9470A962A2F272984E5EB0DA32F3372AC
        - created_at: "2026-07-24T17:07:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwSHi8yuDIZWARAArzv2uUvhhFykY8k6qg/a4cHnYcI5aCBvI+1g/uC55Xf2
            HWMq7bfsd8XukT/yLfdTkMFqXTS9dwUm0lEc/rtz6dgRw+O6Bs3u2PtltoUyuksR
            OpfSRoKGW449yGLsz75f1POb1jdhui1dpDSefIaL6GJ8hNxjJQV6iqRmocJFr9qQ
            bBqxqzzVlvaXnr39dvya2LS2B4RLphtNdWytCayqrW4gYzgT+ZIbcIpBmQvWYXkd
            +Dn1dEkMmm0jFitd3fNeN4cjYrqMIKmDXhav7nFP6/CxbgBbcA4V57dZQ2K+bia5
            cKQX08uzVaVlXzHIHpA2ElRLYbemxGywaUkCPo9NkTRoxb48kAVWaw5GqPQil3Ok
            dnFgI0THHkJbI7cXT6OfojnIzrs4ViOuDwYQCFb3QO5Z5z8bosxj3bE0l57tLz3J
            vwyE0JuVxE6+tMSRBoTOLGbq+FnwMiLjCQgGiiIdAtW6bAMwKT/UmCsaVkHqgBcX
            Z/ScTyFPDVCGb5NBizKHoNrfpspzaCN6N95nrGn90XR6BYQfkB6e72QqkQJObYWA
            4WuIUl3Yl3F6WrtiCflM1EE0YC8TrF7K8/MabG2uFlr3AJdmOSHEiBGOEW1zqULz
            BXgFXatr9zAiyyS6GJCyC3wJUVSvv259Oa1heWGaItVg9u5UeaKzGigX3mAWPWfS
            XAHHINKLVFkteyHRpPX94ye1qjwxZ9nQ3tAtveLwvR5ltjmsX6mpOFcxjeMagEky
            aKIDIsEFrLrkwLb1xtiFVB+vRwHhlue5cwQdJPZwzURZdGn8MixjpWn6RlRT
            =ZmkO
            -----END PGP MESSAGE-----
          fp: 8A07D816280A983BBC35E85C280DB66A3E8C012E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.12.1
