apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-registry-push
  namespace: b4mad-forgejo
spec:
  encryptedData:
    .dockerconfigjson: AgCmNwO/YavbmT8DrhcIGFUEW0Dd8JqjmWpvVd/hDRjUiC5yA1AT9t3wel9r0lZzdSvy9n5NjHd1gNkoW6oFzk5FJ6i3Lpl+VpkUJ8Ritu/pKADnpRtuIlz8Zvjj4micrNtWR8acdAOiLbWye+welAQ8Wq0ND91GV+wvusL0+vueS5NMpubMDYrWP02X4VwlCJeB/cGHxqrkFVknwPCW4jkYtP370A901sE97VOaPsyvf3YafJ2x9ewI95b5nc9kMZCVjo0EMT1JDCV/HBHnGx5RfB1C94m0BX1RSExLKnJnO6bmyLMhmZouJeAPRC700kEJ5WGFl4owbqGPo2oXJNuZjbbPBtZda/phiNL05CygKHNM7b7VGlHF5GfTxLighQ/5a9Vj2SNSzu0wFFTk3TdSG0BnvNmDiKdCx9NnVbKTZrnlMIQqLSoIj3ONt9N5/UmM3XQtZi0h74/UbO9X2bkPGthJp2Eo7ZdfXPyaZ28TFIUc+GjjFa1q+0yoCFyTA83y5VHHw17q0s7unfaFbAqQ6nXrX2FufIlxOZM6hydFs6W6Tca0LWtQWpMFOYx9ZvPPMzqFzCar4cZTC95YKBl1sUebtpYiQcp2gBQ7IgpjpCmzK77e8lRrC3XjxP4ea5Yb9IzkbLCT6oTxZUO81mROr5Ft08ozqbnhiLe8Yj9lX5yWuOzQRf9tFkQc70dTz6BO70YYoL6jJaYkrsvHpms8gzTt4YKqlT8yJFxTLpBm3lJv8+7cIpYqP/V7Q8rqoLIqteHzG/uIvL7N4jsYiOca7lhNiZ6jeJg45gm2x/YZYV+qEz+xqtdZZQlCdzJk4OS4XB7bcxuYZaCnTA==
  template:
    metadata:
      creationTimestamp: null
      name: forgejo-registry-push
      namespace: b4mad-forgejo
    type: kubernetes.io/dockerconfigjson
---
