apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-mailer
  namespace: b4mad-forgejo
spec:
  encryptedData:
    mailer: AgAw2GrT0+URUr60E0uiJ795p/bDA1bP1BBGMxF9MDDS7fnWd/nmLZx0UX2ZOKinFzrd4Pwz3u/1X19qoRrzKXH6LflQitzlpz+F/TrWuYwZiAT8U0AOuOv7sWxWNpTSr23ngEqg+QyWGnWrhmgwvc7crXSmZMksS1DnbqiVD56iR4QhVCF7JomxFRpaBZ7TKCiaUV6ehWUP+GwHJ8KepIStp2bbHq1eU/6CCe2g9jdJvWglcJV6WyHr3DmHUz64doVKMUnpDg/o+QolGcmU7nZyPYg//QZpAQA+vPRZYUp2ruMuD/DPA5My8PPN4eXsBbsT/Y9WevCS30oF9OuZlIupNK730j/Um/+VXZVN0FhHgk1PULWG9YbHhC9fxyTduaJ3kFCE7bvlgyXLlUElQl58IzZSm5KLN8m+8QTw5BfMBVtbXdIrWg05u1DI525X2tR07QF9JJNfOVoP34jcKOAUJn5DqdBhEZT62MydtiW6tn2EkZYbE1ZIoCo+nPyu0jpnd5bH9+310yjrxEubcWe55kUkll43yx9iS+G66iDNYdPplT0NxCmssALpMTcXE5c60ChcRnH6DEnTYQk5vYIRSJqc39ZNLM2cUD7G2s7q/DhoyVHZHJRG4o5JugUg2DesNPZgj+CGM/JtGZA0e8VlK0rVv+NayjnYwu9lb6ZhlmR0SVmdNFtWQjtaLwzhU/nsJ4uwCt/nsGfFdzxBGh9UBwJyVkUsb5uBKQpYjRcvBK+mUyHytlNwf1MFF5z3HvD+7G8rSaQVbsD09JGpr1HP80wf/eIx55ioDcIrM7zFIrnlQVp8KV0lJ7sv+bItZOUFQRbbsPc2oNKq7dSfUPEEeO++z/EA0TOJY54qo/+3lVsl6WsvxA7i7shb5hzTwgD1Ga3rdRuOeG9hTPUdcRNxwjq7jjrlo4qihd0guwA5OcSM/boXSk61PuIwy55TSFI=
  template:
    metadata:
      creationTimestamp: null
      name: forgejo-mailer
      namespace: b4mad-forgejo
    type: Opaque
---
