apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-mailer
  namespace: b4mad-forgejo
spec:
  encryptedData:
    mailer: AgAdqXTjTTI+a7RuqoO9zPdyEI0hU+m0UV/W32M0d+E5ilZe9sdQBzU1diKFJoxwU+1nYcHTZ2m0nooDXa9CN9j/h7anB1VPUYDMJqfp3W92AS4Z7rQ6hZXyt6P7ViTvRK7+d1W7BD+5ipefdwFemWsYKCL8seAN+EjmZMpNJ6DjVwlrD22vDh9tw5ZKSKXKPD0YKp1JN93qfmEPnPSwMuS7Y7Dg9SSR05dyV+6tufz0fOraNiRQ+rxmynlHIY+2awNpiGrqblHqsp25KcfBmaHtjKht4F0cH634YBY4aZh+LAEWKcaWAceEIJ7l8Q+7w+WnyA/D3Jy2WpcrxUpHSkj6FG3ceEQ+zuN8mmChDyj2p04/cLd35kFtjCAWxWnDOj0pLu9Ocy6QW7bV6TDwi6I22wMkGIEDJUNw2i4MeZZUWlYFME+LeXoTkFVyLk6AdKxbG1okw7ETGlGdFxO5qH5ppWGSxWpeTYU26YHQeti8McUltHe4vLtRgn+ax9erFhS2q0IwnMTkB0GY3DS2UILaJ3SVB1Z/ZVfT8NpmPnuN1QCFCx48iMYFVVxb7BmcDQQpsZ70z9UdqBRgzFxEr4XFMfJ2d8DQ9cgPwAPl7yQqzpaRHLaUk0J5YatpV5ubwtmr6i57yjiAdI2zBUNxIr4PKQcYSizqE6xioWfTE4dlNe7qNEXLIu/y4wqBF24jG6sgnv6zd18jo/bnBtDcPbBLy5OTi//u3+NjYqO5IdIyRn8BoyZv3A34aFoSP9Nxua70fJ8LVBvLumYfYjEQ28+ipDx/ukLJn1bstwg0yLDVF6An49ODxkjRTm2TRccFodM+Xu7MFOK1dvSGYwSOnu2q0RSpVV7H36qIf0ymcCGI+J0X3umTmb9SUm8TVoZog4ghKF/V2rEQUE9saSUG1Z2COaqpI2ZjKkIw8Bma0N1YGn3pUAYgqNqu2kCV/UG/a9fS4g==
  template:
    metadata:
      creationTimestamp: null
      name: forgejo-mailer
      namespace: b4mad-forgejo
    type: Opaque
---
