apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-registry-push
  namespace: b4mad-forgejo-test
spec:
  encryptedData:
    .dockerconfigjson: AgAsupYTWA2lsP/0ivAVtDavuhuWdjV7ciR5E7aboZkE/WcqbyvdX7k1N/xJ5q3NLWm9ha7ZC1UyNajguFONL/1hKI9v0Kg7PkttnOalKVANPCYzyAxHPAQ3TmRhLB9+VItkebvcMBdiLdFjsLEInD08Ltptx1QpvbCXVKt54Eh2qqcu/sxzdC01EbMDLeK9rnFzkxkcvF+iWNjcXs8hNw6YEzPgi9cPPlAikrczdnE4cZRe91eLkXWbMpmLDu1inCKbPPYIySdvbSzD0HGa3CwySZ7fc0cQ6DMMRInEO8TU3RthPKFOVqx+o5bQ43m3o83wpSBI8MqHleZ7HWO6MSGe+HjwER7pLIaFTPGXiM7jqgVmQKYQy/E8IzE+sxjyuVK0jbr2sYMxoCp6FETzmTUjMn4kz+TCMIVo0jGQ/d5j9Sxim2xdOlbUDezTfJF4ImSUvNJIi2zNn4bM9bYd3kTQg9Dk4K/emMbmuc+xCNKkRYIZwINydnu7w1tOJTigr7e1gyVtxLpY/MeVtamFYg2l7LhyvByLOFxofktiuOIF8XpYdshnp6hHzPyObtNzXpAI9RDY5BJYreoH+UJ/O3gSVKQEGvahe5JL2AksjcjjKa2RKDOIxvWXCE6e/NVCmuHIDpCBrYt+0o3XP/aiYvBN57EDoh0mw5opf1WA4n0UL2nyyJc/rYGIwGBD+99aFeDjNmRrJb4Xq82DUKHptK0mR6FWBgikach5KFTmFwexOoF7gsOwU6YqwcasgmogTMyC6A87ZxuvYcvANy/Xo4jd1qpHM3rynQxq7Qbzr6JDhoLeeWIbmXcwplWVzwKo6B2Y9jDmNXQnn+m6Qw==
  template:
    metadata:
      creationTimestamp: null
      name: forgejo-registry-push
      namespace: b4mad-forgejo-test
    type: kubernetes.io/dockerconfigjson
---
