apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-oauth-secret
  namespace: b4mad-forgejo-test
spec:
  encryptedData:
    key: AgBm9uS3lT/HsYlIhF+PWSSgqMjMAlQPYjXR48AWwOeyvkJC9eJAcESiOeX9/dlGjFb5f6EfiGbDaUUVs5RRZYXc88buCFRcwSPtVitoRFbC9QpcMtKdpmGzfsj4xDZvseGMS3HkyMZGBV7QDaXSvKlZd9MKM1H7d31cbclhSwDXYVQ6kD+flZTQSIZOy/IT9K0FZcs2kwvffW4juFOf+dk9Yw/bFx0t8DNaR7HBi2zkq/fkRUVss6LljAARWj09958/joxxnnbEpQwECl09horOwjHVAyj+/Zji/EzlR4kM1dAip4zrmgjDYRG/x3aP0n0dnuoR9e+D+xXzscz61qoEc6iR/fLs3PzgkNRs26ttBy6UFCKUhLumf6LnOYH3kmLcNdpEbwyaw2qsnTuBtfLux17nwh+kkzJbmOGhYzX6pG9Vh5Rwm35smGmf4dH2OgoAVt7DxDIxJknHHu31+wRqp0IYgdCmUsbLYBSv5r037S2oaoVZCqyDa3PH7gTRfhvpMg5bAFzna38tVNIwghotZNQcd/bRztrIPiM0UXXfAPeliI+emMDU9VtyVCoWdgQZIhjX5AC6jsawWyLU/S3BAPpLM4ywTHDEuMfVJ+GMEHh4PNAa5q5V8+b1LCbzfabcXg35i7HBn1mBb1hf5mkk4wN5QWoHvqkHI/p3hbThV8fJeEfPpDfAwNh3Ayze5LdhVZecptXV
    secret: AgDIwcRWAxIO3VZTFt3mjGiq+F2MDML2iqVIJDZTJDQgZZ4prNors9F/MifpfrR5anNOLrZYlR03cV6w9VDU4XxifGY9gCh6IrOOgZqH2kMiLqX8yTPG7tHIJS3ScjSdKvjYkc8cTqJKOYu3Vmx3bqhcKarweaNCTkZCT1UCa6dU1B/JsAF8AwXdFb9DGR90dKEOAiryd/M1XkkVgQiFI5tkeRSy7AupZcQPp1Y81J0bCYm3SHTWFeDXqdab9ZmUSkP58OVdtygvNiZ7N8OWUQ1xQj+dgTSjR3GRI8SoorXAhwW2d1RJ2MnbuECZO+8viH4Ik+XEL1mpKVyIBe+38Hpxjjgoh9aWrCdXqlakrILc7aw6o20bz+hHST6GZHSuWLpfC2kJX9vM3XaFv3vgQVWE8hPkeak26/kDlMvzlqscz4Htd2w2wuAzycUlPXmvpdvD8Deba/s6lH7wR0loOywQ20kdIEk1uAT7P6mmaqjKr058H5j8/Aw/8xARjVErDH5W7R0F87//yb32lnM0x2TZgn3dW1UN4mVLBfZhdems5tE1tF1WYviHoBc9Z/5LDyUO1/rdH6oEiX/vjYuJH5pWL/YPiaBfY3b/Rev6I2b+PXyqIpxLSJIWYzUMMYCKo01dxWT7vivuvh6ji74DeJuyEa4GTNSPLNlFXFrF0u0NBk7VpSrJ6GWo7ZlTW18wsFGifnpBqbpGw5DXsWQaFlncvS2fuUISYaPx9P5/2eBu2Q==
  template:
    metadata:
      creationTimestamp: null
      name: forgejo-oauth-secret
      namespace: b4mad-forgejo-test
---
