apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/display-name: "#B4mad Forge"
    openshift.io/description: "Forgejo software forge for the #B4mad Network."
    openshift.io/cluster-monitoring: "true"
  labels:
    b4mad.operate-first.cloud/owner: goern.b4mad.net
    argocd.argoproj.io/managed-by: op1st-gitops
  name: b4mad-forgejo
