apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-oauth-secret
  namespace: b4mad-forgejo
spec:
  encryptedData:
    key: AgCdXTlNVs2V07owLySOL8xMPn5z/XMR5prBQtNC6whVS6eomDHr3rx134s2nXhcNrgNZ1+B4U/1k1n3yeT+dn1wrV2bXd6blwi5BSx0jwvdkIEsZtp9/P4BNyt09wv4IsmRohtmdGZZNGbA0FOLNWcCN2RoQ99dGDT6WyCQR0npL/WOvuh0tSL/ado5r4xb4X1vuL4PG2FG+jsoY+pzqcVLXSlqi7ZzT+1pFryBLGWwb5SNtD5kIZgkpwztCzYtuNJDug+85HKPtNDWDb9sle/5h+ZmuWFAQ9AFwit2HjRCowEaTLVz/cgTkSBTWAWfle2Qpbbqyjz+7GdTA7NtBtkwrA+kM4imdQ+bxWw+04RSezt1SvC0WJj6g2MORtFXR55mtbBI11WCERs8Vr9Ldqbgtu2+iACif0geO/H5o5L6MteBDEznL/M0cDl/DM0yWQle5agR2NmWBORJ63cYt/JLiRZ7SnDcRJ5r26jpwgSN0+FmI3xivp0wxzC9Waxacpkrg4Gs90te5nFlzmCSc3TZW78p62GTssTCfAjXcW7EpoML4oqgxGRjUWVY5Zd+T+35gX10IL2loe1DJkYrbNFy7Drdtkjhhdu0FM1exehWZjBrQ7uODwbnC8j/Fyx9cEwGN8mfmuacar6+vCB+drpLpKE3Gw49mMQs5Zdf0SSuTos7W0t1Zfam/If52t6Gg3MBW00NYMjC
    secret: AgBYLfrr7y0oqRNZQ7dE40+iEw9TJ40jMGfxGuMwRam/u/M0e03bgN5Csy63UbJBENLMt9J+VvY6YnPkiex7zh1aar4rEIU4p72TJTwR5ukWI2MTJmvKsq4WwCU9Zkc+wLfCtWSJvHxHa+a2Iil0dJnTse/PPJAaxkJKkrzw3EXtohJDs7uTzPz+kqvNRFdOe9PQ0SHZZJ9V67baf8g7f2/rzHBNi0SbLEfAupEu+jdyIms0m72Ov+ve8xUQ7IRj/scp46cNghDl0meieZneTKHlXW7zG+Fwq2BX1h9jr0oCqaA3PP+gPF/F6kmXYSQSha7rIDeu654yGLj6K/TuaqMbUvIUt+guk+QVCwf+pghn0pgfW3CH/6Hp0vxq8Q0T4Vh8jxcdmBVGgHOO1r37/H7Vm8QkhsHodxD3KAcAY+GRuziM395pVgIcfJTDTexX+s372+0IvRXlBfsk1cEhi1NWzu7BGdPENwI9yAzP5y6JMxWSR3EN6n/U0wGYYPKMSaZXWRC9rGpvxSU6zFot6KZweO9qphCX+TjC+3gtzKU+uhFRI3Bm8BEpANMsVUbktkT1lgu7H9y876WZRS9hvQL/Bw8eM7mOZAKu77d6IIR7FtTZ+sO8QiZ4barUkoq76XxvwrHNxX6MT1oYk4/xQXczK24VLoCjQsGf+mPeqtzER+vToDfi9FBDBTlWMMk8C2bnRfoUd0TAPea3r5BuJtRjcClE24dy3A5D6OVtCQw7TQ==
  template:
    metadata:
      creationTimestamp: null
      name: forgejo-oauth-secret
      namespace: b4mad-forgejo
---
