apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/display-name: "#B4mad Meshtastic Gateway"
    openshift.io/cluster-monitoring: "true"
  labels:
    b4mad.operate-first.cloud/owner: goern.b4mad.net
  name: b4mad-meshtastic-gateway
